### ISSUE TITLE
请问非 spring 程序如何感知biz包卸载

### ISSUE THREAD

**Issue by cwbhhjl** [sofastack/sofa-ark#1039]
我写了一个用来热加载的biz包，是普通的java程序，比如main函数里启动一个线程做一些事情，那么biz包被卸载时，应该如何感知到卸载的事件来做资源清理呢

**Comment by gaosaroma** [comment]
可以监听 AfterBizStopEvent 事件，事件机制详见： https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-event/

如：
```java
public class EventHandlerSample implements EventHandler<AfterBizStopEvent> {
}
```

然后在模块启动的 main 方法中，把监听事件的对象注册则运行时中，如：

```java
EventHandler sample = new EventHandlerSample();
ArkClient.getEventAdminService().register(sample);
```

**Comment by cwbhhjl** [comment]
> 可以监听 AfterBizStopEvent 事件，事件机制详见： https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-event/
> 
> 如：
> 
> ```java
> public class EventHandlerSample implements EventHandler<AfterBizStopEvent> {
> }
> ```
> 
> 然后在模块启动的 main 方法中，把监听事件的对象注册则运行时中，如：
> 
> ```java
> EventHandler sample = new EventHandlerSample();
> ArkClient.getEventAdminService().register(sample);
> ```

感谢，我试一下
