### ISSUE TITLE
Old version of ark-biz still running after switching to new version — is this expected?

### ISSUE THREAD

**Issue by hokamc** [sofastack/sofa-ark#1040]
### Describe the question or bug

I encountered an issue while using ark-biz. After switching to a new version of ark-biz, the old version seems to continue running alongside the new one. Is this expected behavior?

### Expected behavior

After switching to the new version of ark-biz, the old version should no longer be accessible.

### Actual behavior

Both the old and new versions are running simultaneously without any issues.

### Steps to reproduce

Steps to reproduce the problem:
1. Create an ark-biz and register the code inside the main() method.
2. Call the code from the master biz.
3. Switch to a new version of the ark-biz.
4. Call the code from the old version in the master biz and observe it still runs.

**Comment by lvjing2** [comment]
1. did you uninstall the old version? if not, then the old version should be running indeed, such as the timer task and so on.
2. the switch action, which set the old version deactivated, not mean the shutdown the old version, it just means the beans or services in old version should not be accessable any more. this is mainly depend on how RPC framework find the beans or services, ***did the RPC framework recognize the deactivated status of old version.***

**Comment by hokamc** [comment]
I see. So, it is expected that the code from the old version will remain accessible until it is uninstalled. We are considering leveraging this feature to implement green-blue deployment for ark-biz.
