### ISSUE TITLE
公共jar包共享需求

### ISSUE THREAD

**Issue by nkorange** [sofastack/sofa-ark#1045]
### Feature description

假设我的项目名为app，这个app项目依赖了2个二方包lib1, lib2。这3个项目都依赖了一个三方包lib3，且lib1和lib2依赖的lib3版本为1.0，而app项目里依赖的lib3版本为2.0。依赖结构如下：

app -> lib1 -> lib3:1.0
       -> lib2 -> lib3:1.0
       -> lib3:2.0

目前一种解决方式是将lib1和lib2打包为ark plugin，这样就可以和app项目里的lib3:2.0共存了。但是这样的问题是lib1和lib2插件包里都包含了lib3:1.0，等于是重复打包了，会让应用app的可执行包变的很大。
有没有版本让lib1和lib2不重复打包lib3:1.0，但是又能够实现lib3:1.0和lib3:2.0共存呢？我试了一些写法好像都不行。
麻烦sofa-ark社区的老师指导！

**Comment by lvjing2** [comment]
首先需要知道解决这个问题的收益有多少呢？值不值得去解决，如果确实要解决这个问题，可以参考 com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook 写个 plugin 的 classLoaderHook，不确定是否可行，没这么用过。

**Comment by nkorange** [comment]
@lvjing2 感谢，已经通过这种方式调试通了
