### ISSUE TITLE
Should we put our further plan of this project on the milestone?

### ISSUE THREAD

**Issue by khotyn** [sofastack/sofa-ark#11]
We can put our further plan on the milestone, so those who are interested in this project cat see it. And  we even can relate the issues to the milestone to organize the issues better.

@straybirdzls @QilongZhang

**Comment by QilongZhang** [comment]
good idea.  the following features may need to be implemented at high priority.
+ support juint test framework and spring-test
+ support resource to be exported and imported elegantly

@straybirdzls @khotyn

**Comment by khotyn** [comment]
@QilongZhang OK, you can write issues about those two features, and relate them to a milestone. When you done, please comment on the thread and I'll close the discussion.

**Comment by QilongZhang** [comment]
@khotyn  done.  Progress of related issues can be seen on the KanBan
