### ISSUE TITLE
Use regular match to support export/import resource 

### ISSUE THREAD

**Issue by QilongZhang** [sofastack/sofa-ark#113]
Use regular match to support export/import resource instead of exactly resource name.

**Comment by johnyannj** [comment]
正有疑问，对于spring寻找classpath下的资源文件，大都使用
PathMatchingResourcePatternResolver

classpath*:/xxx/*.xml

它的原理是，先找/xxxx,  然后列举这个目录下的文件进行匹配。
如果按目前sofa-ark的设计，即便设置导出/xxxx/a.xml， Spring也是找不到的。

**Comment by QilongZhang** [comment]
> 正有疑问，对于spring寻找classpath下的资源文件，大都使用
> PathMatchingResourcePatternResolver
> 
> classpath*:/xxx/*.xml
> 
> 它的原理是，先找/xxxx, 然后列举这个目录下的文件进行匹配。
> 如果按目前sofa-ark的设计，即便设置导出/xxxx/a.xml， Spring也是找不到的。

资源的导入导出目前只做了精确匹配，满足蚂蚁内部的一些特殊使用场景。之前也考虑过做成正则匹配，只是目前还没有类似的需求，你可以简单描述下你们的需求背景。

**Comment by johnyannj** [comment]
举例，我们的应用是模仿开源软件 apache/servicecomb-java-chassis

https://github.com/apache/servicecomb-java-chassis/blob/master/foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/BeanUtils.java

它的启动原理就是利用Spring 加载各个jar包（各个plugin）里的META-INF/spring/下面的xml文件
```

  public static final String DEFAULT_BEAN_RESOURCE = "classpath*:META-INF/spring/*.bean.xml";
.....
 public static void init() {
    init(DEFAULT_BEAN_RESOURCE);
  }

  public static void init(String... configLocations) {
    prepareServiceCombScanPackage();

    context = new ClassPathXmlApplicationContext(configLocations);
}

```

我再前面提到的，Spring寻找classpath下面的文件，是使用的PathMatchingResourcePatternResolver这个类。它并不会调用ClassLoader的getresources(META-INF/spring/xxxx.bean.xml)
而是调用ClassLoader的getResources(META-INF/spring)
然后列举jar包里的目录得到所有的 META-INF/spring/*.bean.xml

如果使用sofa，指定导出resource是META-INF/spring/xxxx.bean.xml
Spring调用的 getResources(META-INF/spring)， sofa-ark的classloader会返回找不到。

**Comment by lylingzhen** [comment]
@lvjing2 帮忙回答一下。

**Comment by lvjing2** [comment]
指定为 META-INF/spring/ 级别试试

**Comment by lvjing2** [comment]
由于该 issue 已经超过一年，当前开始自动关闭，如果问题，请重新打开。
