### ISSUE TITLE
sofa-ark-maven-plugin support for running integration test 

### ISSUE THREAD

**Issue by lunasxk** [sofastack/sofa-ark#114]
### Your question

https://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html , springboot based ark plugin
now not support for running integration test while package, we now need for this function, wondering if
this could be done in future version

**Comment by QilongZhang** [comment]
@lunasxk  we has support integration test in spring boot.  http://www.sofastack.tech/sofa-boot/docs/sofa-ark-ark-demo
