### ISSUE TITLE
Replace the generic declaration with new diamond grammar in Java 7

### ISSUE THREAD

**Issue by khotyn** [sofastack/sofa-ark#16]
We change the generic collection declaration from the new diamond grammar in Java 7 back to older grammar before Java 7 due to the formatter problem which I think is not the right way to solve the problem.

We should fix the formatter so it can deal with the new diamond grammar in Java 7 in stead of change the grammar back before Java7.

@QilongZhang @straybirdzls

**Comment by khotyn** [comment]
The reason why formatter can not deal with the new Grammar in Java 7 is because in the `Formatter.xml` we set the compiler source to 1.5, change the compiler source to 1.7 should fix the problem

**Comment by straybirdzls** [comment]
great!!
