### ISSUE TITLE
ZipInflaterInputStream native memory leak

### ISSUE THREAD

**Issue by wgqazll** [sofastack/sofa-ark#211]
我们在使用ark 0.6.0版本时，发现系统响应时间变长，发现为系统频繁YGC，但一次FULL GC后，系统就恢复正常，后来看了美团的一篇技术文章（https://mp.weixin.qq.com/s/aYwIH0TN3nSzNaMR2FN0AA）发现ark 0.6.0里的ZipInflaterInputStream的写法和spring-boot2.0.4版本一致，这种写法存在问题，需要加上close方法

- SOFAArk version: 0.6.0

**Comment by wgqazll** [comment]
YGC的时间为100ms左右，FGC后时间降下来了

**Comment by QilongZhang** [comment]
@wgqazll  非常感谢，1.0.0 版本会整体对 SOFAArk 性能优化，尤其针对启动速度，启动期gc.  有兴趣，这个 Fix 可以 PR 至 1.0.0 版本。

另外，能否介绍下你们是哪个公司以及使用场景？

**Comment by glmapper** [comment]
[ZipInflaterInputStream native memory leak](https://github.com/spring-projects/spring-boot/issues/13935)
