### ISSUE TITLE
Reduce GC pressure during ark startup.

### ISSUE THREAD

**Issue by QilongZhang** [sofastack/sofa-ark#227]
+ 空 Spring Boot Web 应用运行在 SOFAArk 热点对象分配：
![image](https://user-images.githubusercontent.com/8833026/56207069-6bab9c80-6080-11e9-90bc-92ccc3b15806.png)

大部分临时对象的产生发生在 Jar 文件解析(含类加载)，这一块需要优化，已知的几点优化参考 Spring Boot
+ https://github.com/spring-projects/spring-boot/issues/11207
+ https://github.com/spring-projects/spring-boot/issues/14561
+ https://github.com/spring-projects/spring-boot/pull/18515

其他优化点还在研究中

**Comment by lylingzhen** [comment]
Ark 2.0 已经对 Jar 包加载进行了大幅优化，我理解问题已经解决。
@lvjing2 double check 一下。

**Comment by lvjing2** [comment]
是的
