### ISSUE TITLE
SOFAArk 0.6.0 多Web应用合并部署遇到的问题

### ISSUE THREAD

**Issue by jiashuntian** [sofastack/sofa-ark#228]
### Your question
1，命令行启动模式下 配置了宿主 Biz 名 com.alipay.sofa.ark.master.biz 依然提示 Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: Master biz should be configured when deploy multi biz.
配置文件路径：conf/ark/bootstrap.properties
排查原因：url = this.getClass().getClassLoader().getResource(ARK_CONF_FILE); 返回是null
2，IDE 启动模式下可以获取到配置的宿主 Biz 名，宿主启动正常，非宿主模块启动报错：
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] web-ark-plugin : can not load class: org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader

### Your advice

另外希望提供多Web应用合并部署的示例项目。

### Environment

- SOFAArk version:0.6.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
问题一： 辛苦将 demo 包发给我看下

问题二： 原因应该是非宿主模块没有引入 `sofa-ark-springboot-starter` 依赖

多 Web 合并部署示例：https://github.com/QilongZhang/jarslink-demo/tree/master/multi-web-app-sample

**Comment by QilongZhang** [comment]
@jiashuntian  描述下你的操作方式？ 我这边打包是正常运行的

**Comment by QilongZhang** [comment]
@jiashuntian  操作是正确的，demo 不需要任何修改。 尝试下删掉本地 ark 的仓库依赖，重新拉包呢。

**Comment by QilongZhang** [comment]
@jiashuntian  我这边找了台linux 机器是可以的，晚点看在 windows 是否可以复现你的问题。另外demo更新了一个脚本，麻烦也请看下直接执行脚本是否报错。

**Comment by QilongZhang** [comment]
@jiashuntian  感谢反馈，确定是 windows 环境相关的问题，已经复现。

**Comment by jiashuntian** [comment]
忘了告知你我的运行环境，给你排查问题带来了麻烦，实在抱歉，非常感谢您的热心答疑。

**Comment by cnodin** [comment]
升到1.0.0-SNAPSHOT好像并没有解决问题啊。代码在
`public List<URL> getProfileConfFiles(String... profiles) {
        List<URL> urls = new ArrayList<>();
        for (String profile : profiles) {
            URL url;
            if (StringUtils.isEmpty(profile)) {
                url = this.getClass().getClassLoader()
                    .getResource(ARK_CONF_FILE);
            } else {
                url = this.getClass().getClassLoader()
                    .getResource(String.format(ARK_CONF_FILE_FORMAT, profile));
            }
            if (url != null) {
                urls.add(url);
            } else if (!StringUtils.isEmpty(profile)) {
                ReportUtil.reportWarn(String.format("The %s conf file is not found.", profile));
            }
        }
        return urls;
    }`
并不能获取到bootstrap.properties配置文件的URL地址，bootstrap.properties有在解压后的文件夹中。还请帮忙看看哈。

**Comment by cnodin** [comment]
看了下，跟#238 还是同样的现象，我的OS是win10。

**Comment by QilongZhang** [comment]
> 看了下，跟#238 还是同样的现象，我的OS是win10。

好的，我在确认下，这两个 issue 是同一个问题。

**Comment by cnodin** [comment]
用jar vtf 看，其他的都对，就这个bootstrap.properties的entry不太对。应该是com.alipay.sofa.ark.tools.writeConfDir这个方法有点问题吧。

**Comment by QilongZhang** [comment]
> 用jar vtf 看，其他的都对，就这个bootstrap.properties的entry不太对。应该是com.alipay.sofa.ark.tools.writeConfDir这个方法有点问题吧。

对的，打包的时候没有写正确的路径，也是在这里fix的。

**Comment by cnodin** [comment]
用个比较粗暴的写法，在writeConfDir里jarWriter.writeEntry(entryName, new FileInputStream(subFile));代码前加了一句：entryName = entryName.replace("\\", "/");。解决问题。

**Comment by jrqxlicong** [comment]
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException 这个问题还没解决吗？
