### ISSUE TITLE
动态API的方式安装卸载 Biz 应用资源释放问题

### ISSUE THREAD

**Issue by jiashuntian** [sofastack/sofa-ark#230]
https://github.com/QilongZhang/jarslink-demo/tree/master/multi-web-app-sample
在web模块合并部署示例项目基础上,通过api进行动态安装卸载app-two模块,app-two模块没有打包进可执行jar里，二是放在固定一个磁盘目录下；对app-two模块多次执行安装卸载都提示成功，但发现内存持续增加，另外卸载后 磁盘目录上的app-two模块jar删除不掉，提示在java进程中占用着。为了验证app-two模块是否还存活，在app-two模块中起了一个新线程，间隔数秒打印信息，卸载app-two模块后，线程依然存活持续打印信息。
如何才能完全从内存中回收卸载的模块，解除资源占用？

- SOFAArk version:0.6.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10
- Maven version:
- IDE version:

**Comment by loveslikey** [comment]
有相同的疑问，重复安装卸载几次，内存就变得特别大

**Comment by QilongZhang** [comment]
@jiashuntian  收到反馈，在复现问题排查。

**Comment by loveslikey** [comment]
@jiashuntian 你好，打扰问下找到了原因了吗？我现在用不了几次装卸，内存就不够用了，好处理吗？

**Comment by QilongZhang** [comment]
> @jiashuntian 你好，打扰问下找到了原因了吗？我现在用不了几次装卸，内存就不够用了，好处理吗？

抱歉，web 应用卸载没有做好完整的测试工作，目前分析下来最大的问题来自于 `ArkTomcatWebServer` 内部匿名线程没有关闭以及 `ArkTomcatEmbeddedWebappClassLoader` 和 Tomcat 容器内部的  ClassLoader 存在父子关系，后者相对负责，还需要研究下如何解决，我们会尽快在1.0.0-SNAPSHOT 版本fix.

**Comment by loveslikey** [comment]
@QilongZhang 你好这个问题解决了吗？或者有其他的临时替代方案吗？

**Comment by QilongZhang** [comment]
> @QilongZhang 你好这个问题解决了吗？或者有其他的临时替代方案吗？

下周发布 1.0.0 版本，修复该问题.

**Comment by jiashuntian** [comment]
1.0.0版本什么时候发布？

**Comment by QilongZhang** [comment]
> 1.0.0版本什么时候发布？

1.0.0-SNAPSHOT  已经 fix 这个问题了，你可以先验证下， pr review 结束就发布。

**Comment by AJ-Liang** [comment]
> > 1.0.0版本什么时候发布？
> 
> 1.0.0-SNAPSHOT 已经 fix 这个问题了，你可以先验证下， pr review 结束就发布。

请将相差issue关联一下，谢谢
