### ISSUE TITLE
关于pom的传递依赖如何处理

### ISSUE THREAD

**Issue by johnyannj** [sofastack/sofa-ark#239]
### Your question

假设我在写一个pluginA

pluginA 的pom里依赖了开源软件B 
B的pom依赖开源软件C

B我想export出去
C不想export出去。

业务如果依赖PluginA， 就会通过pom的传递 看到C。 其实不我想暴露C。 我应该怎么做呢？

我目前的做法是，在pluginA的pom在对B的依赖中exclude掉对C的依赖， 然后直接依赖C，同时设置C的&lt;optional&gt;true&lt;/optional&gt;

问题是假设A依赖很多软件，这些软件又会向上依赖其它很多软件。 我该这么办呢？这是个很棘手的问题。

**Comment by QilongZhang** [comment]
一般都是设置  <optional>true</optional>  实现的，之前看 Spring  Boot 的源代码也是这种写法。

**Comment by QilongZhang** [comment]
这个 issue 我先关了，后续如果有问题，可以重新打开。
