### ISSUE TITLE
IDE环境运行的时候是如何排除Plugin引入的jar包的干扰

### ISSUE THREAD

**Issue by johnyannj** [sofastack/sofa-ark#246]
前置条件：
pluginA包的pom传递引入了B.jar包(备注：B.jar里的class也是pluginA要export的)

问题：
当IDE里运行的时候，classpath里的plugin包可以由PluginClassloader加载。 但是B.jar会被BizClassLoader加载了。

可能会导致Biz 在getResources的时候， 会同时加载到PluginA里的B.jar和Biz里的B.jar 里的资源

**Comment by QilongZhang** [comment]
参考 maven optional 的用法 https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by johnyannj** [comment]
首先pluginA.jar 是业务必须引入的。
其次B.jar 是pluginA导出的，业务编译需要它，PluginA 必须把B.jar 传递给业务。

你的意思是让我在pluginA的pom里把B.jar设置为optional=true?

biz依赖PluginA， 然后自行依赖B.jar(设置为provided)?

**Comment by QilongZhang** [comment]
> 首先pluginA.jar 是业务必须引入的。
> 其次B.jar 是pluginA导出的，业务编译需要它，PluginA 必须把B.jar 传递给业务。
> 
> 你的意思是让我在pluginA的pom里把B.jar设置为optional=true?
> 
> biz依赖PluginA， 然后自行依赖B.jar(设置为provided)?

嗯，是的，目前是这种做法，另外 plugin 提供了一个 shade 的功能，除了将依赖包打进plugin，也会将这些类shade 进plugin，这样对应用可见。

**Comment by johnyannj** [comment]
@QilongZhang  这个问题我有个建议，不值是否可行。

把pluginA.jar开放的jar包文件名， 写到PluginA.jar的Manifest里的，在运行时从BizClassloader里剔除掉。

**Comment by QilongZhang** [comment]
> @QilongZhang 这个问题我有个建议，不值是否可行。
> 
> 因为optional的方式使用太麻烦了， 使用shade 方式会让业务不知道plugin引入了哪些jar包，可能造成重复引入。
> 
> 那么把pluginA.jar导出的jar包文件名， 写到PluginA.jar的Manifest里的，在运行时从BizClassloader里剔除掉是否可行呢？

optional 这种方式是很正常的用法，可以参考 Spring Boot Starter, 基本都是 optional 控制依赖的传递。

PluginA 写在 Manifest 文件不可以取，一个 jar 不一定所有的类都需要导出。

**Comment by johnyannj** [comment]
我是站在使用plugin的业务的角度出发看待这个问题的， pluginA里要export的jar包，就是要让业务看到的，并不是说可选的， 和spring boot starter什么的不一样， 使用optional在语义上说不通。

如果业务依赖pluginA开发，只要依赖pluginA的pom就行了，这是最直接的方式。

如果我想依赖pluginA开发，依赖pluginA的同时，还要provided模式依赖  pluginA开放的其它jar包。 说不通的。

**Comment by QilongZhang** [comment]
> 我是站在使用plugin的业务的角度出发看待这个问题的， pluginA里要export的jar包，就是要让业务看到的，并不是说可选的， 使用optional在语义上说不通。
> 
> 和Spring Boot Starter场景不一样。 假设某个Spring Boot Starter依赖的jar包，如果是业务必须使用的，难道Starter的pom里会使用optional，让业务自己加吗？
> 
> 如果业务依赖pluginA开发，只要依赖pluginA的pom就行了，这是最直接的方式。
> 
> 如果我想依赖pluginA开发，依赖pluginA的同时，还要provided模式依赖 pluginA开放的其它jar包。 说不通的。

上面回复已经说明了， shade 的方案就是为了解决这种情况让业务使用时更加友好。 你提到的在 manifest 的配置不是一个较好的方案，像上面所说的，一个 jar 有些是需要导出的，有些是不需要导出的，这个时候就没法让 Biz 排除。

**Comment by johnyannj** [comment]
"一个 jar 有些是需要导出的，有些是不需要导出的，这个时候就没法让 Biz 排除。"===>好像ark-plugin-maven-plugin 并没有提供shaded的时候哪些class 可以排除掉。

shade的一个麻烦就是业务可能重复依赖了同样的jar包。没法排查。

**Comment by QilongZhang** [comment]
> "一个 jar 有些是需要导出的，有些是不需要导出的，这个时候就没法让 Biz 排除。"===>好像ark-plugin-maven-plugin 并没有提供shaded的时候哪些class 可以排除掉。
> 
> shade的一个麻烦就是业务可能重复依赖了同样的jar包。没法排查。

shaded 不需要排除指定的 class。

> shade的一个麻烦就是业务可能重复依赖了同样的jar包。没法查。
依赖了重复的包也没有问题，你还是举一个实际的例子吧~

**Comment by johnyannj** [comment]
前提条件：
我写了一个插件PluginA，依赖fastjson，pluginA里的类 和fastjson的类 我都要export出去。
这个插件的pom按你说的，应该是这样的
```
    \<groupId\>com.XXX\</groupId\>
    \<artifactId\>pluginA\</artifactId\>
    \<version\>1.0.0\</version\>

    \<dependencies\>
        \<dependency\>
            \<groupId\>com.alibaba\</groupId\>
            \<artifactId\>fastjson\</artifactId\>
            \<version\>1.38\</version\>
            \<optional\>true\</optional\>
        \</dependency\>
    \</dependencies\>
```
然后我有个业务Biz，要使用PluginA。 那么他的pom要这样写：
```
    \<groupId\>com.yyyy\</groupId\>
    \<artifactId\>biz\</artifactId\>
    \<version\>1.0.0\</version\>

    \<dependencies\>
        \<dependency\>
            \<groupId\>com.XXX\</groupId\>
            \<artifactId\>pluginA\</artifactId\>
            \<version\>1.0.0\</version\>
        \</dependency\>
        \<dependency\>
            \<groupId\>com.alibaba\</groupId\>
            \<artifactId\>fastjson\</artifactId\>
            \<version\>1.38\</version\>
            \<scope\>provided\</scope\>
        \</dependency\>
    \</dependencies\>
```

我的理解对吗？

**Comment by QilongZhang** [comment]
> 前提条件：
> 我写了一个插件PluginA，依赖fastjson，pluginA里的类 和fastjson的类 我都要export出去。
> 这个插件的pom按你说的，应该是这样的
> 
> ```
>     <groupId>com.XXX</groupId>
>     <artifactId>pluginA</artifactId>
>     <version>1.0.0</version>
> 
>     <dependencies>
>         <dependency>
>             <groupId>com.alibaba</groupId>
>             <artifactId>fastjson</artifactId>
>             <version>1.38</version>
>             <optional>true</optional>
>         </dependency>
>     </dependencies>
> ```
> 
> 然后我有个业务Biz，要使用PluginA。 那么他的pom要这样写：
> 
> ```
>     <groupId>com.yyyy</groupId>
>     <artifactId>biz</artifactId>
>     <version>1.0.0</version>
> 
>     <dependencies>
>         <dependency>
>             <groupId>com.XXX</groupId>
>             <artifactId>pluginA</artifactId>
>             <version>1.0.0</version>
>         </dependency>
>         <dependency>
>             <groupId>com.alibaba</groupId>
>             <artifactId>fastjson</artifactId>
>             <version>1.38</version>
>             <scope>provided</scope>
>         </dependency>
>     </dependencies>
> ```
> 
> 我的理解对吗？

不一定的，因为 Biz  编译时可能不需要依赖 fastjson。

**Comment by johnyannj** [comment]
可能我的举例不是很恰当，不应该使用fastjson。

fatjson换成yyy吧，是业务编译必须的。是不是就应该上面这种做法。

就是业务需要依赖pluginA的同时，还要依赖yyy ， 比较麻烦。

**Comment by QilongZhang** [comment]
> 可能我的举例不是很恰当，不应该使用fastjson。
> 
> fatjson换成yyy吧，是业务编译必须的。是不是就应该上面这种做法。
> 
> 就是业务需要依赖pluginA的同时，还要依赖yyy ， 比较麻烦。

嗯，是的，这种情况使用有些麻烦，除了 shade ，目前没有想到更好的解法，这块如果有好的思路欢迎贡献哈，上面提到的在 manifest 记录的方案有一些缺陷。
