### ISSUE TITLE
Add Integration CI Test

### ISSUE THREAD

**Issue by straybirdzls** [sofastack/sofa-ark#25]
Currently we only have unit test, this is not enough, when there are huge code changes, we have to do much manual test to guarantee code stability.

This can be done on next milestone

**Comment by lylingzhen** [comment]
@straybirdzls 这块我们当时有什么想法、建设或进展么。
我认为在社区我们需要建设与 SpringBoot 的 CI 测试，重点保障与 SpringBoot 各版本和 SDK 的类加载兼容性。这块我们计划争取能在 6 月底完成第一版。
