### ISSUE TITLE
Bytes.littleEndianValue 求教

### ISSUE THREAD

**Issue by AJ-Liang** [sofastack/sofa-ark#254]
想了解一下这个方法的主要作用与原理，请大神指教一下

**Comment by QilongZhang** [comment]
[谷歌下大端小端](https://www.google.com/search?q=little+endian+big+endian&oq=little+endian++&aqs=chrome.3.69i57j0l5.11116j0j7&sourceid=chrome&ie=UTF-8) 可以搜到你要的答案

**Comment by AJ-Liang** [comment]
> [谷歌下大端小端](https://www.google.com/search?q=little+endian+big+endian&oq=little+endian++&aqs=chrome.3.69i57j0l5.11116j0j7&sourceid=chrome&ie=UTF-8) 可以搜到你要的答案

感谢
