### ISSUE TITLE
plugin 加载的设计理念请教

### ISSUE THREAD

**Issue by AJ-Liang** [sofastack/sofa-ark#262]
你好，我想了解一下 plugin 可双向加载的设计理念：

- biz 中的 plugin 与 plugin 在什么场景下需要双向加载呢？
- 我设想的场景应该是这样，如，biz 使用了 config-plugin 与 rpc-plugin 还有 runtime-plugin，而config-plugin与rpc-plugin都使用了 runtime-plugin。问题：这时 config-plugin 与 rpc-plugin 使用的 runtime-plugin 的版本不在同一版本，这样的话会不会也会有类冲突问题出现？

**Comment by QilongZhang** [comment]
> biz 中的 plugin 与 plugin 在什么场景下需要双向加载呢？

以你说的场景为例，runtime-plugin 导出相关的类，rpc 和 config 导入 runtime 相关的类；运行时，config 和 rpc 用的肯定是相同的版本。除了确保 runtime 是同一个版本，也能减小 config 和 rpc 的包大小，避免重复打包 runtime 相关的类。

**Comment by AJ-Liang** [comment]
其实就把runtime抽取出共享层了，其实runtime不同版本是不是应该也可以接受呢，这样对用户的易用性来说会更好一些。当runtime的版本是一致的，把它抽出共享层

**Comment by QilongZhang** [comment]
> 其实就把runtime抽取出共享层了，其实runtime不同版本是不是应该也可以接受呢，这样对用户的易用性来说会更好一些。当runtime的版本是一致的，把它抽出共享层

没明白意思，runtime 又是版本一致又是不同版本，看着晕 😓
