### ISSUE TITLE
Ark缺失Ark-biz根据指定版本运行的机制

### ISSUE THREAD

**Issue by kelvin-zhangy** [sofastack/sofa-ark#263]
### Your question

Ark API 缺失Ark-biz根据指定版本运行的机制

### Your scenes
同一个Ark-biz运行的时候会存在多个版本并存的情况

场景A: 比如一个场景中的同一个ark-biz会存在压测版本，灰度版本，基础流量版本等。
运行的时候会根据真正的业务流量性质指定ark-biz的版本去运行。

场景B:多个业务共用一个ark-biz，运行的时候根据不同的版本自由控制，相同的版本复用，提高利用率。

### Your advice

Ark-biz提高指定版本运行的机制。
eg:
ArkClient.invocationReplay(arkVersion, new Replay() {
Object invoke(){
//ark-biz逻辑
}
}

**Comment by QilongZhang** [comment]
感谢反馈，这个需求已经在计划中了，我们会尽快支持
