### ISSUE TITLE
sofa-ark 底层怎么做到切换不同的 classloader 来加载class

### ISSUE THREAD

**Issue by linzhouzhi** [sofastack/sofa-ark#266]
sofa-ark 底层怎么做到切换不同的 classloader 来加载class

**Comment by linzhouzhi** [comment]
为什么项目启动的时候会重新设置classLoader: Thread.currentThread().setContextClassLoader(com.alipay.sofa.ark.container.service.classloader)
直接启动 container 有什么问题么？ 还是有其它考虑

**Comment by QilongZhang** [comment]
容器启动需要包含自己的 classpath, 但是 java -jar 启动时， AppClassLoader  的 classpath 是不包含的，因此在启动容器的时候，会将 TCL  设置为容器的 ClassLoader.
