### ISSUE TITLE
sofaark 中的plugin是否可以不打包到ark包内部？

### ISSUE THREAD

**Issue by Alt-er** [sofastack/sofa-ark#274]
是否可以指定plugin路径，从指定路径中加载plugin。
例如 
      指定路径为 ./ark-plugin
      启动时从加载./ark-plugin/* 中的plugin jar包

**Comment by LeagendaryHe** [comment]
我也在研究sofaark 加个好友探讨下啊 1143191737(QQ)

**Comment by glmapper** [comment]
> 是否可以指定plugin路径，从指定路径中加载plugin。
> 例如
> 指定路径为 ./ark-plugin
> 启动时从加载./ark-plugin/* 中的plugin jar包

可以具体描述下这种使用方式的场景吗？
