### ISSUE TITLE
Resource cleanup issue when SOFAArk biz is uninstalled

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-ark#279]
* [#460 Unloading modules using the combined deployment feature of sofa-ark does not release related connections such as redis, rpc, etc. ](https://github.com/sofastack/sofa-boot/issues/460)

* #230 

* https://github.com/sofastack/sofa-boot/issues/464

**Comment by LeagendaryHe** [comment]
我也在研究sofaark 加个好友探讨下啊 1143191737(QQ)

**Comment by hpejustin** [comment]
We need a dynamic mechanism to resolve this problem, details to be discussed soon.

**Comment by hpejustin** [comment]
持续关注中！谈谈我的思路：卸载动作应该只是针对模块本身进行了操作，而模块创建的连接与业务场景相关，框架本身无法感知并清理相关资源。这种场景下是否考虑将模块与外部资源交互的逻辑剥离到一个单独的模块中(称之为基座)，由基座负责单独的连接创建、维护，模块只是进行调用而不维护连接，这样模块的释放就无需关注资源清理问题。 @LeagendaryHe

**Comment by lvjing2** [comment]
> 

把与资源相关的逻辑下沉在基座，模块作为轻量化的代码包动态合并部署，是内部使用的一种方式，可以减少大部分类卸载的问题。但是不是所有的业务应用可以改造成这种模式，所以关于资源清理的还提供了[事件的方式](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-event/)来允许主动清理资源。
