### ISSUE TITLE
Master biz should be configured when deploy multi biz. How to solve this problem

### ISSUE THREAD

**Issue by S-117-John** [sofastack/sofa-ark#281]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
#228
