### ISSUE TITLE
Jar package conflicts and conflicting classes are loaded via spi

### ISSUE THREAD

**Issue by fengdui** [sofastack/sofa-ark#288]
假如我依赖2个plugin A和B, A使用了tomcat 驱动包版本x,B使用了tomcat 驱动包版本y,
x y是使用线程上下文加载器加载， 这时候线程上下文加载器是bizClassloader，这时不知道用哪个plugin里面的驱动类吧

**Comment by glmapper** [comment]
@fengdui 如果你的插件 A 和 B 中导出了 相关类，会委托给具体的插件来加载，如果插件 A 和 B 中都没有导出，插件内部使用 pluginClassLoader ，biz 使用 bizClassLoader

**Comment by glmapper** [comment]
@fengdui i will be close current issue. if you have any other question, you can open it again.
