### ISSUE TITLE
Package ark package under windows, config directory can not be packaged into the jar package, baseDir is also configured

### ISSUE THREAD

**Issue by dxp909** [sofastack/sofa-ark#292]
### Describe the bug

项目根目录下增加了config目录，如下图：
![image](https://user-images.githubusercontent.com/4726312/65312584-67eaeb80-dbc5-11e9-975c-fd85e1766943.png)

pom文件配置
![image](https://user-images.githubusercontent.com/4726312/65312773-c7e19200-dbc5-11e9-9718-34cfaee3c119.png)

然后执行mvn package指令后，jar包内容如下：

![image](https://user-images.githubusercontent.com/4726312/65312684-9ff22e80-dbc5-11e9-8133-78fd7c2d26e6.png)

### Environment

- SOFAArk version:1.0.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):windows10
- Maven version:3.6.1
- IDE version:

**Comment by LeagendaryHe** [comment]
我也在研究sofaark 加个好友探讨下啊 1143191737(QQ)
