### ISSUE TITLE
Use the sofaark plugin, not the sofaboot project or the springboot project.

### ISSUE THREAD

**Issue by LeagendaryHe** [sofastack/sofa-ark#294]
使用sofaark插件，不是sofaboot项目或者springboot项目也可以吧，应该只要是 maven项目就行吧 按我的理解？

**Comment by glmapper** [comment]
> 使用sofaark插件，不是sofaboot项目或者springboot项目也可以吧，应该只要是 maven项目就行吧 按我的理解？

Currently, only supported in the springboot/sofaboot environment
