### ISSUE TITLE
duplicate sofaark container dependency

### ISSUE THREAD

**Issue by LeagendaryHe** [sofastack/sofa-ark#297]
when i depend three ark-plugin .jar in my springboot project and do maven clean install,,,maven indicate me that

 Failed to execute goal com.alipay.sofa:sofa-ark-maven-plugin:1.0.0:repackage (default-cli) on project springboot-ark-demo: Execution default-cli of goal com.alipay.sofa:sofa-ark-maven-plugin:1.0.0:repackage failed: duplicate SOFAArk Container dependency

![图片](https://user-images.githubusercontent.com/22810951/65367365-f497b700-dc62-11e9-97d9-b0ea779382e9.png)

![图片](https://user-images.githubusercontent.com/22810951/65367366-f9f50180-dc62-11e9-896e-4edc7734b0bf.png)

i wonder why it happend??  and hope that who can tell me reason...thanks

**Comment by sumou608** [comment]
@LeagendaryHe 

Have you solved it? I am also encountering this problem and it is quite distressing.
