### ISSUE TITLE
biz lifecycle event feature

### ISSUE THREAD

**Issue by quhw** [sofastack/sofa-ark#304]
### Your question

Ark biz has several lifecycle status (such as activated, deactivated). Sometimes the biz itself or the other biz modules need to be notified when the status changing. For example, for better  biz initialization or destruction. The SOFA lifecycle call does not meet the requirements, since the biz activated and deactivated is not a kind of sofa lifecycle. 

### Your scenes

For example, the master biz modules needs to know if a sub biz module is ready implicitely. During biz module upgrading, the old version of biz is deactivated and the new version is activated, but the master biz module cannot know this change without lifecyle event.

### Your advice

Provide lifecycle change event.

### Environment

- SOFAArk version: 1.0.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Linux and macos
- Maven version: 3.2+
- IDE version: Idea Intellij

**Comment by glmapper** [comment]
@quhw First of all, my understanding is that biz is parallel. In the scenario of merge deployment, although we proposed the concept of master biz, we still don't expect master to take too much responsibility. Therefore, if the status change of biz requires other biz awareness (if master can, then others can), then biz can be broadcast once in the container to notify other biz, which adds some complexity.

In addition, SOFAArk provides endpoints for monitoring biz status in containers, and to some extent, managing biz based on container level is more reasonable than mutual awareness between biz.

Of course, the problem you mentioned is very good, which is a very good feature for SOFAArk. If you are interested, you are welcome to provide a pull request for this feature.

**Comment by quhw** [comment]
Status notification across biz modules may not be necessary. As discussed with @caojie09  last night, container lifecycle event for biz module itself is meaningful. For example, a biz module may register some business information  (such as business extensions) in master module after activating. During a biz module upgrade, the old version and the new version of biz module may coexists for a while. The new version module starts up firstly and enters deactivated status. Now we have a problem, whether the new module should register new biz information in the master module now? If it does, the master module may call biz module according to the new biz information. But since the new module is not activated, the SOFA service still routes to old version, the invocation may fail. A solution is that the new module holds the registering action until the module is activated.

**Comment by glmapper** [comment]
@quhw 对于两个不同的模块来说（bizName 不同），执行安装操作之后，其状态就是 activated 状态；对于 同一模块，不同版本，目前 容器里面是只允许一个 版本的模块处于激活状态，向外提供服务（默认只会找激活状态的模块），如果希望调用非激活状态的版本，可以通过指定版本调用的方式来完成。

**Comment by glmapper** [comment]
> For example, the master biz modules needs to know if a sub biz module is ready implicitely. During biz module upgrading, the old version of biz is deactivated and the new version is activated, but the master biz module cannot know this change without lifecyle event.

回到你最先提到的这种场景，对于你提到的*During biz module upgrading, the old version of biz is deactivated and the new version is activated*是不对的。一个新的版本安装之后，其状态是 deactivated 状态（老版本处于 activated 状态），master biz 在查找服务时默认逻辑还是回去走老版本提供的逻辑服务，这种对于 ark/runtime 来说是合理的，如果想走新版本提供的服务有两种方式：

* 通过 switch 激活新版本
* 通过 ArkClient 指定版本调用

另外，biz 在安装的各个阶段其实是会发送相应的事件的，可以在 master 中提供一个  EventHandler 实现（EventHandler 是全局的生效的，对于所有的 biz 生命周期行为，都能监听到），监听所有的 biz 生命周期事件，然后再做相应的处理即可。
