### ISSUE TITLE
Biz module startup order problem

### ISSUE THREAD

**Issue by quhw** [sofastack/sofa-ark#310]
### Describe the bug

两个模块：
主模块：demo-app-bootstrap-1.0.0-SNAPSHOT-ark-biz.jar		
业务模块：demo-biz-1.0.0-SNAPSHOT-ark-biz.jar

默认的priority，conf/ark/bootstrap.properties指定了demo-app-bootstrap是主模块。

### Expected behavior

先加载demo-app-bootstrap，后加载demo-biz。

### Actual behavior

先加载了demo-biz，启动失败。
telnet localhost 1234，biz -a，发现demo-biz顺序在demo-app-bootstrap之前。biz -m看，两个模块的priority都是100。

后来pom.xml加了priority，问题解决。

应该master有最高优先级。

### Environment

- SOFAArk version: 1.0.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@quhw 所有 biz 的默认优先级都是 100，ark 在 pipeline 其中流程中，会对 biz 进行排序，然后决定 各个biz 的启动顺序，不会对 master 做特殊的处理
