### ISSUE TITLE
Plugin released services

### ISSUE THREAD

**Issue by tensecond** [sofastack/sofa-ark#321]
Plugin发布的服务问题
1、如何使用？
2、什么场景可能会用到其他plugin发布的服务

例子
有2个plugin，分别为plugin-A，plugin-B
1、plugin-A在插件入口实现类SamplePluginActivator中注册了context.publishService(SamplePluginService.class, new SamplePluginServiceImpl());
2、plugin-B也在插件入口实现类SamplePluginActivator中注册了context.publishService(SamplePluginService.class, new SamplePluginServiceImpl());
3、通过如下方式没有拿到发布的服务，得到ClassNotFoundException错误
ArkServiceContainerHolder.getContainer().getService(RegistryService.class).referenceService(SamplePluginService.class)

请问这个报错是什么原因，应该怎么获取plugin发布的服务？

**Comment by glmapper** [comment]
@tensecond 可以参考下 SOFAArk 中 web 插件和 config 插件实现
