### ISSUE TITLE
Can different biz-module both publish http services?

### ISSUE THREAD

**Issue by thoughtxeize** [sofastack/sofa-ark#325]
如果两个biz都想要发布http服务是否允许？能否像sofa区分context一样来分割开呢。

比如:
home-biz
/index/api/a
/index/api/b

foo-biz
/foo/api/a
/foo/api/b

**Comment by glmapper** [comment]
我理解你是希望两个biz 都是 web 应用，然后能够共享同一个端口，是这个意思吧

**Comment by thoughtxeize** [comment]
> 我理解你是希望两个biz 都是 web 应用，然后能够共享同一个端口，是这个意思吧

是的，我看到在sofaark的打包配置里可以配置webContextPath

可以通过这个配置来达到这个目标么

**Comment by glmapper** [comment]
@thoughtxeize 是的，web plugin 中有处理这部分，对于 Tomcat 来说，一个 Tomcat 下面可以有多个 Context 容器，如果两个 web 希望共用端口，就需要通过 webContextPath 来区分下。

**Comment by thoughtxeize** [comment]
Thanks a lot
