### ISSUE TITLE
官网与sofa-ark相关的示例运行报错

### ISSUE THREAD

**Issue by wuxiaohui0906** [sofastack/sofa-ark#334]
官网上下载的所有与sofa-ark相关的工程使用idea运行时都报如下错误，包括动态模块https://github.com/sofastack-guides/kc-sofastack-dynamic-demo.git工程，sample-ark-plugin等，请问是什么原因

- SOFAArk version:0.6.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10教育版
![2019-12-10_144814](https://user-images.githubusercontent.com/58681100/70502804-c5eff500-1b5c-11ea-8553-94bceee8acfc.jpg)
![2019-12-10_144827](https://user-images.githubusercontent.com/58681100/70502805-c6888b80-1b5c-11ea-809b-673bf5b8d24b.jpg)

- Maven version:3.6.1
- IDE version:2018.3.5

**Comment by glmapper** [comment]
@wuxiaohui0906 你需要提供你自己所运行的 demo ，官方提供的 kc-sofastack-dynamic-demo 工程需要部署额外的 SOFADashboard 及相关服务（例如 zookeeper），在运行案例工程前确保相关服务已经准备好。关于 sample-ark-plugin 及在 windows 版本下使用 ark 0.6.0 问题，请参考 #277 。

**Comment by glmapper** [comment]
and we provide a new guides for sofa ark, https://github.com/sofastack-guides/sofa-ark-dynamic-guides
