### ISSUE TITLE
How to not package the lib directory into the jar package when the biz package is packaged, and load the external lib directory when running?

### ISSUE THREAD

**Issue by dxp909** [sofastack/sofa-ark#336]
### Your question

biz包打包时如何不把lib目录打包到jar包里，运行时加载外部lib目录？

### Your scenes

项目里需要把多个工程打包成biz包，然后合并部署，打包成biz包后第三方依赖会放到lib目录下打包到biz包中，biz工程外部依赖都一样，如何把这些依赖实现共享？

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@dxp909 可以通过classloaderhook 机制使得所有子biz共享宿主biz中的依赖

**Comment by dxp909** [comment]
好的，多谢 @glmapper
