### ISSUE TITLE
How to reduce the size of Biz package

### ISSUE THREAD

**Issue by Divernia** [sofastack/sofa-ark#339]
### Your question

项目由多个Biz包构成，但是每个Biz中都有相同的jar包，怎样能够使得子Biz能够共享宿主Biz中的jar包，从而缩减包的总大小？能否提供相关示例呢？

### Environment

- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win10
- Maven version: 3.5
- IDE version: STS4

**Comment by glmapper** [comment]
@Divernia 这些包是业务包还是中间件层面的包，如果是中间件层面的，可以通过下沉插件的方式来实现共享，如果是业务层面的，可以通过 classloadehook 机制让子模块加载委托给 master来处理

**Comment by Divernia** [comment]
@glmapper 是中间件包，尝试过将中间件包落到底层plugin包中，作为共通依赖。但是最终打包还是因为传递性将plugin中的中间件jar包打到了Biz中。

**Comment by Divernia** [comment]
@glmapper OK已解决，上层Biz包中将plugin中的依赖scope设置为provided，然后plugin中将中间件所有类导出。
