### ISSUE TITLE
PluginClassLoader and BizClassLoader should invoke registerAsParallelCapable

### ISSUE THREAD

**Issue by caojie09** [sofastack/sofa-ark#346]
PluginClassLoader and BizClassLoader should invoke registerAsParallelCapable

oracle classloader document: https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html

> Class loaders that support concurrent loading of classes are known as parallel capable class loaders and are required to register themselves at their class initialization time by invoking the ClassLoader.registerAsParallelCapable method. Note that the ClassLoader class is registered as parallel capable by default. However, its subclasses still need to register themselves if they are parallel capable.

**Comment by glmapper** [comment]
补充：调用 Classloader.registerAsParallelCapable 方法，会开启并行类加载功能，把锁的级别从 ClassLoader 对象本身，降低为要加载的类名这个级别，换句话说只要多线程加载的不是同一个类的话，loadClass 方法都不会锁住。
