### ISSUE TITLE
bizState is not updated when getting BIZ_EVENT_TOPIC_AFTER_INVOKE_BIZ_START

### ISSUE THREAD

**Issue by quhw** [sofastack/sofa-ark#349]
### Describe the bug

订阅BIZ_EVENT_TOPIC_AFTER_INVOKE_BIZ_START事件，收到模块启动事件后getBizState()，发现状态是resolved，而非activated。这样导致无法判断模块到底是否成功启动，后续会变成activated还是未知resolved（多版本情况）。

### Expected behavior
先更新bizState，然后触发BIZ_EVENT_TOPIC_AFTER_INVOKE_BIZ_START。

### Environment

- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@quhw 对于”先更新bizState，然后触发BIZ_EVENT_TOPIC_AFTER_INVOKE_BIZ_START“我们有讨论过，没有使用这种策略是因为，对于 ark biz 来说，健康检查通过才会认为 biz 是启动正常的，所以需要通过 BIZ_EVENT_TOPIC_AFTER_INVOKE_BIZ_START 来先触发健康检查，然后再进行状态更新。对于你提到的场景，应该是因为健康检查失败导致biz 状态不符合预期，需要充业务层面去解决该问题
