### ISSUE TITLE
Using SOFAArk, Spring dependency injection problem

### ISSUE THREAD

**Issue by wapkch** [sofastack/sofa-ark#350]
最近在调研sofaark，因项目中使用spring依赖注入为通过接口注入，切换过程中问题如下：

依赖版本：
springboot：2.1.0
sofaark：1.0.0

案例如下：
- 接口IMyService，实现类MyService都定义在plugin中；
- 使用Spring依赖注入myService，通过接口接收；
  ```java
  @autowire
  private IMyService myService;
  ```
  - 启动报错;
  ```
  org.springframework.beans.factory.BeanNotOfRequiredTypeException:Bean named 'myService' is expected to be of type `IMyService` but was actually of type `myService`
  ```
 - 改为通过实现类注入，则启动成功
  ```java
  @autowire
  private MyService myService;
  ```

**Comment by wapkch** [comment]
@QilongZhang 历史项目中依赖注入都是这种用法，猜测是PluginClassLoader原因，请问是否有遇到类似问题？

**Comment by glmapper** [comment]
@wapkch plugin 一般用来下沉基础组件，业务服务应该在 biz 中来完成。如果期望在 plugin 中提供服务，可以参考插件服务设计。例如 config-ark-plugin 中提供的插件服务。

**Comment by wapkch** [comment]
@glmapper 多谢回复。找到问题了，原来plugin中没有将接口export。但还是没明白，既然在plugin中export就可以在容器中直接注入使用，为何还需要发布plugin插件服务呢？发布plugin插件服务主要是用在什么场景呢？

**Comment by glmapper** [comment]
@wapkch 插件服务属于容器级别的，可以提供给其他插件或者biz使用，这种使用是使用ark自己提供的注入方式注入的。plugin导出一般建议是类或者包级别导出，它导出的不是服务，是一个类或者包下所有的类

**Comment by wapkch** [comment]
@glmapper 感谢解答，我再理解一下是：plugin导出的是类，服务是由引入该类的biz提供。而插件服务是ark容器内独立的服务，其他插件或服务注入使用插件服务，走的是内部通信机制，类似biz与biz间的通信，和biz一样，每个plugin服务也有独立的Spring上下文。
