### ISSUE TITLE
The custom ClassLoaderHook implementation class cannot be loaded.

### ISSUE THREAD

**Issue by wapkch** [sofastack/sofa-ark#352]
### Your question

1. 自定义的ClassLoaderHook实现类无法被加载。
2. https://github.com/sofastack/sofa-ark/issues/159 中spring项目ark plugin化问题是否可以通过定义PluginClassLoaderHook，使用主bizClassLoader加载spring类来解决？

### Your scenes

问题1场景：
在plugin中定义了ClassLoaderHook实现类并导出，启动后ClassLoaderHook实现类并未被加载。看源码发现extension的加载默认路径为META-INF/services/sofa-ark,应该如何定义ClassLoaderHook实现类才能被正确加载？
ClassLoaderHook实现类：
```
@Extension(value = "plugin-classloader-hook")
public class PluginClassLoaderHook implements ClassLoaderHook<Plugin> {
    @Override
    public Class<?> preFindClass(String name, ClassLoaderService classLoaderService, Plugin plugin) throws ClassNotFoundException {
        return null;
    }
}
```
ExtensionLoaderServiceImpl中loadExtension逻辑：
```
public final static String EXTENSION_FILE_DIR = "META-INF/services/sofa-ark/";
public final static String fileName = "com.alipay.sofa.ark.spi.service.classloader.ClassLoaderHook";
Enumeration<URL> enumeration = resourceLoader.getResources(EXTENSION_FILE_DIR+ fileName);
```
问题2场景：
https://github.com/sofastack/sofa-ark/issues/159 提到spring项目ark plugin化后问题的两种解决方案：
- 项目去spring化
- spring 下沉为另一个 ark plugin

这两种方案对项目改造成本都比较大，否可以通过ClassLoaderHook解决？例如在plugin中定义ClassLoaderHook实现，使用主bizClassLoader加载spring类。
```
@Extension(value = "plugin-classloader-hook")
public class PluginClassLoaderHook implements ClassLoaderHook<Plugin> {
    @Override
    public Class<?> preFindClass(String name, ClassLoaderService classLoaderService, Plugin plugin) throws ClassNotFoundException {

        if (name.startsWith("org.springframework.")) {
            BizManagerService service = ArkServiceContainerHolder
                    .getContainer().getService(BizManagerService.class);
            String masterBizName = ArkConfigs.getStringValue(Constants.MASTER_BIZ);
            String version = "1.0.0";
            Biz biz = service.getBiz(masterBizName, version);
            return biz.getBizClassLoader().loadClass(name);
        }
        return null;
    }
}
```

@glmapper 麻烦帮忙看下上述问题，感谢！

### Environment

- SOFAArk version:1.0.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@wapkch 委托 master biz 去加载 Spring 的类理论上是可行的。

如果使得自定义的hook 生效：在 META-INF.services.sofa-ark目录下新建一个 名为 com.alipay.sofa.ark.spi.service.classloader.ClassLoaderHook 的文件，文件中写hook 类的全限定名 com.alipay.sofa.ark.container.service.classloader.hook.TestBizClassLoaderHook。参考 [这里](https://github.com/sofastack/sofa-ark/tree/master/sofa-ark-parent/core-impl/container/src/test/resources/META-INF/services/sofa-ark)

**Comment by wapkch** [comment]
@glmapper 非常感谢！
