### ISSUE TITLE
telnet tool biz -i command specific parameter format

### ISSUE THREAD

**Issue by SnapDL** [sofastack/sofa-ark#359]
请问biz -i 之后安装ark-biz参数具体应该怎么传的，官网没找到说明

我按照bizName:bizVersion:bizState?bizUrl=file://path 格式传，但是没有生效

- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): macOS 10.15
- Maven version: 3.6.0
- IDE version: IDEA

**Comment by glmapper** [comment]
@SnapDL 目前支持两种协议：1、biz -i file:///path    2、biz -i http://path
