### ISSUE TITLE
Can you suggest a common class library for each biz package to the same class path

### ISSUE THREAD

**Issue by iteaj** [sofastack/sofa-ark#368]
### Your question
现在的打包情况是如果多个biz包打在一起， ark动不动上百兆，基于每个biz包的依赖基本一致， 建议能否抽取公用的依赖
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@iteaj 可以通过将依赖下沉到插件中提供给 容器中的 biz 使用，以缩减 biz包大小
