### ISSUE TITLE
Refer to the sofa-dashboard-guides local build project and introduce the runtime-sofa-boot-plugin dependency to start the report within the idea [instance must be started before calling this method]

### ISSUE THREAD

**Issue by ahyoSolitude** [sofastack/sofa-ark#370]
### Your question
参照sofa-dashboard-guides本地构建项目，引入runtime-sofa-boot-plugin依赖后idea内启动报【instance must be started before calling this method】

describe your question clearly
连接zk报错，具体报错信息请参见附件中error.log

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment
win7 64位
- SOFAArk version:
0.6.0
- JVM version (e.g. `java -version`):
1.8
- OS version (e.g. `uname -a`):

- Maven version:
3.6.2
- IDE version:
intellij（在启动项内已关闭 enable jmx agent）

[ark-root.zip](https://github.com/sofastack/sofa-ark/files/4491639/ark-root.zip)
[error.log](https://github.com/sofastack/sofa-ark/files/4491643/error.log)

**Comment by glmapper** [comment]
related to #421
