### ISSUE TITLE
Sofaark not support EnableSwagger2 annotation

### ISSUE THREAD

**Issue by zhouyix** [sofastack/sofa-ark#376]
When importing swagger2 related package,below error happens

Error creating bean with name 'handlerAdapterComposite' defined in class path resource [SMVC-INF/kernel/advise/smvc-scheme-composite.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in com.alipay.mdda.web.home.interceptor.SwaggerConfig: Initialization of bean failed; nested exception is java.lang.LinkageError: loader constraint violation: when resolving method "org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.getObjectMapper()Lcom/fasterxml/jackson/databind/ObjectMapper;" the class loader (instance of com/alipay/sofa/ark/container/service/classloader/BizClassLoader) of the current class, springfox/documentation/spring/web/ObjectMapperConfigurer, and the class loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) for the method's defining class, org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter, have different Class objects for the type com/fasterxml/jackson/databind/ObjectMapper used in the signature

**Comment by zhouyix** [comment]
Could you please help us with this,it is urgent

**Comment by glmapper** [comment]
> Could you please help us with this,it is urgent

Please internal consultation
