### ISSUE TITLE
3.3.4 version Ark judges that there is a problem with MasterBiz

### ISSUE THREAD

**Issue by HeartBeat312** [sofastack/sofa-ark#378]
### Environment

- SOFAArk version: 3.3.4
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): mac
- Maven version: 
- IDE version:

com.alipay.sofa.ark.container.pipeline.HandleArchiveStage类134行判断有误
// master biz should be specified when deploy multi biz, otherwise the only biz would be token as master biz
            if (bizCount > 1) {
                AssertUtils.isFalse(
                    StringUtils.isEmpty(ArkConfigs.getStringValue(Constants.MASTER_BIZ)),
                    "Master biz should be configured when deploy multi biz.");
                String masterBizName = ArkConfigs.getStringValue(Constants.MASTER_BIZ);
                for (Biz biz : bizManagerService.getBizInOrder()) {
                    if (masterBizName.equals(biz.getBizName())) {
                        ArkClient.setMasterBiz(biz);
                    }
                }
            } else {
                List<Biz> bizList = bizManagerService.getBizInOrder();
                if (!bizList.isEmpty()
                    && **StringUtils.isEmpty(ArkConfigs.getStringValue(Constants.MASTER_BIZ))**) {
                    ArkConfigs.putStringValue(Constants.MASTER_BIZ, bizList.get(0).getBizName());
                    ArkClient.setMasterBiz(bizList.get(0));
                }
            }

**Comment by glmapper** [comment]
You mentioned is not a fatal problem, the design is like that
