### ISSUE TITLE
Multiple biz merge deployment must configure multiple webContextPath

### ISSUE THREAD

**Issue by wapkch** [sofastack/sofa-ark#379]
### Your question

SOFAArk 多 web 应用部署时，采用单 Host，多 context 模式。web 应用在打包 biz 时，需要增加 webContextPath 打包配置：
```
<configuration>
	<attach>true</attach>
    <webContextPath>/app</webContextPath>
</configuration>
```
### Your scenes

现有多个项目需要做合并部署, 但由于各项目的历史接口url定义无法抽出webContextPath, 且修改历史接口url成本非常高

### Your advice

多biz合并部署情况, 能否支持不配置指定的webContextPath, 使用默认的webContextPath=`/`

### Environment

- SOFAArk version: 0.6.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by wapkch** [comment]
@glmapper  烦请看下上述场景能否支持? 或者是否有其它方案不, 谢谢!

**Comment by glmapper** [comment]
> @glmapper 烦请看下上述场景能否支持? 或者是否有其它方案不, 谢谢!

目前暂无计划支持
