### ISSUE TITLE
can't inject ark container default service

### ISSUE THREAD

**Issue by tonyxu721** [sofastack/sofa-ark#384]
### 问题

Ark容器成功启动后，无法注入暴露的默认服务，比如PluginManagerService、EventAdminService. 测试项目：https://gitee.com/wesley721/sofa-acts（acts-sample/sofa-boot-run/TestController）

### 截图

![image](https://user-images.githubusercontent.com/23226155/86506603-66f91280-be03-11ea-98d3-c48555e59cf9.png)
![image](https://user-images.githubusercontent.com/23226155/86506604-6a8c9980-be03-11ea-9338-e6df30d4602b.png)

### 环境

- SOFAArk version: 0.5.2
- JVM version (e.g. `java -version`): 1.8.0_231
- OS version (e.g. `uname -a`): Darwin Kernel Version 19.0.0
- Maven version: 3.6.3
- IDE version: IDEA-2019.3.1

**Comment by glmapper** [comment]
@tonyxu721 why acts?

**Comment by tonyxu721** [comment]
@glmapper just use it's example.

**Comment by glmapper** [comment]
@tonyxu721 in fact, in ark env, some test framework cannot be work correctly, include acts.  and we also keep our energy to support this feature.

**Comment by tonyxu721** [comment]
@glmapper ths
