### ISSUE TITLE
例子项目的sample-springboot-ark 都没用到sample-ark-plugin，是怎么来验证插件的？

### ISSUE THREAD

**Issue by lhui1991** [sofastack/sofa-ark#398]
### Your question
如题，https://github.com/sofastack-guides/sofa-ark-guides
describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@lhui1991 关于插件使用，可以参考这篇文章：[ARK 插件基本规则及注意事项](http://www.glmapper.com/2019/08/28/sofa-ark-plugin-rule/)
