### ISSUE TITLE
Does ark plugin support being built as a spring boot starter

### ISSUE THREAD

**Issue by lichen782** [sofastack/sofa-ark#400]
### Your question

As we know quite a lot java libs nowadays in biz system are packaged as spring boot starters, once you use spring boot/cloud. Just want to know if a spring boot starter could be refactored to an ark plugin while we still could use spring boot features like autoconfigure, Condition, Conditional, Configuration etc. 

### Your scenes

describe your use scenes (why need this feature)

mentioned above. Now I translate into Chinese. 因为现今我们业务系统大多数二方库都是使用spring starter来构建的。想知道ark plugin是否能支持打包spring starters。我自己尝试了一下，container改造成ark container，spring starter直接打包成ark plugin，会遇到类转换问题。
Caused by: java.lang.ClassCastException: com.mydemo.Condition cannot be cast to org.springframework.context.annotation.Condition
	at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:125)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:218)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:586)
	... 48 more

原因是在如下方法中：
	private Condition getCondition(String conditionClassName, @Nullable ClassLoader classloader) {
		Class<?> conditionClass = ClassUtils.resolveClassName(conditionClassName, classloader);
		return (Condition) BeanUtils.instantiateClass(conditionClass);
	}

Spring在加载条件类的时候进行强转，但是conditionClass是通过ark的plugin classloader 来加载的，但是Condition这个spring基础类是通过biz classloader，也就是ark container 的class loader来加载的，类的classloader不兼容。

### Your advice

describe the advice or solution you'd like
麻烦提供可以work的方式。

### Environment

- SOFAArk version: 1.1.1
- JVM version (e.g. `java -version`): 1.8.0_201
- OS version (e.g. `uname -a`): Darwin Kernel Version 17.7.0
- Maven version: 3.6.1 
- IDE version: Intellij IDEA 2018 Ultimate

**Comment by glmapper** [comment]
@lichen782 支持打包 starter，但是是需要将 spring 也全部放在插件中进行导出

**Comment by lichen782** [comment]
> @lichen782 支持打包 starter，但是是需要将 spring 也全部放在插件中进行导出

谢谢回复，想知道一下，如果spring全部放在插件，那么引用插件的部分，还能使用spring web么

**Comment by glmapper** [comment]
@lichen782 Of course
