### ISSUE TITLE
how to get plugin service like Spring ApplicationContext/如何像spring ApplicationContext getBean一样获取插件服务

### ISSUE THREAD

**Issue by Charles19961002** [sofastack/sofa-ark#402]
### Your question

目前我有2个插件实现了同一个服务，我可以设置他们为不同的uniqueId，但是我需要在运行时通过业务来获取不同uniqueId的服务。
所以我需要知道如何像spring ApplicationContext getBean一样获取插件服务，或者有其他更好的方案。

### Your scenes

需要运行时获取指定uniqueId的服务应用

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@Charles19961002 可以把 uniqueId 作为参数，通过 SOFABoot 提供的 ClientFactory 来实现运行时指定具体的 uniqueId 对应的服务进行调用

**Comment by Charles19961002** [comment]
> @Charles19961002 可以把 uniqueId 作为参数，通过 SOFABoot 提供的 ClientFactory 来实现运行时指定具体的 uniqueId 对应的服务进行调用

老哥稳，我找到方法了

**Comment by Charles19961002** [comment]
后来人可以参考这个文档https://www.sofastack.tech/projects/sofa-rpc/programing-sofa-boot-api/

**Comment by Charles19961002** [comment]
后来人可以参考这个文档https://www.sofastack.tech/projects/sofa-rpc/programing-sofa-boot-api/
具体需要依赖sofaboot才能实现
