### ISSUE TITLE
是否支持通过API方式来安装、替换Ark Biz包

### ISSUE THREAD

**Issue by junjie-tang99** [sofastack/sofa-ark#405]
### Your question
在Sofa-Ark的文档中，看到“[不推荐直接通过 telnet 指令在线上执行 Biz 操作指令，推荐使用 API 或者动态配置方式。](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-telnet/)”，但是也没有找到API方式的相关说明，能否提供下链接地址？

**Comment by vipwhr** [comment]
+1

**Comment by glmapper** [comment]
@junjie-tang99 @vipwhr 通过 api 的方式是指通过 ark 中提供的 ArkClient 客户端进行相应的模块运维操作，用户可以根据自身场景结合 ArkClient 来做相应的运维定制

**Comment by vipwhr** [comment]
> @junjie-tang99 @vipwhr 通过 api 的方式是指通过 ark 中提供的 ArkClient 客户端进行相应的模块运维操作，用户可以根据自身场景结合 ArkClient 来做相应的运维定制

Thanks ☺  @glmapper
