### ISSUE TITLE
sofa-ark-all是否可以有去掉spring和netty相关依赖lite版本

### ISSUE THREAD

**Issue by jenrryyou** [sofastack/sofa-ark#411]
sofa-ark-all.jar包大小12.4MB，对于我们的场景还说还说太大了，而且telent server和spring的特性完全用不到。是否考虑做一个更轻量的container包，把spring和netty相关依赖去掉？

**Comment by glmapper** [comment]
@jenrryyou sofa-ark-all  talent server 是作为可选能力是否开启，目前不会基于现有的条件再去维护一个分支已支持“更轻量的container包”
