### ISSUE TITLE
多biz项目如何在IDEA中启动

### ISSUE THREAD

**Issue by liaoyz89** [sofastack/sofa-ark#412]
### Your question
https://github.com/jeckyee/sofaark-demo ,该工程通过stock-mng模块访问打成ark-biz包的provider，mvn install生成dynamic-stock-mng-1.0.0-ark-executable.jar后，可以通过执行命令行java -jar dynamic-stock-mng-1.0.0-ark-executable.jar启动，并在页面上访问 http://localhost:8080/jar/provider1并获得返回。
但在IDEA中，该如何拉起该服务呢？暂时没找到多biz在IDEA启动的指引，还请指教。
describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):WINDOWS 10
- Maven version:
- IDE version:IDEA 2020.1

**Comment by kun1988** [comment]
> ### Your question
> https://github.com/jeckyee/sofaark-demo ,该工程通过stock-mng模块访问打成ark-biz包的provider，mvn install生成dynamic-stock-mng-1.0.0-ark-executable.jar后，可以通过执行命令行java -jar dynamic-stock-mng-1.0.0-ark-executable.jar启动，并在页面上访问 [http://localhost:8080/jar/provider1并获得返回。](http://localhost:8080/jar/provider1%E5%B9%B6%E8%8E%B7%E5%BE%97%E8%BF%94%E5%9B%9E%E3%80%82)
> 但在IDEA中，该如何拉起该服务呢？暂时没找到多biz在IDEA启动的指引，还请指教。
> describe your question clearly
> 
> ### Your scenes
> describe your use scenes (why need this feature)
> 
> ### Your advice
> describe the advice or solution you'd like
> 
> ### Environment
> * SOFAArk version:
> * JVM version (e.g. `java -version`):1.8
> * OS version (e.g. `uname -a`):WINDOWS 10
> * Maven version:
> * IDE version:IDEA 2020.1

请问你是怎么解决的呢？我在IDEA里面运行插件不会执行PluginActivator，但是命令行启动可以，文档完全没有说IDEA里面怎么运行
