### ISSUE TITLE
Whether sofa-ark-springboot-starter will support spring boot 1.x version in the future

### ISSUE THREAD

**Issue by JR--Chen** [sofastack/sofa-ark#417]
0.6.0 后的自动配置项依赖了Spring boot 2.x的API，spring boot 1.x在添加该stater后无法正确运行。

**Comment by glmapper** [comment]
> 0.6.0 后的自动配置项依赖了Spring boot 2.x的API，spring boot 1.x在添加该stater后无法正确运行。

spring boot 官方已经不再维护 1.x 版本了，建议迁移至 2.x 版本

**Comment by qixiaobo** [comment]
same here
