### ISSUE TITLE
sofa-ark是否必须基于sofaboot才能正常运行

### ISSUE THREAD

**Issue by junjie-tang99** [sofastack/sofa-ark#418]
最近尝试将基于maven的普通Java项目（非spring项目）打包为ark-biz，然后动态加载到executable-ark.jar中。但是实际操作后，发现无法进行动态加载。参考了官方的示例（https://github.com/sofastack-guides/sofa-ark-dynamic-guides ），发现ark-biz项目和ark项目都是sofaboot项目。
所以，想确认下sofa-ark是否必须基于sofaboot才能正常运行。

**Comment by glmapper** [comment]
> ark

@junjie-tang99 如果你的 ark biz 只是纯业务逻辑，可以不基于 SOFABoot；但是宿主应用目前还是需要基于 SOFABoot 的
