### ISSUE TITLE
Unloading modules using the combined deployment feature of sofa-ark does not release related connections such as redis, rpc, etc.

### ISSUE THREAD

**Issue by grindwheel** [sofastack/sofa-ark#419]
现象是，多次部署加载与卸载模块时（该模块会创建redis连接，rpc连接），通过netstat发现，连接并未释放，每动态部署模块时，就会添加一个连接

**Comment by glmapper** [comment]
> @glmapper 有结果吗

类似问题我们遇到过，目前提供一种可行的方案是通过监听模块卸载事件或者 spring 上下文关闭事件来动态释放 socket 和 定时任务以及类似的例如缓存、线程池等

**Comment by lylingzhen** [comment]
cc @yuanyuancin 关注。

**Comment by lvjing2** [comment]
> 

建议按照 @glmapper 提供方式，如果还有问题可以重新打开 issue
