### ISSUE TITLE
sofa-ark-plugin-maven-plugin 版本1.1.5及以下插件对多个jar包shade时，无法合并多个jar中的META-INF文件夹下的文件

### ISSUE THREAD

**Issue by ivesmojito** [sofastack/sofa-ark#425]
### Describe the bug

本人使用sofa-ark-plugin-maven-plugin 插件打包时，指定了阿里云注册中心配置中心两个包；
                             
                           
                            <classifier>ark-plugin</classifier>

                            <shades>
                                <shade>com.alibaba.cloud:spring-cloud-alibaba-nacos-discovery:2.1.1.RELEASE</shade>
                                <shade>com.alibaba.cloud:spring-cloud-alibaba-nacos-config:2.1.1.RELEASE</shade>
                            </shades>
打出的ark.plugin插件中，只有其中一个jar 下的META-INF文件，并没有将两个jar 包下的META-INF文件合并；
代码是可以合并的 ^_^

- SOFAArk version: 1.1.5

**Comment by glmapper** [comment]
@ivesmojito 自定义 plugin 只需要把两个包正常引入进去就好

**Comment by lylingzhen** [comment]
超过 3 个月未有回复，先关闭，若仍有问题可以 Reopen 或者创建一个新 Issue 跟进。
