### ISSUE TITLE
关于ark biz包动态的时候针对集群的话，在终端发布新版本的话集群每个节点的版本都会被更新吗?

### ISSUE THREAD

**Issue by caozhenhuamail** [sofastack/sofa-ark#437]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@caozhenhuamail 取决于具体实现方案，比如基于 zk 场景，如果所有客户端都直接 watch 了资源节点，当资源节点有新的 biz 数据时，所有客户端都会 watch 到变更，并开始执行相关的运维逻辑
