### ISSUE TITLE
基于kc-sofastack-dynamic-demo工程Ark Biz包服务通讯问题

### ISSUE THREAD

**Issue by lduffy69** [sofastack/sofa-ark#439]
### 问题
我这边基于`https://github.com/sofastack-guides/kc-sofastack-dynamic-demo`，想验证不同非宿主应用Ark Biz包的服务通讯【JVM服务】，demo的默认实现为Ark Master Biz引用Ark Biz包。但是存在@SofaReference引用的Biz包无法正常install,并且没有相关日志。

###  操作步骤
我在上述工程基础下做如下改造：
* 改造dynamic-facade接口模块，增加UserService；
* 增加dynamic-provider-another模块，实现UserService接口
* dynamic-provider模块通过@SofaReference引用UserService【同dynamic-stock-mng引用StragetyService方式】
* 编译打包出相关ark-biz相关包
* 启动核心包,telnet localhost 1234 && biz -a 正常
* biz -i file://xxxxx/dynamic-provider-another-1.0.0-ark-biz.jar && biz -a 正常
* biz -i file://xxxxx/dynamic-provider-1.0.0-ark-biz.jar && biz -a 缺失dynamic-provider

### 环境
- SOFAArk version:3.1.4
- JVM version 8

**Comment by lduffy69** [comment]
改造后工程：https://github.com/lduffy69/kc-sofastack-dynamic-demo

**Comment by glmapper** [comment]
@lduffy69 pls add skip JVM health check config in your master biz properties 
```
com.alipay.sofa.boot.skip-jvm-reference-health-check=true
```
