### ISSUE TITLE
sofa-ark can support multiple web applications?

### ISSUE THREAD

**Issue by Msimplehub** [sofastack/sofa-ark#444]
### Your question

sofa-ark can support multiple web applications.

### Your scenes

1、 have two web application
2、I want Merge and deploy together
3、when start them, throw Exception: java.lang.ClassNotFoundException: org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader
4、Deploy separately, no problem

### Your advice

Is sofa-ark does not support the deployment of multiple web applications？
### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@Msimplehub Relying on the web-ark-plugin, we implemented multiple fatjars sharing Embded Tomcat, so we can support multiple webs
