### ISSUE TITLE
IDEA调试多Biz运行时报错

### ISSUE THREAD

**Issue by lizhi12q** [sofastack/sofa-ark#446]
例子地址  https://github.com/caojie09/sofachannel-demo.git
按照帮助文档打成ark包，然后java -jar dynamic-stock-mng-1.0.0-ark-executable.jar，访问localhost:8080是显示成功的
但是用IDEA调试运行dynamic-stock-mng模块中的StockMngApplication的main函数，访问localhost:8080会显示
JVM Reference[interface io.sofastack.dynamic.facade.StrategyService#] can not find the corresponding JVM service. Please check if there is a SOFA deployment publish the corresponding JVM service. If this exception occurred when the application starts up, please add Require-Module to SOFA deployment's MANIFEST.MF to indicate the startup dependency of SOFA modules.

**Comment by glmapper** [comment]
@lizhi12q 

```
JVM Reference[interface io.sofastack.dynamic.facade.StrategyService#] can not find the corresponding JVM service. Please check if there is a SOFA deployment publish the corresponding JVM service. If this exception occurred when the application starts up, please add Require-Module to SOFA deployment's MANIFEST.MF to indicate the startup dependency of SOFA modules.
```

这段报错原因可能是你在访问时模块应用还未安装，所以基座在引用模块 JVM 服务时找不到。你可以尝试启动完成之后，先安装模块再访问
