### ISSUE TITLE
咨询下怎么在IDE当中使用 ark-plugin

### ISSUE THREAD

**Issue by q6413260** [sofastack/sofa-ark#450]
我直接mvn package 打包服务，线上打印出 不同plugin加载的classloader，是没有问题的。我按照https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-demo/ 上面操作，发现在IDE当中，打印出
的classsloader一直都是 bizclassloader

![image](https://user-images.githubusercontent.com/11553677/122387548-8ef46e00-cfa1-11eb-99f2-e12372af9ce3.png)

- SOFAArk version:
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`): Darwin MacBook-Pro-3.local 19.6.0 Darwin Kernel Version 19.6.0:
- Maven version: Apache Maven 3.5.0
- IDE version:2017.1

**Comment by q6413260** [comment]
RestHighLevelClient5Service对应的module pom配置
![image](https://user-images.githubusercontent.com/11553677/122387996-07f3c580-cfa2-11eb-9f45-0e660558f8c9.png)

RestHighLevelClient7Service对应的module pom配置
![image](https://user-images.githubusercontent.com/11553677/122388030-104c0080-cfa2-11eb-93e5-8a8cdbe61f87.png)


public static void main(String[] args) throws Exception {
        SofaArkBootstrap.launch(args);
        RestHighLevelClient7Service restHighLevelClient7Service = new RestHighLevelClient7Service();
        RestHighLevelClient5Service restHighLevelClient5Service = new RestHighLevelClient5Service();
        log.info(restHighLevelClient7Service.getClass().getClassLoader().toString());
        log.info(restHighLevelClient5Service.getClass().getClassLoader().toString());
    }
上述main方法对应的pom 配置
![image](https://user-images.githubusercontent.com/11553677/122388350-6325b800-cfa2-11eb-8efb-40c0a587ada9.png)
![image](https://user-images.githubusercontent.com/11553677/122388379-68830280-cfa2-11eb-830b-14e8e8a6c187.png)

**Comment by glmapper** [comment]
@q6413260 RestHighLevelClient5Service 所在的 module 是 plugin 吗？在你贴的代码片段中，没有发现任何到处 RestHighLevelClient5Service  的逻辑。详细可以参考下这个文档：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-plugin/
