### ISSUE TITLE
是否支持新增模块呢 

### ISSUE THREAD

**Issue by zp994188707** [sofastack/sofa-ark#452]
比如宿主应用启动之后，线下开发新的模块，可以动态装载吗？ 
也就是说宿主应用没有引入新模块的依赖？

**Comment by glmapper** [comment]
@zp994188707 新开发的模块完全可以动态装载，对于 ark 来说，业务以 biz 形式交付，其本身是闭合（包括业务逻辑、依赖等）；当涉及到新增模块与宿主交互时，由于模块和宿主都是不同的 classloader 加载的，所以在类加载层面，两个 biz 中的类都是相互不可见的，这种调用类似两个独立进程之间的调用，需要走序列化。
