### ISSUE TITLE
Sofa-ARK的plugins包shades有什么作用，和lib下的包有啥区别吗

### ISSUE THREAD

**Issue by RobertoHuang** [sofastack/sofa-ark#456]
### Your question

想咨询一下Sofa-ARK的plugins包shades有什么作用，和lib下的包有啥区别吗

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version: 0.6.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@RobertoHuang https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-plugin/ 可以看下文档中的介绍

**Comment by RobertoHuang** [comment]
这个文档我是看过的

没说明shades到plugins的jar和打在lib目录下的jar有什么区别

**Comment by glmapper** [comment]
> 这个文档我是看过的
> 
> 没说明shades到plugins的jar和打在lib目录下的jar有什么区别

![image](https://user-images.githubusercontent.com/35319286/129153174-9ebb7551-9e89-46d0-87e2-4de9b428dd84.png)

this is a demo with shades configuration，you can get the diff of this two types.

**Comment by RobertoHuang** [comment]
我有动手实践过shade 并且看了源码 发现被shade的jar是不会出现lib中

并且被shard的jar会和本项目源代码一样写入同级目录。但是我没搞懂的是 这对后面的类加载隔离有什么影响吗

因为被shades的jar 和 不被shades的(在lib目录下的jar) 都是plugingClassLoader的classPath。好像除了出现的位置不一样外 没什么区别

**Comment by glmapper** [comment]
> shard

和类加载隔离没关系，你应该去看下 maven shade 的作用

**Comment by RobertoHuang** [comment]
shade插件主要是将lib包shade到工程中，并且重命名包这样可以解决冲突

但是sofaark只是单纯的将jar shade进去，没做什么特殊处理。不知道这么做用意是什么呀

**Comment by glmapper** [comment]
> shade插件主要是将lib包shade到工程中，并且重命名包这样可以解决冲突
> 
> 但是sofaark只是单纯的将jar shade进去，没做什么特殊处理。不知道这么做用意是什么呀

sofaark 中的 shade 目前没有特殊用法，目前在实际的应用场景中可忽略该配置项
