### ISSUE TITLE
多个web项目模块集成到ark容器的问题

### ISSUE THREAD

**Issue by singpalo** [sofastack/sofa-ark#458]
### Your question
在我调试demo的时候，两个biz都有自己的web层，暴露对外提供服务的Controller层，放到容器之后，共用的master biz模块的端口，用的是各个模块自己的context-path。当我把sofa ark集成到我的项目中的时候，发现每个模块不再共用master biz的端口了，而是使用自己的端口号了。我想问一下，什么情况下会导致这种情况出现。

-SOFABoot version:3.2.2
- SOFAArk version:1.1.0
- JVM version (e.g. `java -version`):1.8

**Comment by seeflood** [comment]
感谢反馈，@alaneuler  @glmapper 帮忙看看哈

**Comment by lvjing2** [comment]
项目里引入下 web-ark-plugin，就能解决这个问题了。
