### ISSUE TITLE
PluginClassLoader 加载公共类问题

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-ark#460]
biz 和 plugin 里面往往需要用到相同的类（例如：mockito），当这些相同类的对象由于某种原因需要交互（赋值、调用参数等），如果 classloader 不同，就会可能发生 `ClassCastException` 或者 `LinkageError`，对于这些类需要有一个机制，delegate 到相同的 classloader 进行加载（可以参考 OSGi 的 delegation 机制）。

**Comment by yuanyuan2021** [comment]
org.mockito.*导出由plugin加载

**Comment by lylingzhen** [comment]
@yuanyuancin 该 Issue 是否可以 Close 了？
