### ISSUE TITLE
sofa-ark-maven-plugin不支持通过profile指定依赖

### ISSUE THREAD

**Issue by bbili** [sofastack/sofa-ark#462]
sofa-ark-maven-plugin repackage没办法通过profile指定需要打入的dependencies或module.
我们现在用的0.6.0, 他会把所有的依赖都打进去, 即使指定了某个profile.

**Comment by seeflood** [comment]
感谢反馈，@alaneuler  @glmapper 帮忙看看哈

**Comment by yuanyuancin** [comment]
sofa-ark-maven-plugin 可以通过 excludes/excludeGroupIds/excludeArtifactIds配置排除部分依赖

**Comment by lylingzhen** [comment]
@bbili 请问还有问题吗？有问题可以随时再讨论。
