### ISSUE TITLE
provide guides to embed ark container mode

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-ark#466]
https://github.com/sofastack/sofa-ark/pull/463 has been merged, we should provide series guides to help users for quick start

**Comment by lylingzhen** [comment]
4 月份：
1、更新 SOFAArk Github 官网首页文档。
2、在 Github 官网中提供 1.0 到 2.0 Step by Step 的 Migration Guide，会拿一些场景举例。
3、给第 2 步中的一些场景创建 Github Demo 工程。

**Comment by lylingzhen** [comment]
@glmapper 如果有需要完善的，欢迎随时更新或指出
