### ISSUE TITLE
BizState must be ACTIVATED, DEACTIVATED or BROKEN 异常问题

### ISSUE THREAD

**Issue by liu280790081** [sofastack/sofa-ark#468]
Demo: [https://github.com/liu280790081/sofachannel-demo.git](https://github.com/liu280790081/sofachannel-demo.git)
Error file: [error.log](https://github.com/sofastack/sofa-ark/files/8140030/error.log)

- SOFABoot version: 3.2.2
- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): windows 10
- Maven version: 3.8.1
- IDE version: 2021.1.2

**Comment by xymak** [comment]
> Demo: https://github.com/liu280790081/sofachannel-demo.git Error file: [error.log](https://github.com/sofastack/sofa-ark/files/8140030/error.log)
> 
> * SOFABoot version: 3.2.2
> * SOFAArk version: 1.1.0
> * JVM version (e.g. `java -version`): 1.8
> * OS version (e.g. `uname -a`): windows 10
> * Maven version: 3.8.1
> * IDE version: 2021.1.2

这个升级 sofa-ark 2.0 可以解决，sofa-ark 2.0 已经合到 master，文档正在整理中

**Comment by lvjing2** [comment]
你是从哪里找到这个用例的呢？我们更新下这个用例，更新到最新的sofaArk  2.0的用例。

**Comment by liu280790081** [comment]
> 你是从哪里找到这个用例的呢？我们更新下这个用例，更新到最新的sofaArk 2.0的用例。

这是原地址 https://www.sofastack.tech/guides/sofastack-demos/
![image](https://user-images.githubusercontent.com/12794525/157615854-e874f933-cb83-43f6-9781-fb27bfc7e87f.png)

**Comment by liu280790081** [comment]
> 你是从哪里找到这个用例的呢？我们更新下这个用例，更新到最新的sofaArk 2.0的用例。

sofa ark 没看到哪里有2.0的版本啊

**Comment by glmapper** [comment]
> > 你是从哪里找到这个用例的呢？我们更新下这个用例，更新到最新的sofaArk 2.0的用例。
> 
> sofa ark 没看到哪里有2.0的版本啊

master 已经是 2.0.0-SNAPSHOT 版本了，@lvjing2 新demo 尽快提供下

**Comment by lvjing2** [comment]
> > 你是从哪里找到这个用例的呢？我们更新下这个用例，更新到最新的sofaArk 2.0的用例。
> 
> sofa ark 没看到哪里有2.0的版本啊

https://github.com/lvjing2/sofachannel-demo/tree/dev
先参考下这个例子，当前正在合并到官方demo里
