### ISSUE TITLE
web-ark-plugin与webflux的冲突如何解决

### ISSUE THREAD

**Issue by liu280790081** [sofastack/sofa-ark#470]
![image](https://user-images.githubusercontent.com/12794525/155272533-2e6193fa-c3a2-4366-b1c4-9c010e321931.png)
web-ark-plugin 我看这个插件中引用了tomcat  和webflux中的有冲突
有没有其他的插件可做替换

现在在做的工程先将多个服务依赖到宿主应用这，但我们的应用大多都是webflux的框架，如何能让宿主应用做的兼容webmvc于webflux

**Comment by lylingzhen** [comment]
与 “Ark 支持 WebFlux” 是重复的问题？

**Comment by lylingzhen** [comment]
这个问题已经由另一个 Issue 跟进，先关闭，如果有问题可以随时重开
