### ISSUE TITLE
conf/ark/bootstrap.yml   logging.path does not take affect

### ISSUE THREAD

**Issue by TankyMoose** [sofastack/sofa-ark#471]
### question

conf/ark/bootstrap.yml  
logging.path does not take affect, but other property (e.g: com.alipay.sofa.ark.master.biz) does.
ark log is still output to ${user.home}/logs

### Environment

- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`): `1.8`
- OS version (e.g. `uname -a`): `centos 7`
- Maven version: `3.6.3`
- IDE version: `idea 2021.3`

**Comment by glmapper** [comment]
@TankyMoose 可以尝试 debug com.alipay.sofa.ark.container.ArkContainer#reInitializeArkLogger 这个方法

**Comment by TankyMoose** [comment]
> reInitializeArkLogger

谢谢回复，我去研究下

**Comment by lylingzhen** [comment]
先关闭该 Issue，如果有问题欢迎随时重开
