### ISSUE TITLE
相同biz 不同 bizVersion 同时在线

### ISSUE THREAD

**Issue by jhon-ye** [sofastack/sofa-ark#472]
相同biz 不同 bizVersion 同时在线， 不同版本的biz 可以同时接收流量
### Your scenes
数据通道集成场景，会涉及到同一个数据供应商变更了API，存在v1，v2场景，此时v1，v2 对应biz 的v1，v2；要求v1，v2 在一段时间内同时在线，并能够处理业务。
### Your advice
看到sofa-ark biz 的加载机制， 不同version的biz 只有有一个处于activated，另外处于钝化状态不处理业务。

**Comment by lvjing2** [comment]
多个版本同时存在，如果要调用特定的版本，可以通过这个方法进行
com.alipay.sofa.ark.api.ArkClient#invocationReplay

**Comment by glmapper** [comment]
@jhon-ye 使用 ArkClient api 方式指定版本调用即可
