### ISSUE TITLE
Ark2.0 全面支持 webflux

### ISSUE THREAD

**Issue by liu280790081** [sofastack/sofa-ark#474]
公司接到一个项目需要将多个web工程打入到一个jar包中，然后看到了sofa感觉很合适，但是公司的web工程都是使用的webflux为框架实现的 ，在sofa中没有看对与webflux有支持，希望能出个demo

**Comment by xymak** [comment]
近期还没有计划支持 webflux

**Comment by lvjing2** [comment]
@liu280790081 可以参考 web-ark-plugin实现一个 webflux的插件

**Comment by lvjing2** [comment]
与 #476 重复
