### ISSUE TITLE
源码解析：Ark2.0 支持 Netty 插件

### ISSUE THREAD

**Issue by liu280790081** [sofastack/sofa-ark#476]
demo地址: [https://github.com/liu280790081/sofachannel-demo.git](https://github.com/liu280790081/sofachannel-demo.git)  
分支 ： master-webflux

- SOFAArk version: 1.1.0
- JVM version (e.g. `java -version`): java 8
- OS version (e.g. `uname -a`): window 10
- Maven version: 3.8.1

**Comment by lvjing2** [comment]
你引入了 web-ark-plugin是吗？这个plugin会才会使用到webContextPath

**Comment by liu280790081** [comment]
> 你引入了 web-ark-plugin是吗？这个plugin会才会使用到webContextPath

问题是web-ark-plugin 使用的是tomcat作为web服务的，webflux是以netty作为web服务，启动会有冲突的。
能不能提供一个基于netty的插件？

**Comment by liu280790081** [comment]
> 你引入了 web-ark-plugin是吗？这个plugin会才会使用到webContextPath

d

**Comment by liu280790081** [comment]
这个啥时候会支持

**Comment by lylingzhen** [comment]
@liu280790081 后面会发起社区开发者 Ark 源码解析活动，届时会同奖励社区 Developer 一同共建该特性。

**Comment by pmupkin** [comment]
@lylingzhen 想请教下，这个该怎么测试呢，我新建了webflux应用，将本地写好的两个模块打包，但是引入的时候一直报错，我尝试使用tomcat的项目，将sofaark在本地打包后引入，也同样一直报错。后来又尝试用官网的动态热部署demo，使用在本地打包的sofa-ark依然会报错，但使用maven从网上下的就没问题。
