### ISSUE TITLE
微服务部署， biz 寻址问题

### ISSUE THREAD

**Issue by jhon-ye** [sofastack/sofa-ark#478]
### Your question

您好 Sofastack团队：

使用sofaboot 微服务部署方式存在（instance A，instance B ）， 多biz部署， 比如biz-A部署在 instance A 上， biz-B 部署在 instanceB 上， biz-A  依赖 biz-B 可以通过什么的方式解决 这样的依赖问题。
首先 sofa-ark 目前 不支持 在同jvm 进程下的依赖，同样biz 跨 jvm 进程怎么处理，有什么好的建议。
非常感谢。

### Your scenes
目前企业内部有数据通道项目，会对接多个数据供应商做数据的整合， 开放给业务部门使用， 不同的供应商使用不同ark-biz 方式，业务上有不同供应商数据依赖的场景。

### Environment

- SOFAArk version: 0.6.0
- JVM version : JDK8
- Deployment ：K8s

**Comment by lvjing2** [comment]
不是很明白你的意思，跨jvm进程调用与普通的微服务rpc远程调用有什么不同呢。
另外对于同jvm进程的，不同之间模块互相调用是可以的。可以参考这里 https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-jvm/

**Comment by lylingzhen** [comment]
cc @jhon-ye

**Comment by lylingzhen** [comment]
@jhon-ye Hello，请问还有问题吗？如果没有其它问题该 Issue 先 Close，后续可以随时 Reopen。
