### ISSUE TITLE
sofa-ark-maven-plugin

### ISSUE THREAD

**Issue by wangxiaotao00** [sofastack/sofa-ark#489]
sofa-ark-maven-plugin没有2.0.0版本？

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by lvjing2** [comment]
有的 https://mvnrepository.com/artifact/com.alipay.sofa/sofa-ark-maven-plugin/2.0.0

**Comment by lylingzhen** [comment]
先关闭 Issue，如果有额外需要可以随时重开。
