### ISSUE TITLE
升级到2.0.0版本，出现ark容器日志路径不生效问题

### ISSUE THREAD

**Issue by 343585776** [sofastack/sofa-ark#491]
### Describe the bug

版本升级至2.0.0后出现ark的日志路径配置不生效问题。

即使设置日志路径地址，启动后仍然会默认设置为`System.getProperty("user.home")`地址

设置方式

1.使用/conf/ark/bootstrap.propetties

```yml
com.alipay.sofa.ark.master.biz=master-container
logging.path=/xxx/logs
```

2.使用JVM参数设置
```bash
-Dsofa.ark.embed.enable=true
-Dcom.alipay.sofa.ark.master.biz=master-container
-Dlogging.path=/xxx/logs
```
上述两种设置方式都无法生效。

### Expected behavior

日志路径生效

### Actual behavior

日志路径设置不生效

### Environment

- SOFAArk version:2.0.0
- JVM version (e.g. `java -version`):1.8.0_152
- OS version (e.g. `uname -a`):mac os 11.6.5 
- Maven version:3.5
- IDE version:2020.3

**Comment by yuanyuancin** [comment]
可以debug查看下日志logger是否正确

**Comment by lylingzhen** [comment]
@343585776 Hello，请问还有问题吗？

**Comment by 343585776** [comment]
@lylingzhen mac环境下问题一直存在，其他环境目前没有测试过

**Comment by lvjing2** [comment]
直接使用 application.properties 来配置日志路径，可以参考这个 [demo](https://github.com/sofastack-guides/sofa-ark-spring-guides/blob/master/src/main/resources/application.properties)

**Comment by 343585776** [comment]
@lvjing2 是的，应用日志是这样配置的。应用日志目录没有发现问题，能正常生成到配置地址。但是本身ark容器产生的日志路径出现问题，无论设置成什么路径，都会默认定位到System.getProperty("user.home")这个变量地址下去
<img width="319" alt="image" src="https://user-images.githubusercontent.com/15976826/170624672-d98fd04d-d083-4752-819b-af5db1885928.png">
是上面这几个内容日志

**Comment by lvjing2** [comment]
那麻烦参考下这个 [demo](https://github.com/sofastack-guides/sofa-ark-dynamic-guides)，这个日志路径是ok的。
![image](https://user-images.githubusercontent.com/3754074/170647147-8b929758-e8c5-4739-aeca-8aca6fa307af.png)
