### ISSUE TITLE
Sofa Service 暴露 jvm rpc 双服务，升级biz 后出现jvm不可访问，  rpc 可访问

### ISSUE THREAD

**Issue by jhon-ye** [sofastack/sofa-ark#493]
## In what area(s)?

ctn-tracking:2.0.0:activated
ctn-tracking:1.0.0:deactivated

Sofa Service 暴露 jvm rpc 双服务，升级biz 后出现jvm不可访问，  rpc 可访问
jvm 不可访问可以理解， ctn-tracking:1.0.0在install 是没有注册到 bizMangerService ，通过 sofa reference client
访问时是通过  bizName 从  bizMangerService 获取相应的biz信息

但sofa-rpc 似乎没有这样，如果保持一致的话应该是 在biz state 为deactivated是也不可访问

同时提一个问题：
在业务场景中，需要同一个biz 不同的版本同时保持在线，阅读biz 安装的源码，判断biz state 是否可置为activated 仅通过 bizName 来判断， 是否考虑加上bizVersion？

> /area runtime 
> /area operator
> /area placement
> /area docs
> /area test-and-release

**Comment by yuanyuancin** [comment]
1. ctn-tracking:1.0.0在install 是没有注册到 bizMangerService？每次安装都会注册到bizMangerService，见com.alipay.sofa.ark.api.ArkClient#installBiz(java.io.File, java.lang.String[])（166行）
2. 升级biz 后出现jvm不可访问，再详细描述下
3. 判断biz state 是否可置为activated 仅通过 bizName 来判断， 是否考虑加上bizVersion，目前的设计是同name下只有一个biz activated

**Comment by jhon-ye** [comment]
> 
就是在一个宿主应用下，我安装了ctn-tracking version: 2.0.0 然后又安装了 ctn-tracking version: 1.0.0 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/58320279/165715466-69b10803-555e-48cf-9bde-50828b8e837f.png">

这是我安装之后biz state

我在 ctn-tracking 同时暴露了jvm 和 rpc serivce 
我调用 ctn-tracking version: 1.0.0 jvm service 访问不了
 访问 ctn-tracking version: 1.0.0 rpc 可以访问

**Comment by jhon-ye** [comment]
> 1. ctn-tracking:1.0.0在install 是没有注册到 bizMangerService？每次安装都会注册到bizMangerService，见com.alipay.sofa.ark.api.ArkClient#installBiz(java.io.File, java.lang.String[])（166行）
> 2. 升级biz 后出现jvm不可访问，再详细描述下
> 3. 判断biz state 是否可置为activated 仅通过 bizName 来判断， 是否考虑加上bizVersion，目前的设计是同name下只有一个biz activated

就是在一个宿主应用下，我安装了ctn-tracking version: 2.0.0 然后又安装了 ctn-tracking version: 1.0.0
image

这是我安装之后biz state

我在 ctn-tracking 同时暴露了jvm 和 rpc serivce
我调用 ctn-tracking version: 1.0.0 jvm service 访问不了
访问 ctn-tracking version: 1.0.0 rpc 可以访问

**Comment by jhon-ye** [comment]
> 1. ctn-tracking:1.0.0在install 是没有注册到 bizMangerService？每次安装都会注册到bizMangerService，见com.alipay.sofa.ark.api.ArkClient#installBiz(java.io.File, java.lang.String[])（166行）
> 2. 升级biz 后出现jvm不可访问，再详细描述下
> 3. 判断biz state 是否可置为activated 仅通过 bizName 来判断， 是否考虑加上bizVersion，目前的设计是同name下只有一个biz activated
