### ISSUE TITLE
源码解析：Class isolation capability based SOFA-Ark 2.0

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-ark#496]
Currently, sofa-ark framework has officially released version 2.0. One of the major changes in version 2.0 is to embed the startup of ark container into the startup process of spring context of master biz. Meanwhile, version 1.0 PluginClassLoader no longer exists, replaced by classloader(it is com.alipay.sofa.ark.springboot.loader.CachedLaunchedURLClassLoader) of master biz.

However, for most open source users, PluginClassLoader is a common way to solve the problem of class conflict, the change in version 2.0 breaks the class isolation capability of PluginClassLoader.

Expectation: 

Class isolation capability based SOFA-Ark 2.0

**Comment by lylingzhen** [comment]
源码解析活动任务。

**Comment by lylingzhen** [comment]
Unassigned this issue.
