### ISSUE TITLE
springboot使用sofaark2.0如何静态合并部署

### ISSUE THREAD

**Issue by DalianRollingKing** [sofastack/sofa-ark#497]
### Your question
当我的springboot应用使用了sofaark后他被作为masterbiz使用，当我通过pom文件依赖其他的biz时，应用启动后并没有加载其他的biz
describe your question clearly
springboot使用sofaark2.0怎样配置能够进行静态合并部署？
### Your scenes
springboot使用ark2.0后，打包使用springboot的打包插件，与1.0不同的是没有biz目录，是否有机制能够在springboot使用sofaark2.0的时候进行静态合并部署。我说的静态合并部署是指其他的biz包通过pom依赖的形式与主应用一起打包，应用启动的时候主biz和其他biz都会默认被ark容器加载

**Comment by DalianRollingKing** [comment]
目前能力是否支持，或者需要单独进行开发？

**Comment by DalianRollingKing** [comment]
![image](https://user-images.githubusercontent.com/42019170/167533992-79a8d025-4aa8-4880-8353-2307d42faaba.png)
![image](https://user-images.githubusercontent.com/42019170/167534009-c8ce9856-5d31-46ca-90aa-40492cae41ef.png)
![image](https://user-images.githubusercontent.com/42019170/167534039-274f5748-1ef6-45d7-9260-041377e23f35.png)这个情况是因为啥呢。我把springboot打包改成了打ark包但是java -jar启动报找不到，ArkLauncher没有使用自定义的类加载器去加载ArkConfigs这个类


这个情况是因为啥呢。我把springboot打包改成了打ark包但是java -jar启动报找不到，ArkLauncher没有使用自定义的类加载器去加载ArkConfigs这个类

**Comment by lvjing2** [comment]
你的启动参数是 `sofa.ark.embed.enable=false` 的吗？设置成false，SOFAArk 2.0的能力就和1.0是一致的
