### ISSUE TITLE
ark升级2.0后插件导出类的类加载和业务类类加载器是同一个，还能保证类隔离吗

### ISSUE THREAD

**Issue by outh0527** [sofastack/sofa-ark#499]
### 问题
升级后ark插件包不再由PluginClassLoader加载
![image](https://user-images.githubusercontent.com/86814310/169013090-8648bffa-e19d-49c8-9e83-d180856006f7.png)
1.1.6版本，ark插件包里面的类由PluginClassLoader加载，biz类由BizClassLoader加载，可以解决jar冲突，做到了类隔离，升级后弱化Ark Plugin层，将Ark Plugin与master biz合并，还能做到类隔离吗

### 场景

类隔离，统一管控中间件和基础包版本

### 环境
- SOFAArk version:2.0.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by hupper0** [comment]
同问这个问题；而且sofa-ark 2.0 biz打包的插件都变了，去除了deny等一些列配置，对于插件的导出的类，在biz包里不能进行过滤了。。。。

**Comment by lvjing2** [comment]
> 

对于 plugin 隔离的，打包插件还是继续使用 `sofa-ark-plugin-maven-plugin`, 可参考[这里](https://github.com/QilongZhang/ark-plugin-demo?spm=a2c6h.12873639.article-detail.6.29373a01L8D0Bo)

**Comment by yuanyuancin** [comment]
> 同问这个问题；而且sofa-ark 2.0 biz打包的插件都变了，去除了deny等一些列配置，对于插件的导出的类，在biz包里不能进行过滤了。。。。

sofa-ark 2.0 只是master biz 改为 spring-boot-maven-plugin 打包，其余非 master biz 仍旧用sofa-ark-maven-plugin打包

**Comment by hupper0** [comment]
> 1.1.6版本，ark插件包里面的类由PluginClassLoader加载，biz类由BizClassLoader加载，可以解决jar冲突，做到了类隔离，升级后弱化Ark Plugin层，将Ark Plugin与master biz合并，还能做到类隔离吗

OK~
