### ISSUE TITLE
源码解析：SOFAArk2.0 批量查找资源时，如果模块有定义会只返回模块内的资源，无法查找基座的资源

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-ark#500]
## 背景
SOFAArk 2.0后，Plugin的作用有了较大改动，可以说目前是直接取消了。JVM内 ClassLoader 布局有些调整，如下图
<div align="center"><img width="194" alt="image" src="https://user-images.githubusercontent.com/3754074/169092580-4092e088-ba97-420e-b7d1-688dfed60bf5.png"></div>
通过降低 plugin 的地位，提高基座 Master biz 的地位，运行时JVM的布局变成了
<div align="center"><img width="194" alt="image" src="https://user-images.githubusercontent.com/3754074/169092647-ba4047b5-cce5-4151-a696-e05ae62c2e81.png"></div>

模块的类查找方式变成了，优先从模块查找，如果查找不到则直接从基座查找（基座里包含了原来plugin的依赖）。

改成这种模式之后，模块启动时部分类时会查找到部分模块里未声明过的依赖，详见 #477 。

#477 修复的核心思路是从模块发起的类查找和资源查找，即使委托到基座查找，也只查找模块依赖里声明过的。

## 问题描述
但是对于资源查找，`com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader#getResources`, 有三个查找分支，分别是 

1. **preFindResources**

通过 `com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook#preFindResources` 从基座里查找，但是默认 ClassLoaderHook 未定义该方法，所以查找不到内容

2. **getResourcesInternal**

从当前ClassLoader里查找，以及基座exported过的资源里查找，如果找到则直接返回。

3. **postFindResources**

通过 `com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook#preFindResources` 从基座里查找，查找基座的资源。

这三个步骤在当模块里委托部分依赖给基座会遇到问题。例如，查找 spring.factories，模块部分包含该资源的依赖委托给基座，同时模块里还有部分其他依赖也包含该资源。按照预期，是希望能从模块和基座里把所有的 spring.factories 都找到。但是通过这三个步骤，当在第二步的时候，会只查找到 模块里的spring.factories，然后就直接返回了，就不会再从基座里去查找了。所以就丢失了部分的spring.factories.

## 解决后的目标
在满足 #477 的类查找原则基础上，对于资源的批量查找，能找到模块里声明过的所有资源，包括委托给基座的部分，以为未委托的部分。

**Comment by lvjing2** [comment]
## 背景
SOFAArk 2.0后，Plugin的作用有了较大改动，可以说目前是直接取消了。JVM内 ClassLoader 布局有些调整，如下图
<div align="center"><img width="194" alt="image" src="https://user-images.githubusercontent.com/3754074/169092580-4092e088-ba97-420e-b7d1-688dfed60bf5.png"></div>
变成了
<div align="center"><img width="194" alt="image" src="https://user-images.githubusercontent.com/3754074/169092647-ba4047b5-cce5-4151-a696-e05ae62c2e81.png"></div>

模块的类查找方式变成了，优先从模块查找，如果查找不到则直接从基座查找（基座里包含了原来plugin的依赖）。

改成这种模式之后，模块启动时部分类时会查找到部分模块里未声明过的依赖，详见 #477 。

#477 修复的核心思路是从模块发起的类查找和资源查找，即使委托到基座查找，也只查找模块依赖里声明过的。

## 问题描述
但是对于资源查找，`com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader#getResources`, 有三个查找分支，分别是 

1. **preFindResources**

通过 `com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook#preFindResources` 从基座里查找，但是默认 ClassLoaderHook 未定义该方法，所以查找不到内容

2. **getResourcesInternal**

从当前ClassLoader里查找，以及基座exported过的资源里查找，如果找到则直接返回。

3. **postFindResources**

通过 `com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook#preFindResources` 从基座里查找，查找基座的资源。

这三个步骤在当模块里委托部分依赖给基座会遇到问题。例如，查找 spring.factories，模块部分包含该资源的依赖委托给基座，同时模块里还有部分其他依赖也包含该资源。按照预期，是希望能从模块和基座里把所有的 spring.factories 都找到。但是通过这三个步骤，当在第二步的时候，会只查找到 模块里的spring.factories，然后就直接返回了，就不会再从基座里去查找了。所以就丢失了部分的spring.factories.

## 解决后的目标
在满足 #477 的类查找原则基础上，对于资源的批量查找，能找到模块里声明过的所有资源，包括委托给基座的部分，以为未委托的部分。
