### ISSUE TITLE
源码解析：SOFAArk2.0 Benchmark 建设

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-ark#501]
先列举一些本地 Benchmark 跑分可以建设的场景。

1、用 10K、1M、10M、100M 等不同大小的模块（或者用不同 class 文件的数量级），在模块反复安装和卸载时，观察应用的 CPU、Mem 等有多少额外开销，可以产出一些数据化报表。

2、使用 非常复杂的 Java 模型 和 简单的 Java 模型 模拟 模块调用基座、模块调用模块 的通信场景，使用不同的 QPS（比如 1、100、10000）压测这些场景，观察应用的 CPU、Mem 等有多少额外开销，可以产出一些数据化报表。

**Comment by lylingzhen** [comment]
期待产出：一份相对完整的性能 Benchmark 报告。cc @lvjing2 可以补充一些设计细节。

**Comment by wangxingyu000** [comment]
> 

欢迎领取 issue，可以微信添加 SOFAGirl180419，备注“Ark 源码解析“，之后方便我们同步进度

**Comment by wangxingyu000** [comment]
> /assign

欢迎领取 issue，可以微信添加 SOFAGirl180419，备注“Ark 源码解析“，之后方便我们同步进度

**Comment by lylingzhen** [comment]
补充：指标还可以从 GC、FullGC 等维度进行统计。

**Comment by lvjing2** [comment]
1. 指定了类委托的模块间通信耗时 Benchmark
2. 未指定类委托的模块间通信耗时 Benchmark
3. CPU 消耗
4. mem 消耗
5. 模块安装耗时 Beachmark
6. 类查找耗时
