### ISSUE TITLE
源码解析：动态部署

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-ark#503]
### 介绍
在master biz运行时可动态运维其余ark biz，支持对ark biz进行查询、安装、卸载、激活。
同时引入了事件模型，在 container、biz、plugin各个不同生命周期发布相应事件，可通过监听事件进行操作处理。
![image](https://github.com/sofastack/sofa-ark/blob/master/resource/life-arch.png?raw=true)
### 参考解析

Ark事件模型：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-event/
Telnet指令：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-telnet/

### 重点源码

```
com.alipay.sofa.ark.api.ArkClient#installOperation(com.alipay.sofa.ark.spi.model.BizOperation)
com.alipay.sofa.ark.api.ArkClient#uninstallOperation
com.alipay.sofa.ark.api.ArkClient#switchOperation
com.alipay.sofa.ark.api.ArkClient#checkOperation

com.alipay.sofa.ark.spi.event.ArkEvent
com.alipay.sofa.ark.spi.service.event.EventAdminService
```

**Comment by azhsmesos** [comment]
please assigned to me

**Comment by wangxingyu000** [comment]
> please assigned to me

hello~ 领取任务后欢迎添加 SOFAGirl 微信:SOFAGirl180419，备注“SOFAArk源码解析”，方便我们之后跟进任务以及发布奖品

**Comment by it-linnan** [comment]
assign to me

_这个任务目前有人认领吗？我想试一下_

**Comment by lylingzhen** [comment]
@azhsmesos 我把 “类委托机制” 源码解析任务 Assign 给你了。这个任务我 Assign 给 @it-linnan 了哈。cc @it-linnan

**Comment by it-linnan** [comment]
pr: [sofastack/sofastack.tech#970](https://github.com/sofastack/sofastack.tech/pull/970)
