### ISSUE TITLE
源码解析：打包插件

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-ark#504]
### 介绍
sofa-ark提供了两个maven plugin
- sofa-ark-maven-plugin 将项目打包成ark biz

- sofa-ark-plugin-maven-plugin 将项目打包成ark plugin，支持plugin的导入导出配置

### 能力
- 打包插件允许配置一些字段，在SOFAArk 运行时提供逻辑。例如模块打包会记录当前模块所有的依赖列表，用于类委托的时候只委托模块声明过的依赖。参考 #477 
- 在这两个打包插件的基础上，系统里设定了一些规约，把符合规约的jar包放在对应的目录，能提供静态合并部署能力。

### 参考解析
ark biz https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-biz/
ark plugin https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-plugin/

### 重点源码
```
- sofa-ark-maven-plugin
com.alipay.sofa.ark.boot.mojo.RepackageMojo
com.alipay.sofa.ark.boot.mojo.ArtifactsLibraries

- sofa-ark-plugin-maven-plugin
com.alipay.sofa.ark.plugin.mojo.ArkPluginMojo
```

**Comment by glmapper** [comment]
https://nv3tmb.yuque.com/docs/share/7ccc8aee-f5a6-40a5-859d-01217c3bb8b8?# 《【已发】蚂蚁金服轻量级类隔离框架 Maven 打包插件解析 | SOFAArk 源码解析》

**Comment by lijunf** [comment]
Assign to me

**Comment by wangxingyu000** [comment]
> Assign to me

hello~ 欢迎领取任务，辛苦添加 SOFAGirl 微信:SOFAGirl180419，备注“SOFAArk源码解析”，方便我们之后跟进任务以及发布奖品

**Comment by lvjing2** [comment]
@lijunf 由于已经有同学提交了解析的文档了，所以这个暂时就先关闭了。感谢对活动的支持。

**Comment by hupper0** [comment]
> https://nv3tmb.yuque.com/docs/share/7ccc8aee-f5a6-40a5-859d-01217c3bb8b8?# 《【已发】蚂蚁金服轻量级类隔离框架 Maven 打包插件解析 | SOFAArk 源码解析》

链接只有蚂蚁内部人才能看吗？好像打不开~~~~！！~~~~~

**Comment by Kelei0215** [comment]
> 

我们在处理啦，有进展会及时同步哈
