### ISSUE TITLE
源码解析：启动过程

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-ark#505]
### 介绍

SOFAArk2.0里应用有三种启动方式：
- java -jar 方式启动

- IDE启动，指定SofaArkBootstrap.launch启动

- 内嵌模式启动

在embed模式下会将arkcontainer的启动内嵌在master biz spring上下文启动过程中，监听SpringApplicationEvent触发ark容器的启动，使得整个应用还是以AppClassLoader启动，对应用侵入较小。
arkcontainer的启动会发布Ark服务、执行pipeline。

### 参考解析
- [非内嵌模式启动过程](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-startup/)
![image](https://user-images.githubusercontent.com/7148759/49442454-86cdec00-f804-11e8-8298-4f6165631298.png)
- 内嵌模式启动过程
![image](https://user-images.githubusercontent.com/16517325/169310815-4dc12cb3-8b95-468e-8aa7-74d7248c12f4.png)
- Ark服务机制 https://www.sofastack.tech/projects/sofa-boot/sofa-ark-ark-service/

### 重点源码

```
com.alipay.sofa.ark.bootstrap.ArkLauncher
com.alipay.sofa.ark.support.startup.SofaArkBootstrap#launch

com.alipay.sofa.ark.springboot.loader.JarLauncher
com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener
com.alipay.sofa.ark.container.ArkContainer#main
com.alipay.sofa.ark.container.pipeline.StandardPipeline#process
```

**Comment by gaosaroma** [comment]
please assign it to me. : )

**Comment by wangxingyu000** [comment]
> please assign it to me. : )

hello~ 领取任务后欢迎添加 SOFAGirl 微信:SOFAGirl180419，备注“SOFAArk源码解析”，方便我们之后跟进任务以及发布奖品

**Comment by wangxingyu000** [comment]
> please assign it to me. : )
hello~ 任务已经在进行中了吗？可以加下 SOFAGirl 微信:SOFAGirl180419，任务完成之后会发布奖品哟～

**Comment by gaosaroma** [comment]
> > please assign it to me. : )
> > hello~ 任务已经在进行中了吗？可以加下 SOFAGirl 微信:SOFAGirl180419，任务完成之后会发布奖品哟～

好的，预计6.20前能提pr~

**Comment by lylingzhen** [comment]
gaosaroma is busy. I transferred this issue to lijunf now.

**Comment by masonqin** [comment]
@wangxingyu000 麻烦问下已经assign的issue其他人可以并行参与吗？感兴趣，想先写一些内容在申请assign

**Comment by wangxingyu000** [comment]
> 

hello，认领同学已经在进行中了，最好不要并行哟  https://github.com/sofastack/sofa-ark/issues/476 这个还没有人认领，感兴趣的话可以看下，还有其他问题可以加下 SOFAGirl 微信:SOFAGirl180419，回复会比较及时哟

**Comment by wangxingyu000** [comment]
> @wangxingyu000 麻烦问下已经assign的issue其他人可以并行参与吗？感兴趣，想先写一些内容在申请assign

hello，认领同学已经在进行中了，最好不要并行哟 https://github.com/sofastack/sofa-ark/issues/476 这个还没有人认领，感兴趣的话可以看下，还有其他问题可以加下 SOFAGirl 微信:SOFAGirl180419，回复会比较及时哟

**Comment by lijunf** [comment]
pr: https://github.com/sofastack/sofastack.tech/pull/965

**Comment by lylingzhen** [comment]
PR was merged, close this issue.
