### ISSUE TITLE
源码解析：类委托加载

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#507]
### 介绍
SOFAArk 通过多ClassLoader的方式提供类隔离的能力，并在此基础上具备热部署的能力。当然类如果纯粹隔离还不够，还需要考虑ClassLoader之间的类共享。

SOFAArk 通过类委托机制，提供了一套丰富的委托加载能力。定义了PluginClassLoader 和 BizClassLoader，不同类型具备不同的类查找逻辑，同时提供ClassLoaderHook能力，允许自定义模块间的类委托加载。

当然除了类查找以外，还有对应的资源查找。SOFAArk 框架本身的类委托加载是非常灵活的，但是在实际落地时，需要有一套类委托加载的最佳实践。

主要分为两个场景：
1. 多Plugin的类隔离
考虑如何相同类不同版本不会相互冲突
2. 热部署
原应用如何拆分，多 ClassLoader 如何布局，在内部我们jvm的多ClassLoader布局从
![image](https://user-images.githubusercontent.com/3754074/169092580-4092e088-ba97-420e-b7d1-688dfed60bf5.png)
演变成了
 ![image](https://user-images.githubusercontent.com/3754074/169092647-ba4047b5-cce5-4151-a696-e05ae62c2e81.png)，优先从模块里查找列，查找不到从基座里查找。

### 参考解析
[委托机制](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-classloader/)
![image](https://gw.alipayobjects.com/zos/skylark/7dfdc66f-a70d-4ef0-9de3-92b72bf2caf7/2018/png/77f10035-a6c3-4bab-bff3-a2c9a986561f.png)

### 重点源码

```
com.alipay.sofa.ark.container.service.classloader.BizClassLoader
com.alipay.sofa.ark.container.service.classloader.PluginClassLoader
com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader
com.alipay.sofa.ark.spi.service.classloader.ClassLoaderHook
```

**Comment by glmapper** [comment]
@lvjing2 this part is very important for sofa ark, i will pick it up to intro

**Comment by azhsmesos** [comment]
please assigned it to me

**Comment by wangxingyu000** [comment]
> please assigned it to me

hello~ 领取任务后欢迎添加 SOFAGirl 微信:SOFAGirl180419，备注“SOFAArk源码解析”，方便我们之后跟进任务以及发布奖品

**Comment by glmapper** [comment]
> please assigned it to me

pls focus on this issue

**Comment by lylingzhen** [comment]
@azhsmesos  Please handle this task. I transferred this task to you. Thanks!

**Comment by it-linnan** [comment]
assign to me

**Comment by lylingzhen** [comment]
@azhsmesos 请问你还在看这个 issue 吗？

**Comment by lylingzhen** [comment]
该文档由 @lvjing2 开发，已放到官网，先 close。
