### ISSUE TITLE
 SOFAArk 源码解析

### ISSUE THREAD

**Issue by wangxingyu000** [sofastack/sofa-ark#510]
### 关于 SOFAArk 源码解析系列

SOFAArk 源码解析活动是由 SOFAStack 团队主办的开源活动，我们希望打造一个人人皆可参与，基于 GitHub 协作的积极透明的开源活动。

本次活动旨在增强大家对 SOFAArk 的了解与认知，促进开源社区的交流，让大家更好的了解、学习和使用开源项目，是大家学习和使用 SOFAArk，与 SOFAArk 的核心开发者直接交流的一个良好契机。

本次活动所产出的文章将首先发表在 SOFAArk 项目主页上，同时也将会进行线上全渠道的推广，经整理后的部分内容会作为 SOFAStack 官方博客中，并会在全渠道进行发布。

***

### 活动角色划分

- 参与者：所有对社区项目感兴趣的开发者。
- Reviewer：项目核心开发者，在源码解析中给予指导和建议。
- 发起人：负责运营协作

***

### 活动流程

活动在 GitHub 上进行协作。流程图如下：

![](https://gw.alipayobjects.com/mdn/rms_1c90e8/afts/img/A*VjR0S5ELOuMAAAAAAAAAAAAAARQnAQ)

- 参与者登陆自己的 GitHub 账号，在源码解析活动的 GitHub 页面回复【/assign】认领 issue。
- Reviewer 指派 issue 给对应的参与者。
- 参与者在认领 issue 成功后在规定时间内提交 PR。
- Reviewer 对提交的 PR 进行 Review。
- PR 审核通过后，由 Reviewer 进行发布在项目主页中。
- 参与者关闭 issue。

***

### 规则说明

1. 每位参与者一次最多只可以认领一个 issue，如错领 issue 等，需先关闭已领 issue 再进行重新认领。一人可认领完成多次。
2. 本次任务难度分为 3 个等级，1-2 星任务为初阶，3 星为中阶，4-5 星为高阶。
3. issue 根据不同难度，相对应的提交期限不同，初阶 issue 认领 7 天内提交，中阶 issue 认领 15 天内提交，高阶 issue 认领 20 天内提交。如过期未提交将视为放弃该 issue，issue 将会重新进行分配认领。
4. 我们发起人每周会和大家了解进度，通过“金融级分布式架构”公众号同步活动的进展情况。

***

### 活动奖励

根据社区晋升规则：

- 完成 1 个初阶任务可晋升为社区 Contributor；

- 完成 1 个初阶 + 1 个中阶可晋升为社区 Members；

- 完成 1 个高阶可晋升为社区 Members；

社区 Contributor 享有的权利：专属的 Contributor 定制证书（电子版和实物都有）、社区周边礼物（T恤、卫衣、马克杯、贴纸、日历等）

社区 Members 享有的权利：专属的 Members 定制证书（电子版和实物都有）、社区周边礼物（T恤、卫衣、马克杯、贴纸、日历等）

完成任意难度的源码解析任务，均可获得自选图书的机会，价值 100 元以内的图书，任你选择，每人仅限一次。

***

### Reviewer 列表

Reviewer 既是审稿人也担任 mentor 的角色，是 SOFAArk  的核心开发者。

- [lvjing2](https://github.com/lvjing2)
- [yuanyuancin](https://github.com/yuanyuancin)

***

### 源码列表📃 

文章标题及对应的 reviewer 和 issue 地址如下：

| 标题                                                         | Reviewer                                  | Issue                                                     | 难度 | 进展   |
| ------------------------------------------------------------ | ----------------------------------------- | --------------------------------------------------------- | ---- | ------ |
| 多Web部署                                                    | [lvjing2](https://github.com/lvjing2) | [#508](https://github.com/sofastack/sofa-ark/issues/508) | 🌟🌟🌟  | 已完成 |
| 动态部署                           | [yuanyuancin](https://github.com/yuanyuancin) | [#503](https://github.com/sofastack/sofa-ark/issues/503) | 🌟🌟🌟  | 已完成 |
| 打包插件                           | [yuanyuancin](https://github.com/yuanyuancin) | [#504](https://github.com/sofastack/sofa-ark/issues/504) | 🌟🌟🌟  | 已完成 |
|启动过程                                 | [yuanyuancin](https://github.com/yuanyuancin) | [#505](https://github.com/sofastack/sofa-ark/issues/505) | 🌟🌟🌟🌟 | 已完成 |
|类委托加载                                 | [lvjing2](https://github.com/lvjing2) | [#507](https://github.com/sofastack/sofa-ark/issues/507) | 🌟🌟🌟🌟🌟 | 待认领 |

请大家跳转到指定的 issue 下回复 /assign 认领文章。

###  Issue 退！🤺 退！🤺 退！🤺 

除了源码解析的文章，也欢迎大家和我们一起来解决一些实际的 issue，共建 SOFAArk！ 💪

如果你对以下任务有好的想法，欢迎在 issue下面留言我们一起来大开脑洞，解决实际问题吧～

| 标题                                                         | Issue                                                     | 难度 | 进展    |
| ------------------------------------------------------------ | --------------------------------------------------------- | ---- | ------ |
| Ark2.0 支持 Netty 插件 | [#476](https://github.com/sofastack/sofa-ark/issues/476) | 🌟🌟🌟🌟 | 待认领 |
| SOFAArk2.0 Benchmark 建设         | [#501](https://github.com/sofastack/sofa-ark/issues/501) | 🌟🌟🌟🌟 | 已提交 |
| SOFAArk2.0 批量查找资源支持查找master biz | [#500](https://github.com/sofastack/sofa-boot/issues/500) | 🌟🌟🌟 | 已完成 |
| SOFA-Ark supports JDK 11          | [#495](https://github.com/sofastack/sofa-ark/issues/495) | 🌟🌟🌟🌟 | 已完成 |
| Class isolation capability based SOFA-Ark 2.0 | [#496](https://github.com/sofastack/sofa-ark/issues/496) | 🌟🌟🌟🌟 | 待认领 |

请大家跳转到指定的 issue 下留言你的想法，来讨论吧～
如果最终解决了问题，将会得到社区学习奖品，和我们一起成长～

### 获取帮助

- 对于本次活动有任何疑问可以在此条 issue 中回复。
- 对于某个独立的 issue 有任何疑问，请到指定的 issue 中回复，我们的 reviewer 会为您答疑解惑。

领取任务后欢迎添加 SOFAGirl 微信:SOFAGirl180419，会跟进任务进度，解答任何疑问。

**Comment by glmapper** [comment]
https://nv3tmb.yuque.com/nv3tmb/okstsp 之前以前完成的文章在这里

**Comment by lylingzhen** [comment]
活动已结束，先关闭 issue。
