### ISSUE TITLE
参考sofa-ark-spring-guides进行动态部署出现异常

### ISSUE THREAD

**Issue by NobiLee** [sofastack/sofa-ark#524]
### Your question

参考 [sofa-ark-spring-guides](https://github.com/sofastack-guides/sofa-ark-spring-guides) 进行动态部署，将版本号从2.0.1-SNAPSHOT切换到2.0.0版本进行demo测试时，按照spring-boot-ark-biz动态模块出现如下异常： No auto configuration classes found in META-INF/spring.factories

`14:20:10.911 INFO org.springframework.boot.SpringApplication - Starting application on NobiLee with PID 25160 (started by NobiLee in D:\github\sofa-ark-dynamic-guides) 14:20:10.913 INFO org.springframework.boot.SpringApplication - No active profile set, falling back to default profiles: default 14:20:10.989 ERROR org.springframework.boot.SpringApplication - Application run failed java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct. at org.springframework.util.Assert.notEmpty(Assert.java:470) at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180) at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123) at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434) at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879) at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320) at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:237) at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96) at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) at io.sofastack.dynamic.provider.ProviderApplication.main(ProviderApplication.java:15) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:277) at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:172) at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:348) at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:333)`

### Your advice

该问题需要怎么解决？2.0.0的版本怎么进行动态部署，参考了官网其他的一些说明都会出现此类问题

### Environment

- SOFAArk version: 2.0.0
- JVM version : 1.8.0_231
- OS version:  win10
- Maven version: 3.6.3
- IDE version: 2022.1CE

**Comment by turing1989** [comment]
How to solve it
