### ISSUE TITLE
sofaboot plugin 在哪里？

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-ark#528]
在 2.0 release node 中，https://github.com/sofastack/sofa-ark/releases/tag/v2.0.0 有提到增加 sofaboot plugin，但是代码中没有看到

**Comment by lvjing2** [comment]
后面删掉了，统一使用 sofaboot里集成的 sofaboot plugin了。
https://github.com/sofastack/sofa-boot/blob/master/sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/src/main/java/com/alipay/sofa/runtime/ark/plugin/SofaRuntimeActivator.java

**Comment by lylingzhen** [comment]
close this issue，有需要再 reopen。
