### ISSUE TITLE
增加缓存导致获取 package 为null，导致NPE

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#535]
### Describe the bug

com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader#definePackageIfNecessary 增加了缓存功能，但是在执行 `java -jar xxx-executable.jar` 时，会遇到类的getPackage 返回null，导致 npe

![image](https://user-images.githubusercontent.com/3754074/176362848-22b8cdc6-d297-40ca-a26a-6e9e7fc37c88.png)

![image](https://user-images.githubusercontent.com/3754074/176362803-f15f2fb7-3cbe-4b3b-b94c-f6a73de39176.png)

### Expected behavior

缓存里如果找不到，则能从这里查找。
![image](https://user-images.githubusercontent.com/3754074/176363671-7fe6bab2-59c8-4779-8bd9-9b51681968d5.png)

### Actual behavior

com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader#definePackageIfNecessary 增加了缓存功能，但是在执行 `java -jar xxx-executable.jar` 时，会先从 ContainerClassLoader 里尝试执行Master Biz 的package define。

但是由于 ContainerClassLoader 里的URL是没有对应的jar，所以是查找不到的，在引入缓存之前是返回null，在引入缓存之后，这里会返回 `Optional.empty()` ，在执行 getPackage 时会直接返回null。

![image](https://user-images.githubusercontent.com/3754074/176363213-d9f35972-5383-43a4-b4d5-035562f99e1e.png)

### Steps to reproduce
1. mvn clean package -DskipTests 执行如下仓库
 https://github.com/sofastack-guides/sofa-ark-class-isolation/issues/4
2. java -jar 执行 `java -jar sofa-ark-class-isolation-0.0.1-SNAPSHOT-ark-executable.jar`

### Environment

- SOFAArk version: 2.0.2
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by yupd** [comment]
这个问题什么时候能解决？我测试多web biz合并部署时候也报这个错误，使用springboot-2.1.0.RELEASE启动正常，较高版本的springboot会报这个错误。
