### ISSUE TITLE
静态合并部署目前是否支持单元测试

### ISSUE THREAD

**Issue by DalianRollingKing** [sofastack/sofa-ark#538]
### Describe the bug

单元测试使用SofaBootRunner
![image](https://user-images.githubusercontent.com/42019170/177720792-bae3f873-a97b-46e8-b3a2-7087af0b01e3.png)

### Expected behavior
在HandelArchiveStage希望有masterbiz
### Actual behavior
而实际上只能获取到依赖的业务插件包
![image](https://user-images.githubusercontent.com/42019170/177721159-02f4dcac-2b48-406e-942f-f9d37b3649de.png)
### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by DalianRollingKing** [comment]
我说一下背景，因为ark的动态部署需要的基础设施较多，所以我想用静态合并部署规避这一缺点，我希望我的springboot应用在使用ark时跟常规springboot没有太大的差异，在使用中发现1.1.6在junit测试中spring会执行两次，于是改成2.0.2版本进行测试，在测试中我没有使用sofaark官方文档中的SofabootRunner进行测试而是直接使用SpringRunner，并在EmbedClassPathArchive中增加静态合并部署的代码，但我不知道是否可行，希望砖家们给出建议

**Comment by DalianRollingKing** [comment]
Index: sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java b/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
--- a/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java	(revision bd46dcd563a1cf48abddb167c25e36cc9be74309)
+++ b/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java	(date 1657191496673)
@@ -189,6 +189,12 @@
                 LOGGER.warn(String.format("The plugin of %s is excluded.", plugin.getPluginName()));
             }
         }
+        List<BizArchive> bizArchives = executableArchive.getBizArchives();
+        for (BizArchive bizArchive : bizArchives) {
+            Biz biz = bizFactoryService.createBiz(bizArchive);
+            bizManagerService.registerBiz(biz);
+        }
+
         return;
     }
 
Index: sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/EmbedClassPathArchive.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/EmbedClassPathArchive.java b/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/EmbedClassPathArchive.java
--- a/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/EmbedClassPathArchive.java	(revision bd46dcd563a1cf48abddb167c25e36cc9be74309)
+++ b/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/EmbedClassPathArchive.java	(date 1657192691416)
@@ -29,6 +29,8 @@
 import java.io.IOException;
 import java.net.URL;
 import java.util.ArrayList;
+import java.util.Enumeration;
+import java.util.LinkedList;
 import java.util.List;
 
 /**
@@ -58,8 +60,30 @@
     }
 
     @Override
-    public List<BizArchive> getBizArchives() {
-        return new ArrayList<>();
+    public List<BizArchive> getBizArchives() throws Exception {
+        //将classpath中的biz包载入
+        List<URL> urlList = filterBizUrl(Constants.ARK_BIZ_MARK_ENTRY);
+        List<BizArchive> bizArchives = new LinkedList<>();
+        for (URL url : urlList) {
+            bizArchives.add(new JarBizArchive(new JarFileArchive(new File(url.getFile()))));
+        }
+        return bizArchives;
+    }
+
+    /**
+     * 过滤出biz包
+     */
+    public List<URL> filterBizUrl(String resource) throws Exception {
+        List<URL> urlList = new ArrayList<>();
+        Enumeration<URL> enumeration = super.urlClassLoader.findResources(resource);
+        while (enumeration.hasMoreElements()) {
+            URL resourceUrl = enumeration.nextElement();
+            String resourceFile = resourceUrl.getFile();
+            String jarFile = resourceFile.substring(0, resourceFile.length() - resource.length()
+                                                       - FILE_IN_JAR.length());
+            urlList.add(new URL(jarFile));
+        }
+        return urlList;
     }
 
     @Override
Index: sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java b/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java
--- a/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java	(revision bd46dcd563a1cf48abddb167c25e36cc9be74309)
+++ b/sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java	(date 1657192731953)
@@ -58,7 +58,7 @@
 
         private final URL[]          urls;
 
-        private final URLClassLoader urlClassLoader;
+        protected final URLClassLoader urlClassLoader;
 
         private File                 arkConfBaseDir;

**Comment by DalianRollingKing** [comment]
[](url
[add_feature_ark2_0_2支持静态合并部署.patch.txt](https://github.com/sofastack/sofa-ark/files/9063102/add_feature_ark2_0_2.patch.txt)
)

**Comment by gaosaroma** [comment]
如果需要使用Ark的能力（如类隔离、动态部署等等），则需要使用@RunWith(ArkBootRunner.class)进行测试，不能使用SpringRunner

**Comment by lylingzhen** [comment]
Hello，请问还有问题吗？
