### ISSUE TITLE
使用telnet biz -u 卸载，在重新安装 biz -i ,就出错误Unable to start web server; nested exception is java.lang.IllegalArgumentException: Child name [/biz] is not unique

### ISSUE THREAD

**Issue by zhanghongbin** [sofastack/sofa-ark#546]
现在有两个biz
base:1.0.0:activated
spring-boot-ark-biz:0.0.1-SNAPSHOT:activated
biz count = 2
卸载后为一个
base:1.0.0:activated
biz count = 1
再重新安装出这个错误
Unable to start web server; nested exception is java.lang.IllegalArgumentException: Child name [/biz] is not unique
卸载没有卸载干净吗？tomcat环境好像还加载着，这个怎么处理？

**Comment by gaosaroma** [comment]
springboot服务没有动态卸载能力，sofaboot服务可以动态卸载。可以用这个demo试试https://github.com/sofastack-guides/sofa-ark-dynamic-guides

**Comment by gaosaroma** [comment]
同 #554
