### ISSUE TITLE
希望类隔离开发模式，打包时biz包可以共享父模块的相同的jar减少整体体积

### ISSUE THREAD

**Issue by hantianxiaoxue** [sofastack/sofa-ark#549]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

**Comment by gaosaroma** [comment]
> 希望类隔离开发模式，打包时biz包可以共享父模块的相同的jar减少整体体积
父模块是指“基座-masterbiz”吗？
内嵌模式下，可以采用目前ark 2.0.3版本，在打包ark-biz时设为<declaredMode>true</declaredMode>，并把依赖包设置成<provided>，会默认委托基座加载类；可以看看https://github.com/sofastack-guides/sofa-ark-spring-guides 和 https://github.com/sofastack-guides/sofa-ark-dynamic-guides 这两个demo；但内嵌模式目前不支持类隔离，见https://github.com/sofastack/sofa-ark/issues/500 中对内嵌与非内嵌模式的描述；
非内嵌模式支持类隔离，但没有父模块的概念；或者麻烦再描述清楚一些

**Comment by lylingzhen** [comment]
@hantianxiaoxue 父模块就是指基座吧，请问还有问题吗？

**Comment by lylingzhen** [comment]
close issue，有问题再 reopen。
