### ISSUE TITLE
在动态部署的ark-biz里实现JVM服务发布能力

### ISSUE THREAD

**Issue by ixufeng** [sofastack/sofa-ark#551]
当我在一个biz模块里增加runtime-sofa-boot-plugin依赖后，重新打包，然后使用 biz -i 部署，无任何报错，通过web访问也没有成功，如果把这个依赖去掉就可以部署成功

```
    <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-plugin</artifactId>
       </dependency>
```

我是希望在热部署的biz模块中去实现 JVM的服务发布能力，请问是不支持这样吗

**Comment by lvjing2** [comment]
支持的，看下demo里的代码？

**Comment by ixufeng** [comment]
@lvjing2  感谢回答，已解决，是打包插件版本的问题导致的。

biz可以是一个非spring的java模块吗？是常识了一下，启动会报错，是不是必须是一个spring容器？
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/17922337/180751328-30fe377e-df3d-4c74-9136-e4a07d880d87.png">

**Comment by lvjing2** [comment]
@ixufeng 不需要的，可以是普通的java main方法就可以。
