### ISSUE TITLE
提示 [ArkBiz Loader] bdhlvdian:3.0.0 : can not load class

### ISSUE THREAD

**Issue by youlvlv** [sofastack/sofa-ark#553]
### Your question

我按照 官方指引打包了 ark包和 ark-plugin 但是在ark调用ark-plugin里面的内容时出现了异常

### Your scenes

java -jar运行时

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version: 1.1.6
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):macos 12.4
- Maven version:
- IDE version:

**Comment by lylingzhen** [comment]
麻烦提供一下具体的报错异常信息

**Comment by lylingzhen** [comment]
@youlvlv

**Comment by lvjing2** [comment]
信息不全，可更新到最新版本。由于该 issue 已经超过一年，当前开始自动关闭，如果问题，请重新打开。
