### ISSUE TITLE
telnet biz -u 卸载 然后在 telnet biz -i 出错为什么

### ISSUE THREAD

**Issue by zhanghongbin** [sofastack/sofa-ark#554]
telnet biz -u 卸载 然后在 telnet biz -i 出错为什么

**Comment by zjulbj** [comment]
要具体看什么报错

**Comment by zhanghongbin** [comment]
> 要具体看什么报错

Unable to start web server; nested exception is java.lang.IllegalArgumentException: Child name [/biz] is not unique
卸载没有卸载干净吗？tomcat环境好像还加载着，这个怎么处理？

**Comment by lvjing2** [comment]
> > 要具体看什么报错
> 
> Unable to start web server; nested exception is java.lang.IllegalArgumentException: Child name [/biz] is not unique 卸载没有卸载干净吗？tomcat环境好像还加载着，这个怎么处理？

哪个demo，Spring 的[demo](https://github.com/sofastack-guides/sofa-ark-spring-guides)里没有动态卸载能力，需要动态卸载能力，需要注册一个卸载的事件handler，可以参考 sofaboot 里的实现。

https://github.com/sofastack/sofa-boot/blob/b3770f2582657ae69667ede74e24d72c17ba16e9/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaBizUninstallEventHandler.java
