### ISSUE TITLE
是否支持jetty容器

### ISSUE THREAD

**Issue by wangxiaotao00** [sofastack/sofa-ark#560]
### 是否支持jetty容器

测试发现web-ark-plugin不支持jetty，更换jetty后webContextPath也不行

### Environment

- SOFAArk version: 2.0.3
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by lvjing2** [comment]
暂还不支持，可自行扩展

**Comment by lylingzhen** [comment]
close this issue
