### ISSUE TITLE
Sofa Ark 各插件之间 支持资源隔离吗?

### ISSUE THREAD

**Issue by NullExceptionNull** [sofastack/sofa-ark#566]
一个宿主下面 部署了很多个ark 插件包, 能做这些 ark 插件包的资源 隔离吗? 比如说 线程资源 CPU 资源 内存资源等等

**Comment by lylingzhen** [comment]
现在还不支持，不过 JDK17 已经推出了协程 CPU 资源隔离技术。我们也欢迎社区同学设计出方案，大家一起来探讨一下并落地成 PR。

**Comment by lylingzhen** [comment]
比如我们可以提供一个线程池统一的 API 让用户使用，在内部实现 CPU 资源隔离。
