### ISSUE TITLE
sofa.ark.embed.enable 含义

### ISSUE THREAD

**Issue by alexBaiJW** [sofastack/sofa-ark#570]
求解释下sofa.ark.embed.enable 的含义

**Comment by gaosaroma** [comment]
即开启 sofa-ark v2.x.x 功能，让 biz 通用能力和通用依赖嵌入到 masterBiz。biz 在开启 declaredMode 后，可以使用下沉到 masterBiz 的通用依赖。同时 sofa-ark v2.x.x 还解决了 sofa-ark v1.x.x plugin管控依赖成本高和启动入口不通用的问题，详见：
[SOFAArk2.0 升级](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-migration-guide/)

**Comment by yuanChina** [comment]
怎么理解通用能力嵌入masterBiz, 是从classloader角度去理解么. 现在有个疑问,从功能层面上如果2.0的plugin和masterBiz已经融合了,那么如果在masterBiz上面有一个通用接口,每个biz都去实现自己的扩展,这种是不是就不能实现静态合并部署,只能通过动态合并部署呢?因为依赖关系不能是双向的. @gaosaroma

**Comment by gaosaroma** [comment]
@yuanChina

**Comment by lvjing2** [comment]
> 怎么理解通用能力嵌入masterBiz, 是从classloader角度去理解么. 现在有个疑问,从功能层面上如果2.0的plugin和masterBiz已经融合了,那么如果在masterBiz上面有一个通用接口,每个biz都去实现自己的扩展,这种是不是就不能实现静态合并部署,只能通过动态合并部署呢?因为依赖关系不能是双向的. @gaosaroma

这个和静态合并部署还是动态合并部署没有关系，其实你写几个例子试下能看到效果。另外由于该 issue 已经半年 inactive了，该 issue 将进行关闭，如有问题可以再次打开。
