### ISSUE TITLE
How to support logback-spring.xml 

### ISSUE THREAD

**Issue by l10178** [sofastack/sofa-ark#573]
### Describe the bug

根据官方sofa-ark-spring-guides和spring-boot-ark-biz两个例子可复现此问题。

使用sofa-ark-spring-guides作为master biz以java -jar -Dsofa.ark.embed.enable=true方式启动，然后telnet install spring-boot-ark-biz，问题表现为spring-boot-ark-biz无日志输出。

实际上是因为我在spring-boot-ark-biz的resources目录下放了一个logback-spring.xml，如果去掉此文件只在application.properties里配置日志相关参数，或者把logback-spring.xml改为logback.xml，日志都能正常工作。

### Environment

- SOFAArk version: 2.0.4
- JVM version : java 11

**Comment by gaosaroma** [comment]
应该是资源加载的问题

**Comment by gaosaroma** [comment]
因为demo中biz使用的LoggerContext是宿主应用的LoggerContext（使用宿主的类加载器加载的），所以会认为已经被初始化过了，从而不会读取logback-spring.xml。一般而言，建议biz模块使用application.properties配置日志参数。

**Comment by l10178** [comment]
希望将这个说明放到文档里。

**Comment by lylingzhen** [comment]
@gaosaroma 把这个放到文档里吧。

**Comment by gaosaroma** [comment]
已加入文档 https://github.com/sofastack/sofastack.tech/pull/1185
