### ISSUE TITLE
sofa ark 2.0 多web静态合并启动报错

### ISSUE THREAD

**Issue by hadoop835** [sofastack/sofa-ark#580]
### Your question

4:03:31.017 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0xc0a03728, L:/0:0:0:0:0:0:0:0:1234] ACTIVE

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)

2022-10-14 14:03:32.229  INFO 12484 --- [           main] com.example.MasterApplication            : Starting MasterApplication v1.0-SNAPSHOT using Java 1.8.0_162 on DEEP-2019RICWZF with PID 12484 (D:\workspace_2022\web-ark-parent\web-ark-master\target\web-ark-master-1.0-SNAPSHOT-ark-executable.jar started by Administrator in D:\workspace_2022\web-ark-parent\web-ark-master\target)
2022-10-14 14:03:32.233  INFO 12484 --- [           main] com.example.MasterApplication            : No active profile set, falling back to 1 default profile: "default"
2022-10-14 14:03:33.575  WARN 12484 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.NoSuchMethodError: org.apache.tomcat.util.modeler.Registry.disableRegistry()V
2022-10-14 14:03:33.586  INFO 12484 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-14 14:03:33.630 ERROR 12484 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:192)

The following method did not exist:

    org.apache.tomcat.util.modeler.Registry.disableRegistry()V

The calling method's class, org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory, was loaded from the following location:

    jar:file:/D:/workspace_2022/web-ark-parent/web-ark-master/target/web-ark-master-1.0-SNAPSHOT-ark-executable.jar!/SOFA-ARK/biz/web-ark-master-1.0-SNAPSHOT-ark-biz.jar!/lib/spring-boot-2.7.3.jar!/org/springframework/boot/web/embedded/tomcat/TomcatServletWebServerFactory.class

The called method's class, org.apache.tomcat.util.modeler.Registry, is available from the following locations:

    jar:file:/D:/workspace_2022/web-ark-parent/web-ark-master/target/web-ark-master-1.0-SNAPSHOT-ark-executable.jar!/SOFA-ARK/biz/web-ark-master-1.0-SNAPSHOT-ark-biz.jar!/lib/tomcat-embed-core-9.0.65.jar!/org/apache/tomcat/util/modeler/Registry.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.tomcat.util.modeler.Registry: jar:file:/D:/workspace_2022/web-ark-parent/web-ark-master/target/web-ark-master-1.0-SNAPSHOT-ark-executable.jar!/SOFA-ARK/plugin/web-ark-plugin-2.0.5.jar!/lib/tomcat-embed-core-9.0.12.jar!/

Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory and org.apache.tomcat.util.modeler.Registry

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version: 2.0.4
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

能提供一个sofa ark2.0 多web静态合并的实例吗,soaf ark1.0.0没有问题正常运行

**Comment by kongqq** [comment]
阁下是如何做合并部署的，是一个master biz ，然后在 ark 容器中 安装 web biz ？

**Comment by hadoop835** [comment]
master biz 
`
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-springboot-starter</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>web-ark-plugin</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-all</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-api</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		**<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>**`
`<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.6.6</version>

				<configuration>
					<outputDirectory>target</outputDirectory>
					<classifier>ark-biz</classifier>
				</configuration>
				<executions>
					<execution>
						<id>package</id>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>`

**Comment by hadoop835** [comment]
master biz 
`
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-springboot-starter</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>web-ark-plugin</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-all</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-api</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		**<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>**`
`<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.6.6</version>

				<configuration>
					<outputDirectory>target</outputDirectory>
					<classifier>ark-biz</classifier>
				</configuration>
				<executions>
					<execution>
						<id>package</id>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>`

**Comment by hadoop835** [comment]
`<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-springboot-starter</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>web-ark-plugin</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-all</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-api</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		**<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>**`
`<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.6.6</version>

				<configuration>
					<outputDirectory>target</outputDirectory>
					<classifier>ark-biz</classifier>
				</configuration>
				<executions>
					<execution>
						<id>package</id>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>`

**Comment by hadoop835** [comment]
1、master biz 的pom依赖
`<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-springboot-starter</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>web-ark-plugin</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-all</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-api</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>`
2、web biz 
`<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>`
3、master bulid
`<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.6.6</version>

				<configuration>
					<outputDirectory>target</outputDirectory>
					<classifier>ark-biz</classifier>
				</configuration>
				<executions>
					<execution>
						<id>package</id>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>`

**Comment by gaosaroma** [comment]
请问是自行编译了目前 sofa ark 的 master 分支吗？现在 2.0.6 版本不支持静态合并部署。

**Comment by hadoop835** [comment]
没有自己编译，
![image](https://user-images.githubusercontent.com/8055054/197140043-8bf881a7-c70a-45a4-9402-530a234fb80d.png)
2.0版本打算支持静态合并部署吗？@gaosaroma

**Comment by gaosaroma** [comment]
2.0.7 支持静态合并部署，还没有release

**Comment by lylingzhen** [comment]
@hadoop835 新版本静态合并部署都支持，可以尝试使用最新 release 版本。
如果有问题可以一起讨论。
