### ISSUE TITLE
合并部署问题集合

### ISSUE THREAD

**Issue by kongqq** [sofastack/sofa-ark#581]
### Your question

在很多地方看到SofaArk支持合并部署，但找不到有关合并部署的demo，您有没有ark合并相关的demo，麻烦提供一下地址。
另外关于合并部署有几个疑问：
1.合并部署是否跟动态安装模式一样，需要一个宿主master服务，其他需要合并的模块都通过 biz -i file 完成？

2. 原有项目使用的Feign调用，合并后，如何改为内存调用？

3. 合并部署后，机器资源是如何节省的？目前来看，宿主服务的内存是不能少的，另外安装的其他服务资源是隔离的，那么原来所需要加载的内容依然还在，只是集中到了一台机器上，并没有节省资源。

4. 使用sofa-jarslink做合并部署，但实际上按说明上操作不下去，是否这部分以后就废弃了，都让sofaark来实现？

5. 要把普通springboot项目合并部署到sofaark容器上，是否只需要在pom中添加ark biz插件，能够打 ark biz 就能够达到合并要求?

6. 普通的 springboot包 pom中添加插件，能够打成ark-biz 包，但安装不进去，biz -i file 后，没有结果，但  在插件中做<skipArkExecutable>false</skipArkExecutable>  设置后，会生成 x-ark-executable.jar，这个包是可以install 进去

### Your scenes

看着文档，跟着代码一步步学习、验证

### Your advice

Windows 11

### Environment

- SOFAArk version: 2.0.0
- JVM version (e.g. `java -version`): 1.8.x
- OS version (e.g. `uname -a`):   Windows 11
- Maven version: 3
- IDE version: IDEA 2022

**Comment by lvjing2** [comment]
READEME 里有demo链接

**Comment by gaosaroma** [comment]
静态合并部署预计在 2.0.7 版本提供。

**Comment by wsh759146139** [comment]
请问是否有2.1.0版本静态合并部署的DEMO呢？我看2.1.0支持了静态合并部署？感谢

**Comment by penglinzhang** [comment]
> READEME 里有demo链接

没有静态合并部署的demo链接

**Comment by lylingzhen** [comment]
@penglinzhang 请参照这个文档：https://github.com/sofastack-guides/sofa-ark-spring-guides

**Comment by lylingzhen** [comment]
产品文档已更新，先 Close，有问题再 Reopen。
