### ISSUE TITLE
集成spring security出错

### ISSUE THREAD

**Issue by lizhi12q** [sofastack/sofa-ark#582]
### Describe the bug

master biz应用集成spring security，在jvm服务上标注了@PreAuthorize进行权限处理，其他biz中的contoller调用了该jvm服务，biz -i安装其他biz后，访问该controller会报An Authentication object was not found in the SecurityContext，调试的时候发现其他biz应用中的Securitycontext为null

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by gaosaroma** [comment]
我有些不太明白，在jvm服务上标注了@PreAuthorize 指的是在服务的实现类上同时标注@Service @SofaService 和 @PreAuthorize？或者提供一个demo呢？

**Comment by lizhi12q** [comment]
> 我有些不太明白，在jvm服务上标注了@ PreAuthorize 指的是在服务的实现类上同时标注@ Service @SofaService 和 @ PreAuthorize？或者提供一个demo呢？

在实现类上标注了@ Service @SofaService，在类的其中一个方法上标注了@ PreAuthorize，目前调试的原因是master biz集成spring security后，记录登录用户安全的securityContext在master biz的上下文中，biz -i安装其他biz后，因为sofaark的类隔离，导致其他biz上下文中securityContext为null，我想知道有没有其他配置可以让master biz和其他的三方biz共用一个securityContext

**Comment by lylingzhen** [comment]
@gaosaroma 可以看一下。

**Comment by gaosaroma** [comment]
> 因为sofaark的类隔离，导致其他biz上下文中securityContext为null
biz session 中 securityContext 为 null 的原因是 biz 和 基座 使用的是不同的 ContextPath，即 biz 和 基座 在 tomcat 的视角中是不同的应用，而 session 管理器是和 context 容器关联的，每个 web 应用都会有一个 session 管理器。
我理解这个问题实际上是：tomcat 中多个 webapp 如何共享 session，这里贴一个博客：https://www.cnblogs.com/morethink/p/7762291.html 希望能帮助到你。
