### ISSUE TITLE
master 服务以pod方式启动，实现动态合并部署。如果pod重启了。怎么保证启动后是合并后的服务

### ISSUE THREAD

**Issue by hadoop835** [sofastack/sofa-ark#584]
master 服务以pod方式启动，实现动态合并部署。如果pod重启了。怎么保证启动后是合并后的服务

**Comment by lvjing2** [comment]
需要有基线来记录这些信息

**Comment by lylingzhen** [comment]
期待社区 contributor 主导，建设一个基于 K8S Operator 的模块运维平台
