### ISSUE TITLE
类隔离运行不出效果。

### ISSUE THREAD

**Issue by jnan806** [sofastack/sofa-ark#585]
### Describe the bug

尝试使用类隔离功能，按照例子使用，没有达到效果。

详细 查看 https://github.com/sofastack-guides/sofa-ark-multi-plugin/issues/5

**Comment by gaosaroma** [comment]
使用ark的版本是？

**Comment by gaosaroma** [comment]
检查一下实际打出来的 `hessian3-ark-plugin` 和 `hessian4-ark-plugin` 里面是否是预期的`print-plugin-v3.0.0` 和 `print-plugin-v4.0.0`，可能是打包的时候就打包错了依赖。

**Comment by jnan806** [comment]
类隔离这个功能是不是不能直接在 idea 里面运行 Applicantion 这个主类，我刚才试了一下，命令行启动 `***-ark-executable.jar` 这个 jar 是可以的

**Comment by jnan806** [comment]
Thanks for your answer ~
