### ISSUE TITLE
关于多web部署源码解析的一些疑问

### ISSUE THREAD

**Issue by springcoco** [sofastack/sofa-ark#589]
最近在看一些项目的源码解析，在多web部署这一章节，发现这样说道：
![image](https://user-images.githubusercontent.com/118293900/201971705-8d687823-1c8b-4c01-b46a-9f9daef2de1d.png)

我的疑惑是spring是如何判断ArkTomcatEmbeddedWebappClassLoader类存在呢？
在加载ArkTomcatServletWebServerFactory的时候，我发现也会加载Tomcat默认的ServerFactory，如何最终判断使用ArkTomcatServletWebServerFactory呢？

**Comment by pmupkin** [comment]
@gaosaroma ArkTomcatEmbeddedWebappClassLoader的作用是什么呢，仅仅是作为一个判断条件吗？我看ArkTomcatEmbeddedWebappClassLoader和TomcatEmbeddedWebappClassLoader代码基本没有区别。是否可以直接删除ArkTomcatEmbeddedWebappClassLoader

**Comment by lylingzhen** [comment]
close this issue
