### ISSUE TITLE
带 Java Agent 启动时报 ClassNotFoundException

### ISSUE THREAD

**Issue by xingcici** [sofastack/sofa-ark#591]
### Your question
应用携带 Java Agent 启动过程中会抛 ClassNotFoundException，如下图。
![image](https://user-images.githubusercontent.com/38656144/204720413-827e8f09-2d15-40aa-87e7-bdb7d6687af1.png)

简单看了下应该是 Ark 在启动过程中用到 Logback 框架，而我们的 Agent 对 Logback 类做了增强。这时候加载类的时候用 ContainerClassLoader，而这个 Loader 没有对 Agent 的情况做兼容，所以会抛异常。
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/38656144/204720908-a3b0bbe6-417b-45e0-bfd5-84979c707d9b.png">
忽略 Fix 部分，是我临时做了兼容。

### Your scenes
我看 Biz 和 Plugin loader 中都做了兼容，想问下为什么 ContainerClassLoader 没对这种情况做兼容，是有其他的考虑吗。

### Your advice
如果没有其他考虑的话能否官方兼容一下呢，谢谢。

### Environment

- SOFAArk version: 2.0.6
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): macos
- Maven version: 3.x
- IDE version:

**Comment by glmapper** [comment]
@xingcici ContainerClassLoader 负责 ark 容器自己的资源加载
