### ISSUE TITLE
关于动态模块卸载机制

### ISSUE THREAD

**Issue by zhaowwwjian** [sofastack/sofa-ark#592]
### Your question
首先我使用了ark-guides 和ark-biz的例子进行操作。
可以正常加载模块并使用。

但删除其他biz时出现问题
关于动态模块卸载机制，我尝试用biz -u xxxx 列表显示已经删除，但实际上业务存在。
是否telnet -u是不建议的操作方式。应采用api的方式？
还是我漏写了相关代码？

如何干净的将其他biz 模块删除并重新安装？是基于事件处理机制还是其他方式？是否我漏写了相关编码？

以上需求基于sofa-ark

- SOFAArk version: 2.0.6
- JVM version (e.g. `java -version`): 1.8.0_281
- OS version (e.g. `uname -a`): mac
- Maven version: 3.5
- IDE version: idea

**Comment by zhaowwwjian** [comment]
![image](https://user-images.githubusercontent.com/24293009/205476787-34f4ddff-7737-4ba6-862b-aac054257068.png)

另外，刚才突显异常，请问导致的原因？

**Comment by glmapper** [comment]
> 关于动态模块卸载机制，我尝试用biz -u xxxx 列表显示已经删除，但实际上业务存在。
你模块中提供的是什么服务？
> 是否telnet -u是不建议的操作方式。应采用api的方式
没有区别，底层逻辑是一样的

**Comment by lylingzhen** [comment]
close this issue, please reopen it if any
