### ISSUE TITLE
关于集成测试的问题

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-ark#593]
采用springboot+spock编写集成测试,再启动spring容器的时候报错
通过ide执行测试用例,在执行到BizMode start时候就结束了,请问哪里有问题呢

![image](https://user-images.githubusercontent.com/17228216/206627298-b961f035-a33f-428b-90f5-430f8ec185ba.png)

**Comment by glmapper** [comment]
@yuanChina 尝试 debug 走一下，看哪里退出了；”启动spring容器的时候报错“ 贴一下异常堆栈

**Comment by yuanChina** [comment]
@glmapper 上面的截图就是debug的,并没有具体报错,不过在biz invoke的时候就结束了,猜测是因为这个mainClass没有找到或者没有main方法,路径就是com.intellij.rt.junit.JUnitStarter

**Comment by yuanChina** [comment]
描述不准确,实际上并没有报错

**Comment by yuanChina** [comment]
![image](https://user-images.githubusercontent.com/17228216/206661069-9f71de41-33d7-4fe4-8acf-78b968a00e59.png)
这个是spock的启动类,新加了main方法

**Comment by yuanChina** [comment]
@glmapper

**Comment by lylingzhen** [comment]
@yuanChina  一行行 debug 一下有什么发现吗？

**Comment by lylingzhen** [comment]
先 close issue，有问题再 reopen。
可以尝试进到最里面代码 debug。
