### ISSUE TITLE
Provide a description about SOFA ark in project's settings panel

### ISSUE THREAD

**Issue by khotyn** [sofastack/sofa-ark#6]
![image](https://user-images.githubusercontent.com/584455/37561975-bdf5265c-2a97-11e8-8d41-b5c6e75d3b64.png)

A few word of description about SOFA ark will help users know what SOFA ark is in the project list page.

![image](https://user-images.githubusercontent.com/584455/37562001-15ed20da-2a98-11e8-863a-da972d6f2187.png)

**Comment by QilongZhang** [comment]
done.
