### ISSUE TITLE
【feat】希望支持各个ark-biz模块读取各自Apollo配置

### ISSUE THREAD

**Issue by zyclove** [sofastack/sofa-ark#601]
### Your question
目前子应用配置对接的Apollo动态配置服务，迁移整合到ark，希望可以打通配置

**Comment by gaosaroma** [comment]
暂时没有这个计划，如果有想法，欢迎提交PR共同建设~

**Comment by lylingzhen** [comment]
@zyclove   hello 可以加入 24970018417 群一起来讨论技术方案，欢迎成为 contributor，我们有小奖励哦~

**Comment by lylingzhen** [comment]
@zyclove 你好，你可参照 sofaark 支持 zookeeper 的原理文档提交一个类似的 mr ，代码不复杂的：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-zk-config/

**Comment by zyclove** [comment]
目前我们已经适配好了，修改代码不多，只是我们代码是公司内部的，而且Apollo也修改了，还没发直接贡献出来，如果有类似需求的可以找我交流。

**Comment by lylingzhen** [comment]
@zyclove 你这边的适配改动代码，能 Contribute 到 SOFAArk 社区里么？
