### ISSUE TITLE
sofa ark 2.0 合并部署时，ark-biz无法读取配置文件

### ISSUE THREAD

**Issue by linkoog** [sofastack/sofa-ark#602]
### Describe the bug
首先我使用了ark-guides 和ark-biz的例子进行操作。
可以正常加载模块,但是配置文件加载不到。

<img width="446" alt="image" src="https://user-images.githubusercontent.com/8047693/210970333-3b6467bf-0783-4cca-8496-ab39809840af.png">

start是启动模块，
config是配置的存放模块。

尝试了下面两种方式，都读取不到配置文件
1、直接打包config的jar中
2、在start模块下存放conf/ark/

### Environment

- SOFAArk version:   2.0.8
- JVM version (e.g. `java -version`): 1.8.333
- OS version (e.g. `uname -a`):   macos
- Maven version:
- IDE version:

**Comment by gaosaroma** [comment]
配置文件的配置应该和 spring boot 应用保持一致，建议把配置文件放置到 resources 目录下

**Comment by lylingzhen** [comment]
@linkoog 请问还有问题吗？

**Comment by lylingzhen** [comment]
close this issue, please reopen if any
