### ISSUE TITLE
基于2.1.0提供一个静态部署的实例吧

### ISSUE THREAD

**Issue by hadoop835** [sofastack/sofa-ark#605]
基于2.1.0提供一个静态部署的实例吧

**Comment by shenchao45** [comment]
同求

**Comment by yupd** [comment]
+1

**Comment by penglinzhang** [comment]
+1

**Comment by gaosaroma** [comment]
与 Spring Boot 结合的示例已更新：https://github.com/sofastack-guides/sofa-ark-spring-guides

**Comment by penglinzhang** [comment]
静态部署的问题，主要是哪里需要修复，我最近被静态部署的问题困扰没有思路

**Comment by zyclove** [comment]
+1 希望给个操作实例

**Comment by gaosaroma** [comment]
> 静态部署的问题，主要是哪里需要修复，我最近被静态部署的问题困扰没有思路

#612

**Comment by lylingzhen** [comment]
关于文档的话，请大家参考：  https://github.com/sofastack-guides/sofa-ark-spring-guides 

关于会重复扫描模块配置的问题，请大家订阅这个 Issue 的状态：https://github.com/sofastack/sofa-ark/issues/612

目前计划 4 月份 Release 版本修复。

该 Issue 先关闭。
