### ISSUE TITLE
DeclaredMode: 模块启动时重复启动基座中的服务

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#617]
Your question
如该 milestone 所描述，declaredMode 还存在如下的不完善地方，需要解决
https://github.com/sofastack/sofa-ark/milestone/21
![image](https://user-images.githubusercontent.com/3754074/222870804-a2d4ec92-0ba0-4cf3-a4c2-d3701df7c382.png)
这里解决其中第一个问题

> 由于基座提前启动，模块再次启动的时候，如果依赖了基座的依赖里有发布服务，那么模块在启动的时候还会再次发布，如果该问题有一定影响可以模块pom里exclude掉对应的依赖。

Describe and Actions
是否所有遇到类似问题模块里的依赖都可以 exclude，如果不能 exclude 是否存在其他更好的方案来解决该问题？

**Comment by lylingzhen** [comment]
@lvjing2 这个可以 Close 吗？
