### ISSUE TITLE
 The following properties were declared as required but could not be resolved: [spring.application.name]

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-ark#618]
The following properties were declared as required but could not be resolved: [spring.application.name]

模块使用了springboot也需要有配置文件么?不是委托加载么 使用了declaredMode=true和provider

@lvjing2

**Comment by lvjing2** [comment]
委托加载只是资源和类的委托加载，复用基座的，但模块本质拥有完全独立的 spring context。
