### ISSUE TITLE
sofa.ark.plugin.export.class.enable

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-ark#619]
sofa2.0弱化了plugin之后,怎么在显示的引入这个概念,master biz已经不用maven-plugin打包了

**Comment by yuanChina** [comment]
看了下源码 是通过runtime-sofa-boot-plugin设置是吧

**Comment by lylingzhen** [comment]
你的具体需求是什么？master 打包插件换成了标准 springboot 打包插件：

https://github.com/sofastack-guides/sofa-ark-spring-guides#3%E4%BF%AE%E6%94%B9%E6%89%93%E5%8C%85%E6%96%B9%E5%BC%8F

**Comment by lylingzhen** [comment]
不再有 ark 自己的打包插件，尽可能和原生 springboot、sofaboot 兼容，极大降低使用成本。

**Comment by zjulbj** [comment]
为了对存量的兼容性升级，保持加载顺序

**Comment by lylingzhen** [comment]
@yuanChina Issue 先 Close，有问题再 Reopen。
