### ISSUE TITLE
宿主应用动态加载业务应用时，业务应用第一次加载完毕不打印日志，需卸载再次加载则正常

### ISSUE THREAD

**Issue by 343585776** [sofastack/sofa-ark#624]
### Describe the bug

宿主应用动态加载业务应用时，业务应用第一次加载完毕不打印日志，需卸载再次加载则正常
业务应用功能能正常访问，只是不创建日志目录与打印日志

### Expected behavior

业务应用第一次加载时就打印日志

### Actual behavior

只打印宿主应用的日志，不打印业务应用日志

### Steps to reproduce

1.创建宿主应用
2.telnet localhost 1234
3.biz -i file://xxxxxx.jar 进行动态加载

### Environment

- SOFAArk version:2.1.2
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):Darwin 20.6.0
- Maven version:3.5.4
- IDE version:IDEA 2020.3

**Comment by lylingzhen** [comment]
宿主应用（基座）和业务应用（模块）的 maven pom 或者代码样例提供一下？

**Comment by 343585776** [comment]
@lylingzhen 
项目使用的是官方的例子
宿主应用:https://github.com/sofastack-guides/sofa-ark-spring-guides
业务应用:https://github.com/sofastack-guides/spring-boot-ark-biz

有区别的地方是，我在宿主应用与业务应用中分别指定了日志的目录

宿主中：
```
logging:
  file:
    path: ./logs/base
```
业务中:
```
logging:
  file:
    path: ./logs/biz
```
我期望的是日志打印在各自的目录中，但是经过我测试发现
第一次通过telnet加载业务模块时，日志仍然是追加在宿主的日志中(`/logs/base/spring.log`)，导致了我以为业务模块日志没有进行打印

当我们使用telnet进行卸载后再次进行加载
那么`/logs/biz`业务日志目录才会创建，并后续日志都写入该路径下的spring.log内了

**Comment by lylingzhen** [comment]
这个 bug cc @lvjing2 关注一下。

**Comment by lvjing2** [comment]
log 的问题请查看官方 samples 样例
https://github.com/sofastack/sofa-serverless/tree/master/samples/springboot-samples/logging
