### ISSUE TITLE
包依赖之间的冲突问题

### ISSUE THREAD

**Issue by DCLe-DA** [sofastack/sofa-ark#630]
### Your question

您好！我在github简介中看到SOFAArk的应用场景类似于同一个jar包的互不兼容的两个版本被不同的模块引用后做了隔离，那请问假如是多个不同jar包之间的冲突（如A和B冲突，B和C冲突，A、B、C为不同功能的jar包），还能否使用SOFAArk进行以来隔离？谢谢。

**Comment by lylingzhen** [comment]
怎么理解 A 和 B 冲突，B 和 C 冲突，能说明具体一些吗？

**Comment by lylingzhen** [comment]
A 、B、C 分别抽象为一个模块，各自的间接依赖就完全隔离了

**Comment by gaosaroma** [comment]
@DCLe-DA hello，请问还有问题嘛？没有问题的话这个issue先关了哈，有问题再reopen～
