### ISSUE TITLE
【月会】23.05.08 SOFAArk 月会（第二次月会）

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-ark#636]
# 本次月会议题

（上次月会暂无 Action）

### 支持 jdk 17

Github Issue：[Support JDK17](https://github.com/sofastack/sofa-ark/pull/639)
Owner：[yuanyuancin](https://github.com/yuanyuancin)

### 依据jarLocation解析BUG修复
Github Issue: [1.依据jarLocation解析BUG修复](https://github.com/sofastack/sofa-ark/pull/648)
Owner: [AiWu4Damon](https://github.com/AiWu4Damon)

### Benchmark 一期建设
Github Issue：#649
Owner：@jijuanwjj

<br/>

### CI 支持 Windows 环境

[<sususama 的 CI 支持 Widnows 环境 Issue>](https://github.com/sofastack/sofa-ark/pull/643)
Github Issue：#643
Owner：@sususama

已完成 | 已取消 | 已答复 ...

### 修复因文件路径不支持跨平台导致的资源加载失败问题

Github Issue：[修复因文件路径不支持跨平台导致的资源加载失败问题](https://github.com/sofastack/sofa-ark/pull/622)
Owner：[HuangDayu](https://github.com/HuangDayu)

已完成 | 已取消 | 已答复 ...

<br/>

### 开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

项目题目：开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们还需要建设一个客户端框架，对接 SOFAArk 实现 Biz 模块的热部署和热卸载，并暴露 HTTP API 接口可以让上游系统或者开发者直接使用。

难度：3/5 颗星

导师：@glmapper

项目产出要求：设计并开发一个新的 SDK（arklet），新的 SDK 也就是 arklet 暴露一组 HTTP 接口，底层调用 SOFAArk 原子能力实现模块的热部署和热卸载。arklet 未来还会有 nodejs 版，这一期先支持 Java 版也就是对接 SOFAArk。

项目技术要求：理解 SOFAArk 源代码，尤其是关于 telnet 指令安装和卸载模块的部分。

#654 

<br/>

### 开发一个 K8S Operator，编排客户端 API 实现 Biz 模块的热部署，初步达成 Serverless 研发体验

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们需要先建设一个简易的 K8S Operator 和 SOFAServerlessModuleDeployment、SOFAServerlessModuleReplicaSet CRD，对接编排模块热装载和热卸载的客户端，实现模块秒级发布的初步能力，让开发者能初步体验到 Serverless 的发布运维能力。

难度：5/5 颗星

导师：@gold300jin

项目产出要求：设计一组 CRD 并实现一个 K8S Operator，Operator 底层调用热安装和热卸载的客户端 arklet，让用户能够通过 kubectl 操纵 SOFAModuleDeployment 从而实现 SOFA 模块的热部署和热卸载运维能力。

项目技术要求：理解 SOFAArk 模块安装和卸载部分的源代码，并且熟悉 K8S CRD 和 Operator 体系的设计与开发。

<br/>

### SOFAServerless 开源项目工程结构

![image](https://user-images.githubusercontent.com/101314559/235049892-22819bd0-5c3c-4adf-af63-07255a28b44d.png)

所有组件收敛到 SOFAServerless 父工程。其中：

- arklet：是开源之夏课题 1 的子工程，是一个 Java 客户端，和 SOFAArk 一起加载到用户的 JVM 进程中，编排 SOFAArk 的内部方法，对外暴露统一标准的 HTTP 接口，实现模块的热部署和热卸载。
- nodejslet：未来的 arklet nodejs 语言实现，对外暴露和 arklet 一样的 HTTP 接口，实现 NodeJS 模块的热部署和热卸载，先预留占位，未来视情况再定。
- module-deployment：SOFAServerlessModuleDeployment、SOFAServerlessModuleReplicaSet 等 K8S CRD 和 Operators 实现，与 arklet、nodejslet（未来）等客户端交互，使得用户可以用 kubectl 或者调用 K8S APIServer 实现简单的模块部署和卸载能力。
- sofa-ark：链接到现在的 sofa-ark 项目，作为 sofa-serverless 的子工程。

https://github.com/sofastack/sofa-serverless

<br/>

<br/>

## Code GPT 在 SOFA 工程领域探索
模块化里特有的问题
1. 模块接入低成本改造：新建模块，SOFABoot 改造模块，SOFABoot 拆分 模块
2. 模块的代码开发、服务配置与自动化模块瘦身
3. 类委托加载里特有的问题，需要通过代码扫描规则进行防御，并基于代码扫描规则提供辅助 Code Review 和代码修改能力
4. 根据已有规则，自动化进行 SOFA4 升级 SOFABoot
5. 知识库转成问答，减少人工支持量
6. 启动与运行时诊断与自助解决方案

<br/>

# 会议 Action
1、CI 支持 windows 在 2.2.0 版本发布。
2、@jijuanwjj 和 @yuanyuancin 把各自的 Issue 内容补充一下，比如 Benchmark 预计产出的报告。
3、目标：基于 GPT 完成从简单需求到代码到部署的全流程
当前开始：建设基于 ChatGPT + langChain 的基础工具链，欢迎一起共建。
![image](https://user-images.githubusercontent.com/101314559/236839436-f220b26c-973d-4823-8e94-0412a0361f28.png)

<br/>

# 下次月会会邀
主题：SOFAArk 社区会议
时间：6月5日 周一 20:00 - 21:00
入会口令：683 550 26227
电话呼入：+862759771614（中国大陆） +8657128356290（中国大陆）
入会链接：[https://meeting.dingtalk.com/j/hv0CVKasIgs](https://meeting.dingtalk.com/j/hv0CVKasIgs)
主持人：@yuanyuancin

**Comment by jijuanwang** [comment]
Benchmark 一期建设 ： https://github.com/sofastack/sofa-ark/issues/649

**Comment by lylingzhen** [comment]
业界在 AI 辅助软件工程领域已经初步百花齐放，SOFAStack 包括 SOFAArk 在这方面也会保持跟进，希望和社区开发者建设相应的基础设施、工具链并用高质量的样例代码和文档进行训练，应用在 SOFABoot、SOFAArk 工程开发领域，我们在后续月会中会更明确的跟大家分享一下社区相关能力建设思考和规划，希望和大家一起共建相关领域。
