### ISSUE TITLE
【建议】将Telnet指令从ark-container中拆分出去

### ISSUE THREAD

**Issue by FlyAbner** [sofastack/sofa-ark#638]
### 需求细节
将Telnet指令从ark-container中拆分出去，container中仅保留管理指令，管理客户端可设计为一个独立模块，可提供以下几种方式：
① Telnet本地管理
② RPC远程管理（可指定URI或URL），此模块进行下载并执行相关指令。

### 关联的语雀文档

无

### 其它备注
无

**Comment by lylingzhen** [comment]
@FlyAbner 可以重新封装一个客户端（比如叫 Arklet）调用 ArkContainer 的内部方法，社区好多同学都有这个诉求，这个 Arklet 客户端暴露标准的一组 HTTP 接口，比如 installModule、uninstallModule、listModules 等，这个看看你能不能认领一下，大家一起讨论 review 一下。成为 contributor 有 SOFAStack 小奖励~

**Comment by lylingzhen** [comment]
开源之夏活动已有相关课题覆盖。

**Comment by FlyAbner** [comment]
> 开源之夏活动已有相关课题覆盖。

这个已经有人认领了吗？

**Comment by sususama** [comment]
> 

我认领了

**Comment by sususama** [comment]
> > 开源之夏活动已有相关课题覆盖。
> 
> 这个已经有人认领了吗？

我认领了
