### ISSUE TITLE
搭建 SOFAArk Windows 环境 CI

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-ark#640]
### 需求细节

SOFAArk 缺少 Windows 环境的 CI 测试能力，Windows 用户在使用的时候有时会发现不兼容问题，因此需要将 Windows CI 能力集成到 SOFAArk 项目中。

github action 应该是支持 windows CI 的，需要调研：
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#using-a-github-hosted-runner
![image](https://user-images.githubusercontent.com/101314559/230271551-55473497-4d0a-4b43-9b81-be8515731c10.png)

暂时给到 @sususama SOFAArk 项目高权限，配置 windows CI 能力。

### 其它备注
other notes if necessary

**Comment by sususama** [comment]
已经完成了 SOFAArk 的 Windows 环境 CI 的搭建，并且针对 Windows 做出了对应的修改，在 Windows 下进行了官方 demo 的验证，程序无误，该 issue 已经解决，这里就 close 了。
