### ISSUE TITLE
静态合并部署com.alipay.sofa.ark.springboot.listener.ArkDeployStaticBizListener重复执行导致部署失败

### ISSUE THREAD

**Issue by davidzj** [sofastack/sofa-ark#645]
### Describe the bug
com.alipay.sofa.ark.springboot.listener.ArkDeployStaticBizListener 执行两次导致静态合并部署失败，使用动态部署确认可以成功部署

### Expected behavior
com.alipay.sofa.ark.springboot.listener.ArkDeployStaticBizListener 只执行一次

### Actual behavior
com.alipay.sofa.ark.springboot.listener.ArkDeployStaticBizListener 执行了两次

### Steps to reproduce
第一次执行：
<img width="2085" alt="image" src="https://user-images.githubusercontent.com/1204059/232695945-3a3e9223-a2f8-4089-9298-f418bbc8a8dd.png">
<img width="2380" alt="image" src="https://user-images.githubusercontent.com/1204059/232696058-e1002f5d-3755-4498-aad0-4abb87472f59.png">

第二次执行：
<img width="2074" alt="image" src="https://user-images.githubusercontent.com/1204059/232710456-fa193e1c-f6ca-46ba-ae70-5fedfec776b1.png">
<img width="2443" alt="image" src="https://user-images.githubusercontent.com/1204059/232712840-2f8cb744-3e65-4aa9-a76d-80d3b862c3a7.png">

### Environment
- SOFAArk version:  2.1.3
- JVM version (e.g. `java -version`): 1.8.0_321
- OS version (e.g. `uname -a`):  Darwin Kernel Version 22.4.0 arm64
- Maven version: 3.8.4
- IDE version: IntelliJ IDEA 2023.1 (Ultimate Edition) Build #IU-231.8109.175, built on March 28, 2023

**Comment by davidzj** [comment]
补充一点，Master Biz包含Spring Cloud

**Comment by gaosaroma** [comment]
我用结合 spring boot 的静态合并部署的简单demo（https://github.com/sofastack-guides/sofa-ark-spring-guides）貌似没有遇到这个问题；这一段逻辑是这样的：ArkDeployStaticBizListener 类是在 master biz 启动时被加载的，类加载器和 master biz 的类加载保持一致，根据该语句：
```
// Only listen to the event when the master biz is started
        if (this.getClass().getClassLoader() != Thread.currentThread().getContextClassLoader()) {
            return;
        }
```
该 listener 的后续逻辑应当只会在 master biz 启动时触发，用来启动其余的业务biz。由于业务biz是由各自的 BizClassLoader 加载，所以这个语句直接return，不会在业务biz启动时触发该 listener 的后续逻辑。除非在 master biz 启动时 ContextRefreshEvent 被send了不止1次。这可能需要麻烦你再检查一下触发两次后续逻辑的原因了。

**Comment by davidzj** [comment]
> 

把spring cloud加上，比如用spring cloud config从nacos动态记载配置，就会复现了。参考这个文档：https://juejin.cn/post/6844904042292838414，一共是3次，sofa-ark的要保证在第一次不执行，第二次执行，第三次不执行

**Comment by davidzj** [comment]
再补充一点，开启management，一样会执行多次
management.endpoint.health.show-details=always
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*

**Comment by yuanyuancin** [comment]
spring cloud和开启management 时带来的多 application context 问题，可以提个pr修复下～

**Comment by yuanyuancin** [comment]
@davidzj 欢迎加入我们的开发者写作群沟通 钉钉 搜索 SOFAArk 社区开发者协作群 ，群号 24970018417

**Comment by lylingzhen** [comment]
@davidzj 可以提一个修复的 PR 么？

**Comment by lylingzhen** [comment]
放在 Spring 生态治理中统一跟进。

**Comment by lvjing2** [comment]
统一放在这里解决跟进，https://github.com/sofastack/sofa-serverless/issues/213

**Comment by qixiaobo** [comment]
Same problem here
