### ISSUE TITLE
com.alipay.sofa.ark.loader.jar.JarUtils#doGetArtifactIdFromFileName 解析BUG

### ISSUE THREAD

**Issue by AiWu4Damon** [sofastack/sofa-ark#647]
### Describe the bug
sofa-ark版本为2.1.3
当com.alipay.sofa.ark.loader.jar.JarUtils#doGetArtifactIdFromFileName方法
入口参数为/Users/xx/.m2/repository/org/apache/skywalking/apm-toolkit-logback-1.x/8.2.0/apm-toolkit-logback-1.x-8.2.0.jar时解析出的ArtifactId为apm-toolkit-logback，但实际应该为apm-toolkit-logback-1.x

### Expected behavior
预期输出数据正确为apm-toolkit-logback-1.x

### Actual behavior
实际输出apm-toolkit-logback，丢失了最后的数字-1.x

### Steps to reproduce
当入口jar的ArtifactId中有数字时即为复现，解析逻辑比较片面

### Minimal yet complete reproducer code (or GitHub URL to code)
public static void main(String[] args) {
        String artifactId = JarUtils.doGetArtifactIdFromFileName("/Users/xx/.m2/repository/org/apache/skywalking/apm-toolkit-logback-1.x/8.2.0/apm-toolkit-logback-1.x-8.2.0.jar");
        System.out.println(artifactId);
    }

### Environment

- SOFAArk version: 2.1.3
- JVM version (e.g. `java -version`): jdk11
- OS version (e.g. `uname -a`): mac os
- Maven version: 3.8.1
- IDE version: 2021.1.2

**Comment by lvjing2** [comment]
can you submit a pr to fix this bug?

**Comment by AiWu4Damon** [comment]
对于解析ArtifactId我的上面提交的解法不够全部，还是会有不少jar解析失败，报错File must exist

**Comment by AiWu4Damon** [comment]
https://github.com/sofastack/sofa-ark/issues/655 和这个问题类似

**Comment by lvjing2** [comment]
> #655 和这个问题类似

问题不太一样，只是你希望通过配置文件的方式把特殊的jar的artifact配置出来。但这种配置文件的方式是会增加用户的理解和使用成本的，万不得已是不会引入的。
