### ISSUE TITLE
SOFAArk、Arklet 性能压测与 Benchmark 一期产出

### ISSUE THREAD

**Issue by jijuanwang** [sofastack/sofa-ark#649]
### 需求细节

产出单台机器（4c8G），100/3000个bean规模的模块可安全安装个数；评测arklet装卸次数对性能的影响(耗时、成功率、metaspace)；
 

基于2种不同规则模块安装数量压测（100个bean/3000个bean 模块），基本可以得出结论：sofaark安装次数不会应用引起性能的消耗。2种规则压测都是触发了系统的性能瓶颈后停止（metaspace、memory）。
压测过程数据：
100bean 模块数量安装压测：

![image](https://github.com/sofastack/sofa-ark/assets/56915119/ee3f7975-c0f4-4124-9c41-2a31e4f09a95)

![image](https://github.com/sofastack/sofa-ark/assets/56915119/1791eec9-a614-4754-9aad-a19d6f0e3c0c)
![image](https://github.com/sofastack/sofa-ark/assets/56915119/6327146a-9618-4f7d-ac33-7e35fdb70325)

![image](https://github.com/sofastack/sofa-ark/assets/56915119/183d7579-9b15-4843-b96e-2d3b6851a47d)
![image](https://github.com/sofastack/sofa-ark/assets/56915119/d7f2f47d-d402-4cfd-8a80-fc404293333a)

3000bean 模块数量安装压测：
![image](https://github.com/sofastack/sofa-ark/assets/56915119/1adcc312-37af-4a01-ad42-f2165b662460)

![Uploading image.png…]()

**Comment by lylingzhen** [comment]
每种评测产出 3 个量级，比如 100、1000、10000
