### ISSUE TITLE
SOFAArk 支持 windows

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#651]
### 需求细节
当前陆续发现几个关于window使用的问题，#634 #622 需要完整看下是否有未修复的地方

**Comment by sususama** [comment]
@lvjing2 @lylingzhen #622 好像已经修复了，麻烦您review一下吧

**Comment by sususama** [comment]
当前 issue 提出的 Windows 中的问题暂时已经全部解决了，如果还有问题麻烦随时在这个 issue 下回复或者开启新 issue @ 我

**Comment by lylingzhen** [comment]
@sususama 这个 Issue 是否已经完结可以 Close 了？

**Comment by sususama** [comment]
@lylingzhen 当前没有问题，可以暂时 close。

**Comment by sususama** [comment]
> @lylingzhen 当前没有问题，可以暂时 close。

当前提出的相关问题已经解决了。

**Comment by lylingzhen** [comment]
ok，标记 Close，cc @lvjing2
