### ISSUE TITLE
SOFAServerless 开源之夏：开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-ark#654]
项目题目：开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们还需要建设一个客户端框架，对接 SOFAArk 实现 Biz 模块的热部署和热卸载，并暴露 HTTP API 接口可以让上游系统或者开发者直接使用。

难度：3/5 颗星

导师：@glmapper

项目产出要求：设计并开发一个新的 SDK（arklet），新的 SDK 也就是 arklet 暴露一组 HTTP 接口，底层调用 SOFAArk 原子能力实现模块的热部署和热卸载。arklet 未来还会有 nodejs 版，这一期先支持 Java 版也就是对接 SOFAArk。

项目技术要求：理解 SOFAArk 源代码，尤其是关于 telnet 指令安装和卸载模块的部分。

请有兴趣的同学参与此 issue 讨论

**Comment by sususama** [comment]
> cc @sususama 关注一下~

好的
