### ISSUE TITLE
SOFAServerless 开源之夏：开发模块运维调度组件，编排客户端的 API 实现 Biz 模块的热部署，初步达成 Serverless 研发体验

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-ark#657]
### 需求细节

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们需要先建设一个简易的运维调度组件，清晰的定义出统一模型和 API，并且既支持 K8S CR + ETCD (ModuleDeployment/Set) 调和的交互方式又支持标准 HTTP、RPC + DB 的交互方式。底层对接编排模块热装载和热卸载的客户端。最终实现模块秒级发布的初步能力，让开发者能初步体验到 Serverless 的发布运维能力。

难度：5 颗星 / 5 颗星

导师：@gold300jin

项目技术要求：理解 SOFAArk 模块安装和卸载部分的源代码，并且熟悉 Golang、数据库技术、K8S CRD 和 Operator 体系的设计与开发。

**Comment by lvjing2** [comment]
已完成
