### ISSUE TITLE
怎么借助sofa-ark实现非spring项目普通module(jar)的热拔插式管理？

### ISSUE THREAD

**Issue by thirdparty-core** [sofastack/sofa-ark#660]
### Your question
我一个普通的java项目中想要实现某些功能的热部署和卸载，功能按照module开发，单独打包成jar，想要借助sofa-ark实现jar的热拔插式管理，能否提供一个相关的使用方式呢。

### Environment

- SOFAArk version:2.1。0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`): centos8
- Maven version:3.6
- IDE version: idea

**Comment by lvjing2** [comment]
每个模块需要有main方法，有main方法就可以启动。具体怎么走通，需要你研究下了。

**Comment by thirdparty-core** [comment]
感谢您的回复。
您这里说的main方法只是当作一个普通的静态方法使用，而不是又启动一个jvm进程，我这么理解对吗？
因为我的需求是仅仅需要把jar加载到我主程序的jvm中，不需要的时候能够移除。
还有，jar包必须要使用官方maven插件打包吗？普通的jar支持否？

**Comment by yuanyuancin** [comment]
先回答你的几个问题：
1. 是的，main只是作为一个普通静态方法调用，不是另外启动一个vm进程
2. jar包目前只支持使用sofa-ark-maven-plugin打包插件，主要是使用sofa-ark-maven-plugin打包插件所打包出来的jar含有一些热部署必须的属性和布局

再针对你的这个issue诉求有几点建议：
1. 如果你的宿主应用非spring环境，当前sofaark是基于spring环境启动的，你需要首先适配你自己的环境并启动arkcontainer
2. 如果你是宿主应用是spring环境，那么当前sofaark启动模式就可以直接使用
3. 热部署的jar是否是spring环境并不是关键，核心还是在你热部署时候调用的普通jar的main方法启动就可以了
