### ISSUE TITLE
【月会】23.06.05 SOFAArk 月会（第三次月会）

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-ark#661]
# 月会议题

### 支持 jdk 17

Github Issue：[Support JDK17](https://github.com/sofastack/sofa-ark/pull/639)
Owner：[yuanyuancin](https://github.com/yuanyuancin)
to fix: server 模式下获取 classpath

### Benchmark 一期建设
Github Issue：#649
Owner：@jijuanwjj

## 当前未关闭 Issue 进展同步

- 测试类：
    - [集成测试](https://github.com/sofastack/sofa-ark/issues/25 )
- 需求类：
    - [sofa-ark-maven-plugin的gradle插件](https://github.com/sofastack/sofa-ark/issues/73 )
    - [资源模糊匹配](https://github.com/sofastack/sofa-ark/issues/113 )
    - [sofa-ark-maven-plugin 打包 war 包](https://github.com/sofastack/sofa-ark/issues/215 )
    - [资源隔离](https://github.com/sofastack/sofa-ark/issues/566 )
- 咨询类：
    - [多次装卸连接未释放](https://github.com/sofastack/sofa-ark/issues/419 )

### 开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

项目题目：开发一个客户端，支持 Biz 模块的热部署和热卸载，初步实现 Serverless 体验

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们还需要建设一个客户端框架，对接 SOFAArk 实现 Biz 模块的热部署和热卸载，并暴露 HTTP API 接口可以让上游系统或者开发者直接使用。

难度：3/5 颗星

导师：@glmapper

项目产出要求：设计并开发一个新的 SDK（arklet），新的 SDK 也就是 arklet 暴露一组 HTTP 接口，底层调用 SOFAArk 原子能力实现模块的热部署和热卸载。arklet 未来还会有 nodejs 版，这一期先支持 Java 版也就是对接 SOFAArk。

项目技术要求：理解 SOFAArk 源代码，尤其是关于 telnet 指令安装和卸载模块的部分。

初步设计：
![image](https://github.com/sofastack/sofa-ark/assets/16517325/d3b1dc30-714b-4751-a2b0-c62be5778e9c)
![image](https://github.com/sofastack/sofa-ark/assets/16517325/3b64ef02-e279-4563-b17e-cf90a177c088)

#654 

<br/>

### 开发一个 K8S Operator，编排客户端 API 实现 Biz 模块的热部署，初步达成 Serverless 研发体验

项目描述：SOFAArk 从最初的一个类隔离框架，逐步演进为支持合并部署与热部署的 “Serverless” 运行时框架，尤其在去年我们完成了 SOFAArk 1.0 到 2.0 架构的演进。但是为了让开发者真正享受 Serverless 的研发体验，我们需要先建设一个简易的 K8S Operator 和 SOFAServerlessModuleDeployment、SOFAServerlessModuleReplicaSet CRD，对接编排模块热装载和热卸载的客户端，实现模块秒级发布的初步能力，让开发者能初步体验到 Serverless 的发布运维能力。

难度：5/5 颗星

导师：@gold300jin

项目产出要求：设计一组 CRD 并实现一个 K8S Operator，Operator 底层调用热安装和热卸载的客户端 arklet，让用户能够通过 kubectl 操纵 SOFAModuleDeployment 从而实现 SOFA 模块的热部署和热卸载运维能力。

项目技术要求：理解 SOFAArk 模块安装和卸载部分的源代码，并且熟悉 K8S CRD 和 Operator 体系的设计与开发。

<br/>

**Comment by gaosaroma** [comment]
1. arklet 开源之夏活动信息同步：
- 通信交互：
    - 仅支持 http 通用的协议；
    - 提供 rpc 拓展，不需要实现 sofarpc 接入；
- 组织结构：
    - arklet 不需要平迁 telnet；
- 重点：
    - 装卸、激活、资源查看模块及支持批量装卸模块；
    - 提供 command 和 http 接口；
    - 多指令编排&锁机制；
- 时间节点：
    - 一期框架需要 明门 确定时间
2. **当前未关闭 Issue 进展同步**中提到的 issue 来源于大家实践的真实案例，欢迎大家参与解决 issue，共建社区～
