### ISSUE TITLE
请教个代码

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-ark#675]
![image](https://github.com/sofastack/sofa-ark/assets/17228216/cb77b016-b38b-4254-bb5f-1e5c53e98756)
这里l逻辑没看懂 为何重复set

**Comment by gaosaroma** [comment]
emm 看起来是笔误了，无须重复set

**Comment by hustchaya** [comment]
嗯嗯嗯 这个代码最近迭代会删除掉

**Comment by lvjing2** [comment]
已合并 #677
