### ISSUE TITLE
SofaArk如何提高Embed Web容器的可扩展性？

### ISSUE THREAD

**Issue by FlyAbner** [sofastack/sofa-ark#678]
### Your question

在信创大环境下，Tomcat不满足信创要求，如何扩展并替换成其他Web容器？

### Environment

- SOFAArk version: 2.1.3
- JVM version (e.g. `java -version`): 1.8.0_73

**Comment by lvjing2** [comment]
https://github.com/sofastack/sofa-ark/issues?q=is%3Aissue+is%3Aopen+netty

**Comment by lylingzhen** [comment]
SOFAArk 已经支持 Netty ，可以使用 Netty。
