### ISSUE TITLE
启动ark包时模块biz报“Consider defining a bean of type 'xxx.xxx.Xxx' in your configuration.”错误

### ISSUE THREAD

**Issue by zkitcast** [sofastack/sofa-ark#679]
### Your question

我使用https://github.com/sofastack-guides/sofa-ark-spring-guides 这个案例作为基座，再使用我们生产上跑的一个springboot项目作为模块biz。我在模块biz中把报冲突的依赖全都provided掉了。打完ark包启动时，还是有些初始化失败的错误。
![image](https://github.com/sofastack/sofa-ark/assets/10002046/4efa44ee-b9fc-447d-aba4-6e326c0bf842)
上面报错的com.ksyun.de.configure.prop.AuthClient类，在模块biz中会被创建成bean，这个过程在不使用ark时是没问题的，但是现在通过ark包启动时似乎创建bean失败了。这个问题请问可以怎么解决？

除了上面这个错误我还遇到com.alicp.jetcache.anno.support.ConfigMap创建bean失败的错，不过已经解决，需要在基座的启动类上添加以下注解才行
![image](https://github.com/sofastack/sofa-ark/assets/10002046/e24d76ec-b4cd-43fa-9421-d144aca4acdb)
类似这种创建bean的错，在把模块biz作为springboot项目单独启动时是不会出现的，但是用ark包启动就会在初始化过程中各种错，这类问题可以怎么解决呢

### Environment

- SOFAArk version:2.1.3
- JVM version (e.g. java -version):1.8
- OS version (e.g. uname -a):centos 7.5
- Maven version:3.6.3

**Comment by hustchaya** [comment]
你这边是什么情况下需要用到ark包启动呢？生产上是arklet的启动方式是吧

**Comment by zkitcast** [comment]
> 你这边是什么情况下需要用到ark包启动呢？生产上是arklet的启动方式是吧

我是按照官方提供的案例来操作的：https://github.com/sofastack-guides/sofa-ark-spring-guides 。 而且文档里也是这么说的：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-spring-boot-demo/。
我都不知道还有arklet这个启动方式，在文档和博客中没有找到任何描述，大佬能给指导一下么，arklet要如何使用呀

**Comment by zkitcast** [comment]
> 我们这边arklet正在设计开源了，我记错了进度sorry。这个报错的类所在的包有provided 的么？

报错的类com.ksyun.de.configure.prop.AuthClient是我们自己开发的，而基座里没有这个类，所以不能provided

**Comment by gaosaroma** [comment]
创建bean失败的原因是啥呢？贴下报错信息吧～

**Comment by lvjing2** [comment]
这个bean 是怎么初始化的，com.ksyun.de.configure.prop.AuthClient，是通过注解的方式，还是xml的方式，要确保初始化bean的类和配置能被biz启动时创建的 classLoader 加载到，如果给个能复现的例子最好。
