### ISSUE TITLE
关于BizName的疑问

### ISSUE THREAD

**Issue by xwh1108** [sofastack/sofa-ark#680]
在使用ArkClient.installOperation(BizOperation bizOperation)方法时,传入的BizName仅作为Ark包解压缩路径的标识,而context中的BizName则读取MF中的bizName,后续有计划将传入的BizName往下传递吗?

**Comment by xwh1108** [comment]
> 模块启动过程中的 bizName, 应该以MF 里的为准，因为这是模块代码里指定的。arkClient 里传入的 bizName 更多在运维指令里生效，不好往下传递，这两个目前通过链路上的参数控制保持一致。

这两个目前通过链路上的参数控制保持一致? 抱歉 这个有点不是很理解

**Comment by lvjing2** [comment]
通过外部工具，或者运维平台，确保两个参数一致。

**Comment by xwh1108** [comment]
> 通过外部工具，或者运维平台，确保两个参数一致。

感谢回答
