### ISSUE TITLE
Why dose AbstractClasspathClassLoader  need to load Class with Cache?

### ISSUE THREAD

**Issue by smalljunHw** [sofastack/sofa-ark#688]
### Discussed in https://github.com/sofastack/sofa-ark/discussions/687

<div type='discussions-op-text'>

<sup>Originally posted by **smalljunHw** July 29, 2023</sup>
Since ClassLoader will only try to load class on the first time, it seems not neccessary to cache the Class Object.</div>

**Comment by lvjing2** [comment]
已回复
