### ISSUE TITLE
应用之间通信问题

### ISSUE THREAD

**Issue by hionwi** [sofastack/sofa-ark#691]
### Your question

我现在创建了两个应用，使用动态部署的方式将他们加载到宿主应用中。在一个应用引用 JVM 服务时报错。

### Your scenes

报错信息
![image](https://github.com/sofastack/sofa-ark/assets/53936026/eea7836b-e076-4103-a3ae-f3b506272438)
服务发布代码
![image](https://github.com/sofastack/sofa-ark/assets/53936026/401ae89a-6cd0-4810-89fc-b1b2e2cbeb9c)
服务引用代码
![image](https://github.com/sofastack/sofa-ark/assets/53936026/1fe41de6-f8de-4e3d-9a73-4d7669ae9354)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by lvjing2** [comment]
考虑原因是你基座上某些依赖引入的问题，你在官方demo里用例里跑下你的这个case。

**Comment by lvjing2** [comment]
可以查看这里的用例 demo
