### ISSUE TITLE
【Bug】开源组件库中使用Reflection.getCallerClass导致ClassLoader混乱的问题

### ISSUE THREAD

**Issue by FlyAbner** [sofastack/sofa-ark#696]
### Describe the bug

在 Java 中，Reflection API 的 Reflection.getCallerClass() 方法用于获取调用者的类。但是，getCallerClass() 方法的实现依赖于调用栈信息。当存在多个类加载器时，不同类加载器加载的类可能会存在于调用栈中，这可能导致 getCallerClass() 方法返回的类与期望不一致。

### Steps to reproduce

使用log4j2日志库时，获取的LoggerContext一直都是宿主应用的Context，调用栈可见：
Log4J2LoggingSystem#beforeInitialize()
    - getLoggerContext()
    - LogManager.getContext(false)
      - Log4jContextFactory#getContext
        - ClassLoaderContextSelector#getContext()
        - StackLocatorUtil.getCallerClass(fqcn)

### Environment

- SOFAArk version: 2.2.1
- JVM version (e.g. `java -version`): 1.8.0
- OS version (e.g. `uname -a`): win10
- Maven version: 3.6.3
- IDE version: 2021.2.2

**Comment by hustchaya** [comment]
能截图一下详细的不同的classloader导致的问题么？或者你看下java1.9的这个函数Reflection.StackWalker能否满足你的需求

**Comment by FlyAbner** [comment]
> getCallerClass

如`Steps to reproduce`中所述，第三方组件库（log4j组件库等）获取ClassLoader不是通过线程上下文获取的，而是通过它的调用类获取，导致获取到的ClassLoader不是当前BizClassLoader，Debug可以看到完整的调用链。

**Comment by hustchaya** [comment]
因为我这边debug拿到的都是基座的ClassLoader，功能都是Work的，所以想要你给下实际拿到的值和期望拿到的值对照，以及这个对你的模块日志打印造成了什么样的影响？

**Comment by lvjing2** [comment]
> > getCallerClass
> 
> 如`Steps to reproduce`中所述，第三方组件库（log4j组件库等）获取ClassLoader不是通过线程上下文获取的，而是通过它的调用类获取，导致获取到的ClassLoader不是当前BizClassLoader，Debug可以看到完整的调用链。

log4j2 getLoggerContext 的问题通过我们提供的 adapter 可以解决，已经提供对应的 samples 工程
https://github.com/sofastack/sofa-serverless/tree/master/samples/springboot-samples/logging
https://sofaserverless.gitee.io/docs/contribution-guidelines/runtime/logj42/
