### ISSUE TITLE
SOFAArk2.0  + ark plugin 宿主应用+ark插件  插件类隔离不生效

### ISSUE THREAD

**Issue by tofdragon** [sofastack/sofa-ark#700]
### Describe the bug

SOFAArk2.0  + ark plugin 宿主应用+ark插件  插件类隔离不生效

### Expected behavior

插件类隔离生效

### Actual behavior

通过java -jar -Dsofa.ark.embed.enable=true -Dcom.alipay.sofa.ark.master.biz=${bizName} ${bizName}-${bizVersion}-ark-biz.jar启动

telnet查看，插件可以查询出来

![image](https://github.com/sofastack/sofa-ark/assets/7513852/8deb909b-f61e-4985-951e-5bb76fc5bfd1)、

查看具体的插件信息，没有导出类

![image](https://github.com/sofastack/sofa-ark/assets/7513852/1dcad174-cb4e-4efd-9136-6bacab56bee9)

实际的jar包中存在导出

![image](https://github.com/sofastack/sofa-ark/assets/7513852/51049c07-bb90-4b3f-88e3-4b7c285a1b0b)
.

通过spring mvc的控制器请求，发现不是请求插件中的依赖

![image](https://github.com/sofastack/sofa-ark/assets/7513852/622c365c-fc81-4c03-aeae-f1ace0701236)

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win10
- Maven version: 3.6.3
- IDE version: 2023.0.1

**Comment by hustchaya** [comment]
sofaark 2.0 弱化了plugin 的功能，目前plugin是和基座在同一个classloader加载的

**Comment by lylingzhen** [comment]
[hustchaya](https://github.com/hustchaya) 已回复，@tofdragon 再看一下呢？

**Comment by lvjing2** [comment]
欢迎认领

**Comment by zyclove** [comment]
这个问题后面有排期吗？能优先支持一下吗？谢谢 @lvjing2
