### ISSUE TITLE
fix zip slip bug in whole project

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#702]
Thanks for @JLLeitschuh submit this PR #565 ，but this PR is outdated，and we also need to check all the code using the "zip slip" in the whole project, so we need to open a new issues to fix "zip slip" in whole project.

**Comment by fenceSky** [comment]
/**
     * check the path is valid
     * @param actualDirPath actual dir path
     * @param targetPath target path
     */
    private static void checkTargetPath(String actualDirPath,String targetPath){
        if (!actualDirPath.startsWith(targetPath)) {
            throw new ArkRuntimeException("Entry is not in the target dir: " + actualDirPath);
        }
    }

**Comment by lvjing2** [comment]
https://user-images.githubusercontent.com/3754074/279916728-77ff602f-c541-4624-bbe2-a3f697c5af5f.png

由于上述问题解决需要复杂的判断逻辑，影响unzip性能，且该问题在用户打包的 jar 里较少发生，故最终不再合并改 MR。

**Comment by lvjing2** [comment]
https://user-images.githubusercontent.com/3754074/279916728-77ff602f-c541-4624-bbe2-a3f697c5af5f.png

由于上述问题解决需要复杂的判断逻辑，影响unzip性能，且该问题在用户打包的 jar 里较少发生，故最终不再合并改 MR。
