### ISSUE TITLE
【信息安全】sofa-ark打包后源文件中包含git commit信息

### ISSUE THREAD

**Issue by jsc12138446** [sofastack/sofa-ark#715]
![image](https://github.com/sofastack/sofa-ark/assets/144100954/77ac1619-184e-47a3-9eaa-2dd6fb072fa4)

![image](https://github.com/sofastack/sofa-ark/assets/144100954/dfcf18bb-1d3f-44a3-9ec9-f7689f770900)

请问如何配置可以将上述的个人及公司信息隐匿？

**Comment by lylingzhen** [comment]
在 Maven 中，可以使用 Maven Shade 插件来打包隐藏 manifest commit。

首先，在 pom.xml 文件中，添加 Maven Shade 插件的配置：

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.2.4</version>
            <configuration>
                <relocations>
                    <relocation>
                        <pattern>org.apache.commons.compress</pattern>
                        <shadedPattern>your.package.path.shaded.commons.compress</shadedPattern>
                    </relocation>
                </relocations>
                <filters>
                    <filter>
                        <artifact>*:*</artifact>
                        <excludes>
                            <exclude>META-INF/MANIFEST.MF</exclude>
                        </excludes>
                    </filter>
                </filters>
                <transformers>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                        <mainClass>your.package.path.MainClass</mainClass>
                    </transformer>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                </transformers>
            </configuration>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
在上述配置中，将 org.apache.commons.compress 重定向为 your.package.path.shaded.commons.compress。这样可以隐藏原始包路径。

然后，执行 mvn package 命令，即可使用 Maven Shade 插件进行打包。打包后的 JAR 文件将不包含原始的 META-INF/MANIFEST.MF 文件，隐藏了 manifest commit。

注意替换示例配置中的 your.package.path 为实际的包路径，以及 your.package.path.MainClass 为实际的主类路径。

**Comment by jsc12138446** [comment]
打包之后的sofa-ark包里面还是会包含commit信息

**Comment by khotyn** [comment]
@jsc12138446 可以把你的 Maven 的 Pom 的配置发出来看看？
