### ISSUE TITLE
直接执行 mvn clean test 会报错

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-ark#720]
### Steps to reproduce

执行 mvn clean test, 会报如下错误

![image](https://github.com/sofastack/sofa-ark/assets/3754074/0a15225f-983a-4981-b6aa-6a02b99b03ee)

### 原因
模块在 declaredMode，需要根据 artifactId 判断当前依赖是否委托给基座或plugin，在 mvn 执行 clean 之后，target 目录里缺少 pom.properties , 导致无法从本地 target 目录里提取出 artifactId

相关源码地址：com.alipay.sofa.ark.loader.jar.JarUtils#getArtifactIdFromLocalClassPath

![image](https://github.com/sofastack/sofa-ark/assets/3754074/b4270c4b-294c-434c-b05c-0d44be533c8b)

### Environment

- SOFAArk version: 2.2.2
- JVM version (e.g. `java -version`): jdk 8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by sususama** [comment]
这个是因为直接在执行`mvn clean test`的时候没有生成`maven-archiver`这个文件夹，经过我的搜索这个文件夹是maven打包生成的，但是想不到除了跳过测试先进行package之外有什么方法能先生成`maven-archiver`文件夹中的内容

**Comment by lvjing2** [comment]
另一种思路，是这几个单测的目的是在 local calsspath 里能验证 decalredMode 的作用。可以换个思路考虑：完成这个目的，是否必须依赖 maven-archiver 的 pom.properties

**Comment by compasty** [comment]
是否对于这种本地路径artifactId解析，是否可以考虑使用额外补充基于pom.xml文件进行artifactId解析

**Comment by lvjing2** [comment]
> 是否对于这种本地路径artifactId解析，是否可以考虑使用额外补充基于pom.xml文件进行artifactId解析

可以的，麻烦补充下单测呢
