### ISSUE TITLE
文件路径包含空格无法启动项目工程

### ISSUE THREAD

**Issue by jsc12138446** [sofastack/sofa-ark#724]
项目工程文件打包为jar包后，项目存放路径包含空格时无法启动

原文件路径：

![image](https://github.com/sofastack/sofa-ark/assets/144100954/8a3cea6b-4216-4844-9d70-5cf23ef4e067)

sofa解析后替换为%20导致抛出异常：

![image](https://github.com/sofastack/sofa-ark/assets/144100954/4b31f308-66b4-478f-927e-7e53a133c3a1)

**Comment by lvjing2** [comment]
问下，你使用的的 SOFAArk 什么版本？我们再这个 pr 里有修复这个问题
https://github.com/sofastack/sofa-ark/pull/698

**Comment by jsc12138446** [comment]
我们使用的是2.2.2版本，这个问题好像还是存在

**Comment by lvjing2** [comment]
能看下是哪里导致这个问题还在的吗？也欢迎提 PR 修复

**Comment by jsc12138446** [comment]
![image](https://github.com/sofastack/sofa-ark/assets/144100954/88892bf5-3fd5-4147-b3f1-fbc336450a00)

**Comment by jsc12138446** [comment]
> 能看下是哪里导致这个问题还在的吗？也欢迎提 PR 修复

url获取到的文件路径是通过encode方法转换后的结果，空格转换为了%20，解析创建file对象时需要解码decode，再创建File文件。

**Comment by jsc12138446** [comment]
![image](https://github.com/sofastack/sofa-ark/assets/144100954/18b29ca0-a0db-407e-bdc1-666cd3d7f49a)

这是目前排查到有问题的地方，最好一起统一解决

**Comment by lvjing2** [comment]
> > 能看下是哪里导致这个问题还在的吗？也欢迎提 PR 修复
> 
> url获取到的文件路径是通过encode方法转换后的结果，空格转换为了%20，解析创建file对象时需要解码decode，再创建File文件。

你好，有兴趣提交 PR 修复下吗？

**Comment by FlyAbner** [comment]
> > > 能看下是哪里导致这个问题还在的吗？也欢迎提 PR 修复
> > 
> > 
> > url获取到的文件路径是通过encode方法转换后的结果，空格转换为了%20，解析创建file对象时需要解码decode，再创建File文件。
> 
> @FlyAbner 麻烦看下这个问题呢

收到，我复现下问题，再提个PR

**Comment by lvjing2** [comment]
@FlyAbner 这个麻烦修复下呢
