### ISSUE TITLE
asm api version error

### ISSUE THREAD

**Issue by r67yfyt** [sofastack/sofa-ark#726]
### Describe the question or bug

"com.alipay.sofa.ark.tools.MainClassFinder.ClassDescriptor#ClassDescriptor" set "Opcodes.ASM4"
however
"if (nestHostClass != null) {
    classVisitor.visitNestHost(nestHostClass);
}"
and 
"
public void visitNestHost(final String nestHost) {
  if (api < Opcodes.ASM7) {
    throw new UnsupportedOperationException("NestHost requires ASM7");
  }
  if (cv != null) {
    cv.visitNestHost(nestHost);
  }
}
"
### Expected behavior
set "Opcodes.ASM7"

### Environment

- SOFAArk version: 2.2.3
- JVM version (e.g. `java -version`): java version "17.0.8" 2023-07-18 LTS
- OS version (e.g. `uname -a`): windows 11
- Maven version: 3.8
- IDE version: IDEA 2023.1

**Comment by yuanyuancin** [comment]
业务类有何特点，导致走到了

if (nestHostClass != null) {
      classVisitor.visitNestHost(nestHostClass);
    }

**Comment by r67yfyt** [comment]
> 业务类有何特点，导致走到了
> 
> if (nestHostClass != null) { classVisitor.visitNestHost(nestHostClass); }

有内部类或者使用了内部类的
