### ISSUE TITLE
多Host模式下，如何卸载ark biz的tomcat和jdbc资源

### ISSUE THREAD

**Issue by liyingping1991** [sofastack/sofa-ark#729]
疑问：每个业务模块都可以单独对外提供接口服务，采用了多Host模式，每个业务模块都依赖了web和数据库连接，如何卸载和升级biz？

环境：
- SOFAArk version:2.2.1
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10
- Maven version:3.9.2
- IDE version:IDEA2022.1

**Comment by lvjing2** [comment]
多 host 与 单 host 在卸载上理论没有什么区别，主要原因是 springboot 还没支持动态卸载，目前正在开发中，本月底会发布支持 springboot 动态卸载能力。

**Comment by lvjing2** [comment]
这里是单 host 模式的，可以参考下
https://github.com/sofastack/sofa-serverless/tree/master/samples/web/tomcat
