### ISSUE TITLE
请问下sofaark子应用支持用spring-boot-maven-plugin吗？为什么示例里面子应用还用的sofa-ark-maven-plugin

### ISSUE THREAD

**Issue by jgslvwy** [sofastack/sofa-ark#741]
### Describe the question or bug

A clear and concise description of what the question or bug is.

### Actual behavior

A clear and concise description of what actually happened.

### Steps to reproduce

Steps to reproduce the problem:

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by lvjing2** [comment]
子应用使用 sofa-ark-maven-plugin 构建产物是可以热部署到基座的 jar 包，你要用 spring boot maven plugin 可是可以，子应用本身也是独立的 springboot，只是不能热部署到基座 JVM 上而已。

**Comment by jgslvwy** [comment]
e

**Comment by lylingzhen** [comment]
done. close this issue.

**Comment by jgslvwy** [comment]
e
