### ISSUE TITLE
BizClassLoader卸载失败

### ISSUE THREAD

**Issue by liyingping1991** [sofastack/sofa-ark#809]
环境：
Sofa ark版本2.2.1；
jdk8；
单Host模式；

执行步骤：
在卸载业务包时，
1、先执行业务包ApplicationContext关闭操作，
2、再执行sofa uninstall操作，
3、从主容器的ApplicationContext中获取业务包的tomcat子容器并删除。

疑问：
执行完上述操作后，发现业务包中解压文件中的lib目录中jar包仍旧存在，debug发现BizClassLoader中加载的lib目录下的jar包，未进行清除，BizClassLoader仍持有lib目录下jar包引用，无法卸载。请问如何清除业务包加载的jar包并卸载该BizClassLoader??

**Comment by lvjing2** [comment]
先看下这个 samples 呢？
https://github.com/sofastack/sofa-serverless/tree/master/samples/springboot-samples/web/tomcat

**Comment by liyingping1991** [comment]
业务包目前无法做到全部依赖都采用provide模式，因此，打出的业务包中的lib目录下有jar包，与samples不同；lib目录下有jar包时，卸载就会出现描述的问题。

**Comment by lvjing2** [comment]
lib包中有jar应该没关系的，怀疑是有其他问题，方便加开发者协助群进一步讨论吗？

**Comment by InitEason** [comment]
你好，这个问题有解决么？我也遇到了相同的情况，其他模块的包打在的lib目录下，卸载后unpack目录下的其他文件都删了，就lib里的jar包还被占用。

**Comment by InitEason** [comment]
> 你好，这个问题有解决么？我也遇到了相同的情况，其他模块的包打在的lib目录下，卸载后unpack目录下的其他文件都删了，就lib里的jar包还被占用。

更新一下，BizModel的stop方法里，执行deleteQuietly前，加了行classLoader.close()确保删除操作前资源被释放。

**Comment by lvjing2** [comment]
@liyingping1991 @InitEason 方便加群或者微信交流吗？
开发者协作钉钉群：“Serverless 社区交流与协作群”群的钉钉群号： 24970018417
微信号：zzl_ing

**Comment by lvjing2** [comment]
> > 你好，这个问题有解决么？我也遇到了相同的情况，其他模块的包打在的lib目录下，卸载后unpack目录下的其他文件都删了，就lib里的jar包还被占用。
> 
> 更新一下，BizModel的stop方法里，执行deleteQuietly前，加了行classLoader.close()确保删除操作前资源被释放。

@InitEason 这个方便的话可以提交个 PR，我们验证下

**Comment by lvjing2** [comment]
你好，这个问题还存在吗？
