### ISSUE TITLE
有做过sofa-ark与pf2j的对比吗

### ISSUE THREAD

**Issue by gitYupan** [sofastack/sofa-ark#836]
最近有个产品需求需要使用插件化开发，选型过程中找到了sofa-ark和pf4j两个框架，了解后感觉都能满足需求。想了解下两个框架各自的定位，哪些场景下各有什么优势。

**Comment by CodeNoobKing** [comment]
sofa-ark 是 sofa-serverless 下的一个核心组件，是一个类加载框架。
除了类加载框架，我们还在 sofa-serverless 下围绕 sofa-ark 开发了其他组件：
1. sofa-serverless-runtime：快速适配 springboot/sofaboot 技术栈，并且会解决开源中间件一些不兼容多应用模式的情况。
2. module-controller: 基于 sofa-serverless 开发了一套 jar 代码包层面的云原生调度框架。
3. arkctl: 辅助研发本地快速迭代模块项目。
详情可见：https://github.com/sofastack/sofa-serverless

pf4j 我了解的比较少，得去学习一下，关于 pf4j 的生态可以再多了解了解其他输入。
不过 sofa-serverless 围绕 sofa-ark 做了很多生态上的继续完善，目前也在持续迭代中。

**Comment by lvjing2** [comment]
SOFAArk 只是类隔离组件，而蚂蚁基于 SOFAArk 打造了一套全新的研发框架，从应用架构角度出发解决应用研发遇到的系列问题。这里需要看你们需要解决的是哪类问题了

![image](https://github.com/sofastack/sofa-ark/assets/3754074/e6e1fc18-c646-4deb-bd85-4743ca65df67)

方便加钉钉群详聊吗？“Serverless 社区交流与协作群”群的钉钉群号： 24970018417
或者加我微信 zzl_ing

**Comment by gitYupan** [comment]
感谢回复！确实sofa-serverless 围绕 sofa-ark做了很多生态上完善，我加群在仔细研究下
