### ISSUE TITLE
Telnet默认监听1234端口安全性问题

### ISSUE THREAD

**Issue by TeddyLav** [sofastack/sofa-ark#837]
Telnet默认监听1234端口，其他IP的客户端可以随意访问，请问如何提高安全性，比如只监听localhost？

**Comment by TeddyLav** [comment]
请问具体怎么关闭呢？修改配置文件吗？

**Comment by lvjing2** [comment]
可以通过这个参数配置
`com.alipay.sofa.ark.spi.constant.Constants#TELNET_SERVER_ENABLE`

**Comment by TeddyLav** [comment]
conf/ark/bootstrap.properties或者spring工程resources/application.properties配置文件中加入参数不生效，内容如下：
com.alipay.sofa.ark.spi.constant.Constants.TELNET_SERVER_ENABLE=false

**Comment by lvjing2** [comment]
方便的化，可以麻烦 debug 看下原因，可能哪里配置有问题。这个能力我们一直在使用的，是可以再某些环境关闭 telnet 的。
![image](https://github.com/sofastack/sofa-ark/assets/3754074/908e1f75-a661-4484-a0a1-9acdb0722787)

**Comment by lujg** [comment]
> conf/ark/bootstrap.properties或者spring工程resources/application.properties配置文件中加入参数不生效，内容如下： com.alipay.sofa.ark.spi.constant.Constants.TELNET_SERVER_ENABLE=false

key 不对吧，应该使用代码中实际的 string 值 sofa.ark.telnet.server.enable
