### ISSUE TITLE
ModuleController和SofaArk交互过程中，希望整体梳理下有哪些异常状态，对应的异常处理机制是怎样的？

### ISSUE THREAD

**Issue by thinkergithub** [sofastack/sofa-ark#849]
### Feature description

Describe the feature details with Chinese or English.

### Additional notes

Add other notes if necessary.

**Comment by lvjing2** [comment]
已完成
https://koupleless.io/docs/faq/faq/
https://koupleless.io/docs/tutorials/error_code/
