### ISSUE TITLE
plugin 没必要把自己打到lib内，增加了plugin打包的体积

### ISSUE THREAD

**Issue by yuandongjian** [sofastack/sofa-ark#935]
### Describe the question or bug
sofa-ark-plugin-maven-plugin插件除了会把当前项目shade到plugin内，还会把当前项目的jar包打包到plugin/lib内。

### Expected behavior
期望plugin只保留当前项目的shade，不打包自身jar到plugin/lib内

### Screenshots
![image](https://github.com/sofastack/sofa-ark/assets/35158271/2f75a01b-0314-48b4-a2ff-2570d1ad7443)

### Actual behavior
目前PluginClassLoader会同时包含shade与lib。以上图为例，PluginClassLoader的classpath会同时包含
```
sample-ark-plugin-0.6.0-ark-plugin.jar!/
sample-ark-plugin-0.6.0-ark-plugin.jar!/sample-ark-plugin-0.6.0.jar!/
```
因此，可以去掉plugin/lib下自身的jar包，减少plugin体积。

**Comment by lvjing2** [comment]
@crazy-pizza 方便提 PR 修复下吗

**Comment by crazy-pizza** [comment]
@lvjing2 可以的，帮忙把这个issue分配给我吧
