### ISSUE TITLE
对AOT静态编译的支持情况如何，或者说sofa-ark本身是怎么看待这个问题的

### ISSUE THREAD

**Issue by mengqiang81** [sofastack/sofa-ark#942]
### Feature description

对AOT静态编译的支持情况如何，或者说sofa-ark本身是怎么看待这个问题的，未来是否有支持计划

### Additional notes

Add other notes if necessary.

**Comment by lylingzhen** [comment]
JDK 社区曾经做的 AOT 技术现在已经不维护不支持了。
现在的 GraalVM 技术社区兼容性太差，而且对存量应用代码完全不兼容， 包括蚂蚁内部、外部企业都已经放弃，转而接入 SOFAServerless 了。
