### ISSUE TITLE
单Tomcat多模块场景下, Spring Management 没有复用 Tomcat

### ISSUE THREAD

**Issue by leewaiho** [sofastack/sofa-ark#994]
### Feature description

Describe the feature details with Chinese or English.

 Koupleless 基座 和 Koupleless 模块 通过 application.yml 的 management.server.port 指定了相同端口，基座运行正常，然后在基座上安装指定了相同端口的模块时，报端口已被绑定的异常。

### Additional notes

Add other notes if necessary.

![image](https://github.com/user-attachments/assets/2126c41b-2cef-490e-94dc-54801cf208cf)

![image](https://github.com/user-attachments/assets/fd129d35-dd26-4098-b21f-68c13ea4e534)

![image](https://github.com/user-attachments/assets/064cb454-755b-4001-b0bd-b38935e27aa7)

**Comment by yuanyuancin** [comment]
可能是因为createWebServer时，management child context没有ArkServiceInjectProcessor，导致com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory#embeddedServerService == null，最终走到了普通TomcatServletWebServerFactory的createWebServer逻辑

**Comment by leewaiho** [comment]
我 debug 进去看了一下  确实是因为没有 arkinject 导致的 embedded 为空, 但目前对这块还不是特别熟悉, 不知道要怎么改

**Comment by yuanyuancin** [comment]
1. 可以考虑扩展 web-ark-plugin 的能力，缓存 management context 同 port 时共享 tomcat，目前 EmbededServerService 只缓存 server context tomcat
2. 介入 ManagementContext refresh 时添加 ArkServiceInjectProcessor 如果比较难找到扩展点的话，可以考虑在 ArkTomcatServletWebServerFactory 对 embeddedServerService 做延迟注入，getWebServer 调用时提前inject
ArkClient.getInjectionService().inject(this);
