### ISSUE TITLE
SofaArk打包插件支持开关调整是否指定MainClass

### ISSUE THREAD

**Issue by thinkergithub** [sofastack/sofa-ark#999]
### Feature description

现状：当前sofa的打包插件若不指定MainClass会导致打包报错，因为需要将MainClass写入manifest，但是有些场景是可以通过动态传入MainClass，编译期希望可通过开关跳过MainClass指定。
需求：SofaArk打包插件可以通过开关来控制是否指定MainClass。

### Additional notes

Add other notes if necessary.

**Comment by gaosaroma** [comment]
SOFAArk 打包插件可以在配置中指定 MainClass；如果需要在模块启动时，根据参数动态指定 mainClass，可以考虑在 com.alipay.sofa.ark.container.model.BizModel#doStart 处修改。

**Comment by lvjing2** [comment]
fixed by https://github.com/sofastack/sofa-ark/pull/1029
